import { Prisma, RoleName } from '@prisma/client';
import type { RequestUser } from '../types/request-user';
declare function isShopScopedRole(role: RoleName): boolean;
export { isShopScopedRole };
export declare function tenantCompanyShopWhere(actor: RequestUser): Prisma.ShopWhereInput | null;
export declare function assertShopScope(user: RequestUser, shopId: string | null | undefined): void;
export declare function defaultShopFilter(user: RequestUser): string | undefined;
export declare function shopIdsForUser(user: RequestUser): string[] | undefined;
export declare function companyIdForUser(user: RequestUser): string | undefined;
export declare function requireCompanyId(user: RequestUser): string;
export declare function assertCompanyScope(user: RequestUser, companyId: string | null | undefined): void;
export declare function companyListWhere(actor: RequestUser): Prisma.CompanyWhereInput;
export declare function assertCompanyInTenant(actor: RequestUser, targetCompanyId: string): void;
export declare function userListWhere(actor: RequestUser): Prisma.UserWhereInput;
export declare function assertUserInTenant(actor: RequestUser, targetShopId: string | null): void;
export declare function shopListWhere(actor: RequestUser): Prisma.ShopWhereInput;
export declare function storageLocationListWhere(actor: RequestUser, shopId?: string): Prisma.StorageLocationWhereInput;
export declare function supplierListWhere(actor: RequestUser): Prisma.SupplierWhereInput;
export declare function assertSupplierInTenant(actor: RequestUser, supplierCompanyId: string | null): void;
