"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.loadGoodsReceiptForPdf = loadGoodsReceiptForPdf;
exports.buildGoodsReceiptPdfViewModel = buildGoodsReceiptPdfViewModel;
exports.goodsReceiptPdfFilename = goodsReceiptPdfFilename;
exports.renderGoodsReceiptHtml = renderGoodsReceiptHtml;
const common_1 = require("@nestjs/common");
const document_pdf_formatters_1 = require("../document-pdf.formatters");
const document_layout_template_1 = require("../templates/document-layout.template");
const shop_company_1 = require("./shop-company");
const MIN_ROWS = 8;
async function loadGoodsReceiptForPdf(prisma, id) {
    const gr = await prisma.goodsReceiptHeader.findUnique({
        where: { id },
        include: {
            shop: { select: { shopName: true } },
            purchaseOrder: { select: { poNumber: true } },
            items: { include: { product: { select: { productCode: true, description: true } } } },
        },
    });
    if (!gr)
        throw new common_1.NotFoundException('Goods receipt not found');
    return gr;
}
function formatReceiptType(value) {
    if (!value)
        return 'Full Receipt';
    return value === 'PARTIAL' ? 'Partial Receipt' : 'Full Receipt';
}
function formatInwardShift(value) {
    if (!value)
        return '—';
    return value === 'NIGHT_SHIFT' ? 'Night Shift' : 'Day Shift';
}
async function buildGoodsReceiptPdfViewModel(prisma, gr) {
    const ctx = await (0, shop_company_1.loadShopCompanyContext)(prisma, gr.shopId);
    const supplierRow = gr.purchaseOrderId
        ? await prisma.supplier.findFirst({
            where: {
                companyId: ctx.companyId,
                supplierName: { equals: gr.supplierName.trim(), mode: 'insensitive' },
            },
        })
        : await prisma.supplier.findFirst({
            where: {
                companyId: ctx.companyId,
                supplierName: { equals: gr.supplierName.trim(), mode: 'insensitive' },
            },
        });
    const lines = gr.items.map((item) => ({
        code: item.product?.productCode ?? item.productId.slice(0, 8),
        description: item.product?.description ?? '—',
        qty: `${(0, document_pdf_formatters_1.formatDocumentMoney)(Number(item.quantity))} ${item.uom}`,
        unitPrice: (0, document_pdf_formatters_1.formatDocumentCurrency)(Number(item.purchaseRate)),
        amount: (0, document_pdf_formatters_1.formatDocumentCurrency)(Number(item.lineValue)),
    }));
    const subtotal = gr.items.reduce((sum, item) => sum + Number(item.lineValue), 0);
    const grandTotal = gr.totalValue != null ? Number(gr.totalValue) : subtotal;
    const metaRows = [
        { label: 'Status', value: gr.status },
        { label: 'Plant', value: gr.shop?.shopName ?? ctx.shopName },
        { label: 'Receipt Type', value: formatReceiptType(gr.receiptType) },
        ...(gr.receiptSource === 'OUTSIDE'
            ? [
                { label: 'Purchase Order', value: 'Others' },
                ...(gr.inwardShift ? [{ label: 'Inward Shift', value: formatInwardShift(gr.inwardShift) }] : []),
            ]
            : gr.purchaseOrder
                ? [{ label: 'Purchase Order', value: gr.purchaseOrder.poNumber }]
                : []),
        ...(gr.supplierRef ? [{ label: 'Supplier Ref', value: gr.supplierRef }] : []),
    ];
    return {
        documentTitle: 'GOODS RECEIPT',
        documentNumber: gr.grNumber,
        documentDate: (0, document_pdf_formatters_1.formatDocumentDate)(gr.grDate),
        companyName: ctx.companyName,
        companyLines: ctx.companyLines,
        partyLabel: 'Supplier',
        partyName: supplierRow?.supplierName ?? gr.supplierName,
        partyLines: supplierRow ? (0, shop_company_1.supplierPartyLines)(supplierRow) : [gr.supplierName],
        metaRows,
        lines,
        showExtraColumn: false,
        extraColumnHeader: '',
        padRowCount: Math.max(0, MIN_ROWS - lines.length),
        totals: [
            { label: 'Subtotal', value: (0, document_pdf_formatters_1.formatDocumentCurrency)(subtotal) },
            { label: 'Grand Total', value: (0, document_pdf_formatters_1.formatDocumentCurrency)(grandTotal), bold: true },
        ],
        notes: gr.remarks ?? undefined,
        footerNote: 'This document was generated by SoftdigitIMS.',
    };
}
function goodsReceiptPdfFilename(grNumber) {
    return (0, document_pdf_formatters_1.documentPdfFilename)('goods-receipt', grNumber);
}
function renderGoodsReceiptHtml(viewModel) {
    return (0, document_layout_template_1.buildDocumentLayoutHtml)(viewModel);
}
//# sourceMappingURL=goods-receipt.builder.js.map