"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.loadGoodsIssueForPdf = loadGoodsIssueForPdf;
exports.buildGoodsIssuePdfViewModel = buildGoodsIssuePdfViewModel;
exports.goodsIssuePdfFilename = goodsIssuePdfFilename;
exports.renderGoodsIssueHtml = renderGoodsIssueHtml;
const common_1 = require("@nestjs/common");
const document_pdf_formatters_1 = require("../document-pdf.formatters");
const document_layout_template_1 = require("../templates/document-layout.template");
const shop_company_1 = require("./shop-company");
const MIN_ROWS = 8;
async function loadGoodsIssueForPdf(prisma, id) {
    const gi = await prisma.goodsIssueHeader.findUnique({
        where: { id },
        include: {
            shop: { select: { shopName: true, address: true } },
            items: { include: { product: { select: { productCode: true, description: true } } } },
        },
    });
    if (!gi)
        throw new common_1.NotFoundException('Goods issue not found');
    return gi;
}
async function buildGoodsIssuePdfViewModel(prisma, gi) {
    const ctx = await (0, shop_company_1.loadShopCompanyContext)(prisma, gi.shopId);
    const lines = gi.items.map((item) => ({
        code: item.product?.productCode ?? item.productId.slice(0, 8),
        description: item.product?.description ?? '—',
        qty: `${(0, document_pdf_formatters_1.formatDocumentMoney)(Number(item.quantity))} ${item.uom}`,
        unitPrice: '—',
        amount: (0, document_pdf_formatters_1.formatDocumentMoney)(Number(item.quantity)),
    }));
    const metaRows = [
        { label: 'Status', value: gi.status },
        { label: 'Plant', value: gi.shop?.shopName ?? ctx.shopName },
        { label: 'Issue Reason', value: gi.issueReason },
        ...(gi.postedAt ? [{ label: 'Posted At', value: (0, document_pdf_formatters_1.formatDocumentDate)(gi.postedAt) }] : []),
    ];
    return {
        documentTitle: 'GOODS ISSUE',
        documentNumber: gi.giNumber,
        documentDate: (0, document_pdf_formatters_1.formatDocumentDate)(gi.giDate),
        companyName: ctx.companyName,
        companyLines: ctx.companyLines,
        partyLabel: 'Issuing Plant',
        partyName: gi.shop?.shopName ?? ctx.shopName,
        partyLines: ctx.shopLines,
        metaRows,
        lines,
        showExtraColumn: false,
        extraColumnHeader: '',
        padRowCount: Math.max(0, MIN_ROWS - lines.length),
        totals: [{ label: 'Total Lines', value: String(gi.items.length), bold: true }],
        notes: gi.remarks ?? undefined,
        footerNote: 'This document was generated by SoftdigitIMS.',
    };
}
function goodsIssuePdfFilename(giNumber) {
    return (0, document_pdf_formatters_1.documentPdfFilename)('goods-issue', giNumber);
}
function renderGoodsIssueHtml(viewModel) {
    return (0, document_layout_template_1.buildDocumentLayoutHtml)(viewModel);
}
//# sourceMappingURL=goods-issue.builder.js.map