"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.loadGoodsReturnForPdf = loadGoodsReturnForPdf;
exports.buildGoodsReturnPdfViewModel = buildGoodsReturnPdfViewModel;
exports.goodsReturnPdfFilename = goodsReturnPdfFilename;
exports.renderGoodsReturnHtml = renderGoodsReturnHtml;
const common_1 = require("@nestjs/common");
const document_pdf_formatters_1 = require("../document-pdf.formatters");
const document_layout_template_1 = require("../templates/document-layout.template");
const shop_company_1 = require("./shop-company");
const MIN_ROWS = 6;
function reasonLabel(code) {
    const labels = {
        DAMAGED: 'Damaged',
        EXPIRED: 'Expired',
        WRONG_ITEM: 'Wrong item',
        QUALITY: 'Quality issue',
        OTHER: 'Other',
    };
    return labels[code] ?? code;
}
async function loadGoodsReturnForPdf(prisma, id) {
    const ret = await prisma.supplierReturn.findUnique({
        where: { id },
        include: {
            supplier: true,
            shop: { select: { shopName: true } },
            goodsReceipt: { select: { grNumber: true } },
            items: {
                include: {
                    product: { select: { productCode: true, description: true } },
                    goodsReceiptItem: { include: { product: { select: { productCode: true, description: true } } } },
                },
            },
        },
    });
    if (!ret)
        throw new common_1.NotFoundException('Supplier return not found');
    return ret;
}
async function buildGoodsReturnPdfViewModel(prisma, ret) {
    const ctx = await (0, shop_company_1.loadShopCompanyContext)(prisma, ret.shopId);
    const lines = ret.items.map((item) => ({
        code: item.product?.productCode ?? item.goodsReceiptItem?.product?.productCode ?? item.productId.slice(0, 8),
        description: item.product?.description ?? item.goodsReceiptItem?.product?.description ?? '—',
        qty: (0, document_pdf_formatters_1.formatDocumentMoney)(Number(item.quantity)),
        unitPrice: item.grnQuantity?.toString() ?? item.goodsReceiptItem?.quantity.toString() ?? '—',
        extra: reasonLabel(item.reasonCode ?? 'OTHER'),
        amount: (0, document_pdf_formatters_1.formatDocumentMoney)(Number(item.quantity)),
    }));
    const metaRows = [
        { label: 'Status', value: ret.status },
        { label: 'Goods Receipt', value: ret.goodsReceipt?.grNumber ?? '—' },
        { label: 'Plant', value: ret.shop?.shopName ?? ctx.shopName },
        ...(ret.supplierRef ? [{ label: 'Supplier Ref', value: ret.supplierRef }] : []),
    ];
    return {
        documentTitle: 'GOODS RETURN',
        documentNumber: ret.returnNumber,
        documentDate: (0, document_pdf_formatters_1.formatDocumentDate)(ret.returnDate),
        companyName: ctx.companyName,
        companyLines: ctx.companyLines,
        partyLabel: 'Supplier',
        partyName: ret.supplier?.supplierName ?? ret.supplierName,
        partyLines: ret.supplier ? (0, shop_company_1.supplierPartyLines)(ret.supplier) : [ret.supplierName],
        metaRows,
        lines,
        showExtraColumn: true,
        extraColumnHeader: 'Reason',
        padRowCount: Math.max(0, MIN_ROWS - lines.length),
        totals: [{ label: 'Return Lines', value: String(ret.items.length), bold: true }],
        notes: ret.remarks ?? undefined,
        footerNote: 'This document was generated by SoftdigitIMS.',
    };
}
function goodsReturnPdfFilename(returnNumber) {
    return (0, document_pdf_formatters_1.documentPdfFilename)('goods-return', returnNumber);
}
function renderGoodsReturnHtml(viewModel) {
    return (0, document_layout_template_1.buildDocumentLayoutHtml)(viewModel);
}
//# sourceMappingURL=goods-return.builder.js.map