"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.loadInvoiceForPdf = loadInvoiceForPdf;
exports.buildInvoicePdfViewModel = buildInvoicePdfViewModel;
exports.invoicePdfFilename = invoicePdfFilename;
exports.renderInvoiceHtml = renderInvoiceHtml;
const common_1 = require("@nestjs/common");
const document_pdf_formatters_1 = require("../document-pdf.formatters");
const document_layout_template_1 = require("../templates/document-layout.template");
const shop_company_1 = require("./shop-company");
const MIN_ROWS = 8;
async function loadInvoiceForPdf(prisma, id) {
    const invoice = await prisma.invoiceHeader.findUnique({
        where: { id },
        include: {
            customer: true,
            salesOrder: {
                include: {
                    items: { include: { product: { select: { productCode: true, description: true } } } },
                },
            },
        },
    });
    if (!invoice)
        throw new common_1.NotFoundException('Invoice not found');
    return invoice;
}
async function buildInvoicePdfViewModel(prisma, invoice) {
    const ctx = await (0, shop_company_1.loadShopCompanyContext)(prisma, invoice.shopId);
    const currency = invoice.currency || 'INR';
    const soItems = invoice.salesOrder?.items ?? [];
    const lines = soItems.length > 0
        ? soItems.map((item) => ({
            code: item.product?.productCode ?? item.productId.slice(0, 8),
            description: item.product?.description ?? '—',
            qty: (0, document_pdf_formatters_1.formatDocumentMoney)(Number(item.quantity)),
            unitPrice: (0, document_pdf_formatters_1.formatDocumentCurrency)(Number(item.unitPrice), currency),
            extra: (0, document_pdf_formatters_1.formatDocumentCurrency)(Number(item.taxAmount), currency),
            amount: (0, document_pdf_formatters_1.formatDocumentCurrency)(Number(item.lineValue), currency),
        }))
        : [
            {
                code: '—',
                description: 'Invoice total (no line detail)',
                qty: '1',
                unitPrice: (0, document_pdf_formatters_1.formatDocumentCurrency)(Number(invoice.totalValue), currency),
                extra: (0, document_pdf_formatters_1.formatDocumentCurrency)(Number(invoice.taxAmount), currency),
                amount: (0, document_pdf_formatters_1.formatDocumentCurrency)(Number(invoice.totalValue), currency),
            },
        ];
    const subtotal = soItems.length
        ? soItems.reduce((sum, item) => sum + Number(item.lineValue) - Number(item.taxAmount), 0)
        : Number(invoice.totalValue) - Number(invoice.taxAmount);
    const discount = Number(invoice.discountAmount);
    const tax = Number(invoice.taxAmount);
    const grandTotal = Number(invoice.totalValue);
    const paid = Number(invoice.paidValue);
    const balance = Math.max(grandTotal - paid, 0);
    const metaRows = [
        { label: 'Status', value: invoice.status },
        ...(invoice.salesOrder ? [{ label: 'Sales Order', value: invoice.salesOrder.soNumber }] : []),
        ...(invoice.dueDate ? [{ label: 'Due Date', value: (0, document_pdf_formatters_1.formatDocumentDate)(invoice.dueDate) }] : []),
        { label: 'Plant', value: ctx.shopName },
    ];
    return {
        documentTitle: 'TAX INVOICE',
        documentNumber: invoice.invoiceNumber,
        documentDate: (0, document_pdf_formatters_1.formatDocumentDate)(invoice.invoiceDate),
        companyName: ctx.companyName,
        companyLines: ctx.companyLines,
        partyLabel: 'Bill To',
        partyName: invoice.customer?.customerName ?? '—',
        partyLines: invoice.customer ? (0, shop_company_1.customerPartyLines)(invoice.customer) : [],
        metaRows,
        lines,
        showExtraColumn: true,
        extraColumnHeader: 'Tax',
        padRowCount: Math.max(0, MIN_ROWS - lines.length),
        totals: [
            { label: 'Subtotal', value: (0, document_pdf_formatters_1.formatDocumentCurrency)(subtotal, currency) },
            ...(discount > 0
                ? [{ label: 'Discount', value: (0, document_pdf_formatters_1.formatDocumentCurrency)(discount, currency) }]
                : []),
            { label: 'Tax', value: (0, document_pdf_formatters_1.formatDocumentCurrency)(tax, currency) },
            { label: 'Grand Total', value: (0, document_pdf_formatters_1.formatDocumentCurrency)(grandTotal, currency), bold: true },
            ...(paid > 0 ? [{ label: 'Paid', value: (0, document_pdf_formatters_1.formatDocumentCurrency)(paid, currency) }] : []),
            ...(balance > 0 && paid > 0
                ? [{ label: 'Balance Due', value: (0, document_pdf_formatters_1.formatDocumentCurrency)(balance, currency), bold: true }]
                : []),
        ],
        notes: invoice.remarks ?? undefined,
        footerNote: 'This document was generated by SoftdigitIMS.',
    };
}
function invoicePdfFilename(invoiceNumber) {
    return (0, document_pdf_formatters_1.documentPdfFilename)('invoice', invoiceNumber);
}
function renderInvoiceHtml(viewModel) {
    return (0, document_layout_template_1.buildDocumentLayoutHtml)(viewModel);
}
//# sourceMappingURL=invoice.builder.js.map