import type { PrismaService } from '../../../prisma/prisma.service';
import { type DocumentLayoutViewModel } from '../templates/document-layout.template';
export declare function loadPaymentReceiptForPdf(prisma: PrismaService, id: string): Promise<{
    invoice: {
        customer: {
            shopId: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string | null;
            phone: string | null;
            taxId: string | null;
            street: string | null;
            city: string | null;
            state: string | null;
            postalCode: string | null;
            country: string | null;
            customerCode: string;
            customerName: string;
            pan: string | null;
        };
    } & {
        shopId: string;
        currency: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.InvoiceStatus;
        invoiceNumber: string;
        remarks: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
        templateVersion: number;
        totalValue: import("@prisma/client/runtime/library").Decimal;
        fxRateUsed: import("@prisma/client/runtime/library").Decimal | null;
        discountAmount: import("@prisma/client/runtime/library").Decimal;
        taxAmount: import("@prisma/client/runtime/library").Decimal;
        customerId: string;
        salesOrderId: string | null;
        invoiceDate: Date;
        paidValue: import("@prisma/client/runtime/library").Decimal;
        dueDate: Date | null;
    };
} & {
    shopId: string;
    currency: string;
    id: string;
    createdAt: Date;
    updatedAt: Date;
    createdById: string | null;
    updatedById: string | null;
    invoiceId: string;
    method: string | null;
    remarks: string | null;
    brandingMode: import(".prisma/client").$Enums.BrandingMode;
    brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
    templateVersion: number;
    fxRateUsed: import("@prisma/client/runtime/library").Decimal | null;
    receiptNumber: string;
    receiptDate: Date;
    amount: import("@prisma/client/runtime/library").Decimal;
    reference: string | null;
}>;
export declare function buildPaymentReceiptPdfViewModel(prisma: PrismaService, payment: Awaited<ReturnType<typeof loadPaymentReceiptForPdf>>): Promise<DocumentLayoutViewModel>;
export declare function paymentReceiptPdfFilename(receiptNumber: string): string;
export declare function renderPaymentReceiptHtml(viewModel: DocumentLayoutViewModel): string;
