"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.loadPaymentReceiptForPdf = loadPaymentReceiptForPdf;
exports.buildPaymentReceiptPdfViewModel = buildPaymentReceiptPdfViewModel;
exports.paymentReceiptPdfFilename = paymentReceiptPdfFilename;
exports.renderPaymentReceiptHtml = renderPaymentReceiptHtml;
const common_1 = require("@nestjs/common");
const document_pdf_formatters_1 = require("../document-pdf.formatters");
const document_layout_template_1 = require("../templates/document-layout.template");
const shop_company_1 = require("./shop-company");
async function loadPaymentReceiptForPdf(prisma, id) {
    const payment = await prisma.paymentReceipt.findUnique({
        where: { id },
        include: {
            invoice: { include: { customer: true } },
        },
    });
    if (!payment)
        throw new common_1.NotFoundException('Payment receipt not found');
    return payment;
}
async function buildPaymentReceiptPdfViewModel(prisma, payment) {
    const ctx = await (0, shop_company_1.loadShopCompanyContext)(prisma, payment.shopId);
    const invoice = payment.invoice;
    const customer = invoice.customer;
    const invoiceTotal = Number(invoice.totalValue);
    const paidAfter = Number(invoice.paidValue);
    const amount = Number(payment.amount);
    const balance = Math.max(invoiceTotal - paidAfter, 0);
    const paymentType = balance <= 0 ? 'Full' : 'Partial';
    const metaRows = [
        { label: 'Invoice', value: invoice.invoiceNumber },
        { label: 'Receipt Date', value: (0, document_pdf_formatters_1.formatDocumentDate)(payment.receiptDate) },
        { label: 'Payment Type', value: paymentType },
        ...(payment.method ? [{ label: 'Method', value: payment.method }] : []),
        ...(payment.reference ? [{ label: 'Reference', value: payment.reference }] : []),
        { label: 'Invoice Total', value: (0, document_pdf_formatters_1.formatDocumentCurrency)(invoiceTotal) },
        { label: 'Amount Paid', value: (0, document_pdf_formatters_1.formatDocumentCurrency)(amount) },
        { label: 'Balance Due', value: (0, document_pdf_formatters_1.formatDocumentCurrency)(balance) },
    ];
    return {
        documentTitle: 'PAYMENT RECEIPT',
        documentNumber: payment.receiptNumber,
        documentDate: (0, document_pdf_formatters_1.formatDocumentDate)(payment.receiptDate),
        companyName: ctx.companyName,
        companyLines: ctx.companyLines,
        partyLabel: 'Received From',
        partyName: customer.customerName,
        partyLines: (0, shop_company_1.customerPartyLines)(customer),
        metaRows,
        lines: [
            {
                code: invoice.invoiceNumber,
                description: `Payment against invoice ${invoice.invoiceNumber}`,
                qty: '1',
                unitPrice: (0, document_pdf_formatters_1.formatDocumentCurrency)(amount),
                amount: (0, document_pdf_formatters_1.formatDocumentCurrency)(amount),
            },
        ],
        showExtraColumn: false,
        extraColumnHeader: '',
        padRowCount: 7,
        totals: [
            { label: 'Amount Received', value: (0, document_pdf_formatters_1.formatDocumentCurrency)(amount), bold: true },
            { label: 'Balance on Invoice', value: (0, document_pdf_formatters_1.formatDocumentCurrency)(balance), bold: true },
        ],
        notes: payment.remarks ?? undefined,
        footerNote: 'This document was generated by SoftdigitIMS.',
    };
}
function paymentReceiptPdfFilename(receiptNumber) {
    return (0, document_pdf_formatters_1.documentPdfFilename)('payment', receiptNumber);
}
function renderPaymentReceiptHtml(viewModel) {
    return (0, document_layout_template_1.buildDocumentLayoutHtml)(viewModel);
}
//# sourceMappingURL=payment-receipt.builder.js.map