"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.loadSalesQuotationForPdf = loadSalesQuotationForPdf;
exports.buildSalesQuotationPdfViewModel = buildSalesQuotationPdfViewModel;
exports.salesQuotationPdfFilename = salesQuotationPdfFilename;
exports.renderSalesQuotationHtml = renderSalesQuotationHtml;
const common_1 = require("@nestjs/common");
const document_pdf_formatters_1 = require("../document-pdf.formatters");
const document_layout_template_1 = require("../templates/document-layout.template");
const shop_company_1 = require("./shop-company");
const MIN_ROWS = 8;
async function loadSalesQuotationForPdf(prisma, id) {
    const quote = await prisma.salesQuotationHeader.findUnique({
        where: { id },
        include: {
            customer: true,
            shop: { select: { shopName: true } },
            items: { include: { product: { select: { productCode: true, description: true } } } },
        },
    });
    if (!quote)
        throw new common_1.NotFoundException('Sales quotation not found');
    return quote;
}
async function buildSalesQuotationPdfViewModel(prisma, quote) {
    const ctx = await (0, shop_company_1.loadShopCompanyContext)(prisma, quote.shopId);
    const lines = quote.items.map((item) => ({
        code: item.product?.productCode ?? item.productId.slice(0, 8),
        description: item.product?.description ?? '—',
        qty: `${(0, document_pdf_formatters_1.formatDocumentMoney)(Number(item.quantity))} ${item.uom}`,
        unitPrice: (0, document_pdf_formatters_1.formatDocumentCurrency)(Number(item.unitPrice)),
        amount: (0, document_pdf_formatters_1.formatDocumentCurrency)(Number(item.lineValue)),
    }));
    const subtotal = quote.items.reduce((sum, item) => sum + Number(item.lineValue), 0);
    const grandTotal = quote.totalValue != null ? Number(quote.totalValue) : subtotal;
    const metaRows = [
        { label: 'Status', value: quote.status },
        { label: 'Plant', value: quote.shop?.shopName ?? ctx.shopName },
        ...(quote.validUntil ? [{ label: 'Valid Until', value: (0, document_pdf_formatters_1.formatDocumentDate)(quote.validUntil) }] : []),
    ];
    return {
        documentTitle: 'SALES QUOTATION',
        documentNumber: quote.quoteNumber,
        documentDate: (0, document_pdf_formatters_1.formatDocumentDate)(quote.quoteDate),
        companyName: ctx.companyName,
        companyLines: ctx.companyLines,
        partyLabel: 'Customer',
        partyName: quote.customer?.customerName ?? '—',
        partyLines: quote.customer ? (0, shop_company_1.customerPartyLines)(quote.customer) : [],
        metaRows,
        lines,
        showExtraColumn: false,
        extraColumnHeader: '',
        padRowCount: Math.max(0, MIN_ROWS - lines.length),
        totals: [
            { label: 'Subtotal', value: (0, document_pdf_formatters_1.formatDocumentCurrency)(subtotal) },
            { label: 'Grand Total', value: (0, document_pdf_formatters_1.formatDocumentCurrency)(grandTotal), bold: true },
        ],
        notes: quote.remarks ?? undefined,
        footerNote: 'This document was generated by SoftdigitIMS.',
    };
}
function salesQuotationPdfFilename(quoteNumber) {
    return (0, document_pdf_formatters_1.documentPdfFilename)('sales-quotation', quoteNumber);
}
function renderSalesQuotationHtml(viewModel) {
    return (0, document_layout_template_1.buildDocumentLayoutHtml)(viewModel);
}
//# sourceMappingURL=sales-quotation.builder.js.map