"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.loadSupplierPaymentForPdf = loadSupplierPaymentForPdf;
exports.buildSupplierPaymentPdfViewModel = buildSupplierPaymentPdfViewModel;
exports.supplierPaymentPdfFilename = supplierPaymentPdfFilename;
exports.renderSupplierPaymentHtml = renderSupplierPaymentHtml;
const common_1 = require("@nestjs/common");
const document_pdf_formatters_1 = require("../document-pdf.formatters");
const document_layout_template_1 = require("../templates/document-layout.template");
const shop_company_1 = require("./shop-company");
async function loadSupplierPaymentForPdf(prisma, id) {
    const payment = await prisma.supplierPayment.findUnique({
        where: { id },
        include: {
            supplierBill: {
                include: { supplier: true },
            },
        },
    });
    if (!payment)
        throw new common_1.NotFoundException('Supplier payment not found');
    return payment;
}
async function buildSupplierPaymentPdfViewModel(prisma, payment) {
    const ctx = await (0, shop_company_1.loadShopCompanyContext)(prisma, payment.shopId);
    const bill = payment.supplierBill;
    const supplier = bill.supplier;
    const billTotal = Number(bill.totalValue);
    const paidAfter = Number(bill.paidValue);
    const amount = Number(payment.amount);
    const balance = Math.max(billTotal - paidAfter, 0);
    const paymentType = balance <= 0 ? 'Full' : 'Partial';
    const metaRows = [
        { label: 'Supplier Bill', value: bill.billNumber },
        { label: 'Payment Date', value: (0, document_pdf_formatters_1.formatDocumentDate)(payment.paymentDate) },
        { label: 'Payment Type', value: paymentType },
        ...(payment.method ? [{ label: 'Method', value: payment.method }] : []),
        ...(payment.reference ? [{ label: 'Reference', value: payment.reference }] : []),
        { label: 'Bill Total', value: (0, document_pdf_formatters_1.formatDocumentCurrency)(billTotal) },
        { label: 'Amount Paid', value: (0, document_pdf_formatters_1.formatDocumentCurrency)(amount) },
        { label: 'Balance Due', value: (0, document_pdf_formatters_1.formatDocumentCurrency)(balance) },
    ];
    return {
        documentTitle: 'SUPPLIER PAYMENT',
        documentNumber: payment.paymentNumber,
        documentDate: (0, document_pdf_formatters_1.formatDocumentDate)(payment.paymentDate),
        companyName: ctx.companyName,
        companyLines: ctx.companyLines,
        partyLabel: 'Supplier',
        partyName: supplier.supplierName,
        partyLines: (0, shop_company_1.supplierPartyLines)(supplier),
        metaRows,
        lines: [
            {
                code: bill.billNumber,
                description: `Payment against supplier bill ${bill.billNumber}`,
                qty: '1',
                unitPrice: (0, document_pdf_formatters_1.formatDocumentCurrency)(amount),
                amount: (0, document_pdf_formatters_1.formatDocumentCurrency)(amount),
            },
        ],
        showExtraColumn: false,
        extraColumnHeader: '',
        padRowCount: 7,
        totals: [
            { label: 'Amount Paid', value: (0, document_pdf_formatters_1.formatDocumentCurrency)(amount), bold: true },
            { label: 'Balance on Bill', value: (0, document_pdf_formatters_1.formatDocumentCurrency)(balance), bold: true },
        ],
        notes: payment.remarks ?? undefined,
        footerNote: 'This document was generated by SoftdigitIMS.',
    };
}
function supplierPaymentPdfFilename(paymentNumber) {
    return (0, document_pdf_formatters_1.documentPdfFilename)('supplier-payment', paymentNumber);
}
function renderSupplierPaymentHtml(viewModel) {
    return (0, document_layout_template_1.buildDocumentLayoutHtml)(viewModel);
}
//# sourceMappingURL=supplier-payment.builder.js.map