"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.loadSupplierBillForPdf = loadSupplierBillForPdf;
exports.buildSupplierBillPdfViewModel = buildSupplierBillPdfViewModel;
exports.supplierBillPdfFilename = supplierBillPdfFilename;
exports.renderSupplierBillHtml = renderSupplierBillHtml;
const common_1 = require("@nestjs/common");
const document_pdf_formatters_1 = require("../document-pdf.formatters");
const document_layout_template_1 = require("../templates/document-layout.template");
const shop_company_1 = require("./shop-company");
const MIN_ROWS = 8;
async function loadSupplierBillForPdf(prisma, id) {
    const bill = await prisma.supplierBillHeader.findUnique({
        where: { id },
        include: {
            supplier: true,
            purchaseOrder: { select: { poNumber: true } },
            goodsReceipt: { select: { grNumber: true } },
            items: { include: { product: { select: { productCode: true, description: true } } } },
        },
    });
    if (!bill)
        throw new common_1.NotFoundException('Supplier bill not found');
    return bill;
}
async function buildSupplierBillPdfViewModel(prisma, bill) {
    const ctx = await (0, shop_company_1.loadShopCompanyContext)(prisma, bill.shopId);
    const lines = bill.items.map((item) => ({
        code: item.product?.productCode ?? item.productId.slice(0, 8),
        description: item.product?.description ?? '—',
        qty: `${(0, document_pdf_formatters_1.formatDocumentMoney)(Number(item.quantity))} ${item.uom}`,
        unitPrice: (0, document_pdf_formatters_1.formatDocumentCurrency)(Number(item.unitCost)),
        amount: (0, document_pdf_formatters_1.formatDocumentCurrency)(Number(item.lineValue)),
    }));
    const subtotal = bill.items.reduce((sum, item) => sum + Number(item.lineValue), 0);
    const grandTotal = Number(bill.totalValue);
    const paid = Number(bill.paidValue);
    const balance = Math.max(grandTotal - paid, 0);
    const metaRows = [
        { label: 'Status', value: bill.status },
        ...(bill.purchaseOrder ? [{ label: 'Purchase Order', value: bill.purchaseOrder.poNumber }] : []),
        ...(bill.goodsReceipt ? [{ label: 'Goods Receipt', value: bill.goodsReceipt.grNumber }] : []),
        ...(bill.dueDate ? [{ label: 'Due Date', value: (0, document_pdf_formatters_1.formatDocumentDate)(bill.dueDate) }] : []),
        { label: 'Plant', value: ctx.shopName },
    ];
    return {
        documentTitle: 'SUPPLIER BILL',
        documentNumber: bill.billNumber,
        documentDate: (0, document_pdf_formatters_1.formatDocumentDate)(bill.billDate),
        companyName: ctx.companyName,
        companyLines: ctx.companyLines,
        partyLabel: 'Supplier',
        partyName: bill.supplier?.supplierName ?? '—',
        partyLines: bill.supplier ? (0, shop_company_1.supplierPartyLines)(bill.supplier) : [],
        metaRows,
        lines,
        showExtraColumn: false,
        extraColumnHeader: '',
        padRowCount: Math.max(0, MIN_ROWS - lines.length),
        totals: [
            { label: 'Subtotal', value: (0, document_pdf_formatters_1.formatDocumentCurrency)(subtotal) },
            { label: 'Grand Total', value: (0, document_pdf_formatters_1.formatDocumentCurrency)(grandTotal), bold: true },
            ...(paid > 0 ? [{ label: 'Paid', value: (0, document_pdf_formatters_1.formatDocumentCurrency)(paid) }] : []),
            ...(balance > 0 && paid > 0
                ? [{ label: 'Balance Due', value: (0, document_pdf_formatters_1.formatDocumentCurrency)(balance), bold: true }]
                : []),
        ],
        notes: bill.remarks ?? undefined,
        footerNote: 'This document was generated by SoftdigitIMS.',
    };
}
function supplierBillPdfFilename(billNumber) {
    return (0, document_pdf_formatters_1.documentPdfFilename)('supplier-bill', billNumber);
}
function renderSupplierBillHtml(viewModel) {
    return (0, document_layout_template_1.buildDocumentLayoutHtml)(viewModel);
}
//# sourceMappingURL=supplier-bill.builder.js.map