module.exports = {
  apps: [
    {
      name: 'staging-api',
      script: './apps/api/dist/main.js',
      cwd: '/opt/Inventory-control',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        API_PORT: '3001',
        DATABASE_URL: 'postgresql://retail:retail@127.0.0.1:5433/staging_retail_ims',
        JWT_SECRET: 'staging_jwt_secret_long_random_string_32_chars_12345678901234',
        REFRESH_SECRET: 'staging_refresh_secret_long_random_string_32_chars_abcdefghijk',
        COOKIE_SECRET: 'staging_cookie_secret_long_random_string_32_chars_xyz123456789',
        JWT_ACCESS_EXPIRES: '15m',
        JWT_REFRESH_EXPIRES: '7d',
        BCRYPT_ROUNDS: '12',
        WEB_ORIGIN: 'https://softdigitconsulting.com,https://www.softdigitconsulting.com,http://localhost:5173,http://127.0.0.1:5173,http://localhost:5200,http://127.0.0.1:5200,http://erp-softdigit.tech,https://erp-softdigit.tech,http://api.erp-softdigit.tech,https://api.erp-softdigit.tech,https://api.softdigitconsulting.com,https://inventory-management-saas.vercel.app',
      },
      watch: false,
      ignore_watch: ['node_modules', 'dist'],
      error_file: '/var/log/pm2/staging-api-error.log',
      out_file: '/var/log/pm2/staging-api.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      restart_delay: 1000,
      autorestart: true,
      max_memory_restart: '1G',
    },
  ],
};
