import { InvoiceStatus, Prisma } from '@prisma/client';
import { PrismaService } from '../../prisma/prisma.service';
import type { RequestUser } from '../../common/types/request-user';
import { AuditService } from '../audit/audit.service';
import { DocumentNumberService } from '../stock/document-number.service';
import { CreateInvoiceDto } from './dto/create-invoice.dto';
import { SubscriptionService } from '../billing/subscription.service';
import { EmailNotificationsService } from '../email-notifications/email-notifications.service';
import { DocumentEmailService } from '../document-email/document-email.service';
export type InvoiceListQuery = {
    shop_id?: string;
    status?: InvoiceStatus;
    customer_id?: string;
    date_from?: string;
    date_to?: string;
    cursor?: string;
    take?: number;
};
export declare class InvoicesService {
    private readonly prisma;
    private readonly audit;
    private readonly numbers;
    private readonly subscriptions;
    private readonly emailNotifications;
    private readonly documentEmail;
    constructor(prisma: PrismaService, audit: AuditService, numbers: DocumentNumberService, subscriptions: SubscriptionService, emailNotifications: EmailNotificationsService, documentEmail: DocumentEmailService);
    list(user: RequestUser, query?: InvoiceListQuery): Promise<{
        data: {
            shopId: string;
            customer: {
                id: string;
                customerCode: string;
                customerName: string;
            };
            id: string;
            status: import(".prisma/client").$Enums.InvoiceStatus;
            invoiceNumber: string;
            totalValue: Prisma.Decimal;
            customerId: string;
            salesOrderId: string | null;
            invoiceDate: Date;
            paidValue: Prisma.Decimal;
            dueDate: Date | null;
        }[];
        meta: {
            nextCursor: string | null;
            limit: number;
            hasMore: boolean;
        };
    }>;
    create(user: RequestUser, dto: CreateInvoiceDto): Promise<{
        customer: {
            shopId: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string | null;
            phone: string | null;
            taxId: string | null;
            street: string | null;
            city: string | null;
            state: string | null;
            postalCode: string | null;
            country: string | null;
            customerCode: string;
            customerName: string;
            pan: string | null;
        };
        payments: {
            shopId: string;
            currency: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            invoiceId: string;
            method: string | null;
            remarks: string | null;
            brandingMode: import(".prisma/client").$Enums.BrandingMode;
            brandingSnapshot: Prisma.JsonValue | null;
            templateVersion: number;
            fxRateUsed: Prisma.Decimal | null;
            receiptNumber: string;
            receiptDate: Date;
            amount: Prisma.Decimal;
            reference: string | null;
        }[];
        salesOrder: {
            shopId: string;
            currency: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            status: import(".prisma/client").$Enums.SalesOrderStatus;
            remarks: string | null;
            brandingMode: import(".prisma/client").$Enums.BrandingMode;
            brandingSnapshot: Prisma.JsonValue | null;
            templateVersion: number;
            totalValue: Prisma.Decimal | null;
            fxRateUsed: Prisma.Decimal | null;
            discountAmount: Prisma.Decimal;
            taxAmount: Prisma.Decimal;
            customerId: string;
            soNumber: string;
            orderDate: Date;
            expectedDate: Date | null;
            fulfillmentStatus: import(".prisma/client").$Enums.FulfillmentStatus;
            gstSupplyType: import(".prisma/client").$Enums.GstSupplyType;
            subtotalBeforeTax: Prisma.Decimal;
            totalCgst: Prisma.Decimal;
            totalSgst: Prisma.Decimal;
            totalIgst: Prisma.Decimal;
        } | null;
    } & {
        shopId: string;
        currency: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.InvoiceStatus;
        invoiceNumber: string;
        remarks: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: Prisma.JsonValue | null;
        templateVersion: number;
        totalValue: Prisma.Decimal;
        fxRateUsed: Prisma.Decimal | null;
        discountAmount: Prisma.Decimal;
        taxAmount: Prisma.Decimal;
        customerId: string;
        salesOrderId: string | null;
        invoiceDate: Date;
        paidValue: Prisma.Decimal;
        dueDate: Date | null;
    }>;
    sendToCustomer(user: RequestUser, id: string, options?: {
        resend?: boolean;
    }): Promise<import("../document-email/document-email.types").DocumentEmailSendResult>;
    private buildInvoiceEmailContent;
    private autoSendInvoiceCreatedEmail;
    get(user: RequestUser, id: string): Promise<{
        customer: {
            shopId: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string | null;
            phone: string | null;
            taxId: string | null;
            street: string | null;
            city: string | null;
            state: string | null;
            postalCode: string | null;
            country: string | null;
            customerCode: string;
            customerName: string;
            pan: string | null;
        };
        payments: {
            shopId: string;
            currency: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            invoiceId: string;
            method: string | null;
            remarks: string | null;
            brandingMode: import(".prisma/client").$Enums.BrandingMode;
            brandingSnapshot: Prisma.JsonValue | null;
            templateVersion: number;
            fxRateUsed: Prisma.Decimal | null;
            receiptNumber: string;
            receiptDate: Date;
            amount: Prisma.Decimal;
            reference: string | null;
        }[];
        salesOrder: {
            shopId: string;
            currency: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            status: import(".prisma/client").$Enums.SalesOrderStatus;
            remarks: string | null;
            brandingMode: import(".prisma/client").$Enums.BrandingMode;
            brandingSnapshot: Prisma.JsonValue | null;
            templateVersion: number;
            totalValue: Prisma.Decimal | null;
            fxRateUsed: Prisma.Decimal | null;
            discountAmount: Prisma.Decimal;
            taxAmount: Prisma.Decimal;
            customerId: string;
            soNumber: string;
            orderDate: Date;
            expectedDate: Date | null;
            fulfillmentStatus: import(".prisma/client").$Enums.FulfillmentStatus;
            gstSupplyType: import(".prisma/client").$Enums.GstSupplyType;
            subtotalBeforeTax: Prisma.Decimal;
            totalCgst: Prisma.Decimal;
            totalSgst: Prisma.Decimal;
            totalIgst: Prisma.Decimal;
        } | null;
    } & {
        shopId: string;
        currency: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.InvoiceStatus;
        invoiceNumber: string;
        remarks: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: Prisma.JsonValue | null;
        templateVersion: number;
        totalValue: Prisma.Decimal;
        fxRateUsed: Prisma.Decimal | null;
        discountAmount: Prisma.Decimal;
        taxAmount: Prisma.Decimal;
        customerId: string;
        salesOrderId: string | null;
        invoiceDate: Date;
        paidValue: Prisma.Decimal;
        dueDate: Date | null;
    }>;
}
