import type { RequestUser } from '../../common/types/request-user';
import { CreateInvoiceDto } from './dto/create-invoice.dto';
import { ListInvoicesDto } from './dto/list-invoices.dto';
import { InvoicesService } from './invoices.service';
export declare class InvoicesController {
    private readonly invoices;
    constructor(invoices: InvoicesService);
    list(user: RequestUser, query: ListInvoicesDto): Promise<{
        data: {
            shopId: string;
            customer: {
                id: string;
                customerCode: string;
                customerName: string;
            };
            id: string;
            status: import(".prisma/client").$Enums.InvoiceStatus;
            invoiceNumber: string;
            totalValue: import("@prisma/client/runtime/library").Decimal;
            customerId: string;
            salesOrderId: string | null;
            invoiceDate: Date;
            paidValue: import("@prisma/client/runtime/library").Decimal;
            dueDate: Date | null;
        }[];
        meta: {
            nextCursor: string | null;
            limit: number;
            hasMore: boolean;
        };
    }>;
    create(user: RequestUser, dto: CreateInvoiceDto, idempotencyKey?: string): Promise<{
        customer: {
            shopId: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string | null;
            phone: string | null;
            taxId: string | null;
            street: string | null;
            city: string | null;
            state: string | null;
            postalCode: string | null;
            country: string | null;
            customerCode: string;
            customerName: string;
            pan: string | null;
        };
        payments: {
            shopId: string;
            currency: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            invoiceId: string;
            method: string | null;
            remarks: string | null;
            brandingMode: import(".prisma/client").$Enums.BrandingMode;
            brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
            templateVersion: number;
            fxRateUsed: import("@prisma/client/runtime/library").Decimal | null;
            receiptNumber: string;
            receiptDate: Date;
            amount: import("@prisma/client/runtime/library").Decimal;
            reference: string | null;
        }[];
        salesOrder: {
            shopId: string;
            currency: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            status: import(".prisma/client").$Enums.SalesOrderStatus;
            remarks: string | null;
            brandingMode: import(".prisma/client").$Enums.BrandingMode;
            brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
            templateVersion: number;
            totalValue: import("@prisma/client/runtime/library").Decimal | null;
            fxRateUsed: import("@prisma/client/runtime/library").Decimal | null;
            discountAmount: import("@prisma/client/runtime/library").Decimal;
            taxAmount: import("@prisma/client/runtime/library").Decimal;
            customerId: string;
            soNumber: string;
            orderDate: Date;
            expectedDate: Date | null;
            fulfillmentStatus: import(".prisma/client").$Enums.FulfillmentStatus;
            gstSupplyType: import(".prisma/client").$Enums.GstSupplyType;
            subtotalBeforeTax: import("@prisma/client/runtime/library").Decimal;
            totalCgst: import("@prisma/client/runtime/library").Decimal;
            totalSgst: import("@prisma/client/runtime/library").Decimal;
            totalIgst: import("@prisma/client/runtime/library").Decimal;
        } | null;
    } & {
        shopId: string;
        currency: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.InvoiceStatus;
        invoiceNumber: string;
        remarks: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
        templateVersion: number;
        totalValue: import("@prisma/client/runtime/library").Decimal;
        fxRateUsed: import("@prisma/client/runtime/library").Decimal | null;
        discountAmount: import("@prisma/client/runtime/library").Decimal;
        taxAmount: import("@prisma/client/runtime/library").Decimal;
        customerId: string;
        salesOrderId: string | null;
        invoiceDate: Date;
        paidValue: import("@prisma/client/runtime/library").Decimal;
        dueDate: Date | null;
    }>;
    send(user: RequestUser, id: string, resend?: string): Promise<import("../document-email/document-email.types").DocumentEmailSendResult>;
    get(user: RequestUser, id: string): Promise<{
        customer: {
            shopId: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string | null;
            phone: string | null;
            taxId: string | null;
            street: string | null;
            city: string | null;
            state: string | null;
            postalCode: string | null;
            country: string | null;
            customerCode: string;
            customerName: string;
            pan: string | null;
        };
        payments: {
            shopId: string;
            currency: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            invoiceId: string;
            method: string | null;
            remarks: string | null;
            brandingMode: import(".prisma/client").$Enums.BrandingMode;
            brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
            templateVersion: number;
            fxRateUsed: import("@prisma/client/runtime/library").Decimal | null;
            receiptNumber: string;
            receiptDate: Date;
            amount: import("@prisma/client/runtime/library").Decimal;
            reference: string | null;
        }[];
        salesOrder: {
            shopId: string;
            currency: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            status: import(".prisma/client").$Enums.SalesOrderStatus;
            remarks: string | null;
            brandingMode: import(".prisma/client").$Enums.BrandingMode;
            brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
            templateVersion: number;
            totalValue: import("@prisma/client/runtime/library").Decimal | null;
            fxRateUsed: import("@prisma/client/runtime/library").Decimal | null;
            discountAmount: import("@prisma/client/runtime/library").Decimal;
            taxAmount: import("@prisma/client/runtime/library").Decimal;
            customerId: string;
            soNumber: string;
            orderDate: Date;
            expectedDate: Date | null;
            fulfillmentStatus: import(".prisma/client").$Enums.FulfillmentStatus;
            gstSupplyType: import(".prisma/client").$Enums.GstSupplyType;
            subtotalBeforeTax: import("@prisma/client/runtime/library").Decimal;
            totalCgst: import("@prisma/client/runtime/library").Decimal;
            totalSgst: import("@prisma/client/runtime/library").Decimal;
            totalIgst: import("@prisma/client/runtime/library").Decimal;
        } | null;
    } & {
        shopId: string;
        currency: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.InvoiceStatus;
        invoiceNumber: string;
        remarks: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
        templateVersion: number;
        totalValue: import("@prisma/client/runtime/library").Decimal;
        fxRateUsed: import("@prisma/client/runtime/library").Decimal | null;
        discountAmount: import("@prisma/client/runtime/library").Decimal;
        taxAmount: import("@prisma/client/runtime/library").Decimal;
        customerId: string;
        salesOrderId: string | null;
        invoiceDate: Date;
        paidValue: import("@prisma/client/runtime/library").Decimal;
        dueDate: Date | null;
    }>;
}
