export type GstSalesDocumentLine = {
    description: string;
    hsnSac: string;
    qty: string;
    unitPrice: string;
    cgstPercent: string;
    cgstAmount: string;
    sgstPercent: string;
    sgstAmount: string;
    igstPercent: string;
    igstAmount: string;
    amount: string;
};
export type GstSalesDocumentViewModel = {
    documentTitle: string;
    documentNumber: string;
    documentDate: string;
    terms?: string;
    customerPoNumber?: string;
    placeOfSupply?: string;
    supplyTypeLabel?: string;
    isInterState?: boolean;
    companyName: string;
    companyLines: string[];
    brandingLogoUrl?: string | null;
    brandingInitials?: string | null;
    sealUrl?: string | null;
    signatureUrl?: string | null;
    partyName: string;
    partyLines: string[];
    subject?: string;
    lines: GstSalesDocumentLine[];
    padRowCount: number;
    subtotal: string;
    cgstTotal: string;
    sgstTotal: string;
    igstTotal?: string;
    cgstRateLabel: string;
    sgstRateLabel: string;
    igstRateLabel?: string;
    totalDue: string;
    totalInWords: string;
    notes?: string;
    termsAndConditions?: string;
    bankDetails?: string[];
    footerNote?: string;
    generatedAt?: string;
    generatedBy?: string;
};
export declare function buildGstSalesDocumentHtml(model: GstSalesDocumentViewModel): string;
