export enum AuditReason {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  DEVICE_BLOCKED = 'DEVICE_BLOCKED',
  ACCESS_DENIED = 'ACCESS_DENIED',
  MFA_FAILED = 'MFA_FAILED',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
}
