import type { Response } from 'express';
import type { RequestUser } from "../../common/types/request-user";
import { EwayBillsService } from './eway-bills.service';
import { CreateEwayBillDto, UpdateEwayBillDto, GenerateFromInvoiceDto, CancelEwayBillDto, EwayBillFilterDto } from './dto/eway-bill.dto';
export declare class EwayBillsController {
    private readonly service;
    constructor(service: EwayBillsService);
    list(filter: EwayBillFilterDto, user: RequestUser): Promise<({
        invoice: {
            invoiceNumber: string;
        } | null;
        items: {
            id: string;
            description: string | null;
            hsnCode: string;
            gstRate: import("@prisma/client/runtime/library").Decimal;
            productId: string | null;
            quantity: import("@prisma/client/runtime/library").Decimal;
            ewayBillId: string;
            productName: string;
            unit: string;
            taxableAmount: import("@prisma/client/runtime/library").Decimal;
            cgst: import("@prisma/client/runtime/library").Decimal;
            sgst: import("@prisma/client/runtime/library").Decimal;
            igst: import("@prisma/client/runtime/library").Decimal;
            cess: import("@prisma/client/runtime/library").Decimal;
            total: import("@prisma/client/runtime/library").Decimal;
        }[];
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        documentType: import(".prisma/client").$Enums.EwayDocumentType;
        status: import(".prisma/client").$Enums.EwayBillStatus;
        invoiceId: string | null;
        remarks: string | null;
        totalValue: import("@prisma/client/runtime/library").Decimal;
        transactionType: import(".prisma/client").$Enums.EwayTransactionType;
        documentNumber: string;
        customerId: string | null;
        salesOrderId: string | null;
        ewayBillNumber: string;
        supplyType: import(".prisma/client").$Enums.EwaySupplyType;
        subType: import(".prisma/client").$Enums.EwaySubType;
        documentDate: Date;
        fromGstin: string | null;
        fromName: string;
        fromAddress1: string | null;
        fromAddress2: string | null;
        fromPlace: string | null;
        fromPincode: string | null;
        fromStateCode: string | null;
        toGstin: string | null;
        toName: string;
        toAddress1: string | null;
        toAddress2: string | null;
        toPlace: string | null;
        toPincode: string | null;
        toStateCode: string | null;
        transporterGstin: string | null;
        transporterName: string | null;
        transporterId: string | null;
        transportMode: import(".prisma/client").$Enums.EwayTransportMode;
        transDocNumber: string | null;
        transDocDate: Date | null;
        vehicleNumber: string | null;
        vehicleType: import(".prisma/client").$Enums.EwayVehicleType;
        distanceKm: number | null;
        taxableValue: import("@prisma/client/runtime/library").Decimal;
        cgstValue: import("@prisma/client/runtime/library").Decimal;
        sgstValue: import("@prisma/client/runtime/library").Decimal;
        igstValue: import("@prisma/client/runtime/library").Decimal;
        cessValue: import("@prisma/client/runtime/library").Decimal;
        validUpto: Date | null;
        generatedAt: Date | null;
        cancelledAt: Date | null;
        cancelReason: string | null;
    })[]>;
    stats(user: RequestUser): Promise<{
        draft: number;
        generated: number;
        cancelled: number;
        expired: number;
    }>;
    downloadPdf(id: string, user: RequestUser, res: Response): Promise<void>;
    get(id: string, user: RequestUser): Promise<{
        shop: {
            shopName: string;
        };
        invoice: {
            invoiceNumber: string;
        } | null;
        items: {
            id: string;
            description: string | null;
            hsnCode: string;
            gstRate: import("@prisma/client/runtime/library").Decimal;
            productId: string | null;
            quantity: import("@prisma/client/runtime/library").Decimal;
            ewayBillId: string;
            productName: string;
            unit: string;
            taxableAmount: import("@prisma/client/runtime/library").Decimal;
            cgst: import("@prisma/client/runtime/library").Decimal;
            sgst: import("@prisma/client/runtime/library").Decimal;
            igst: import("@prisma/client/runtime/library").Decimal;
            cess: import("@prisma/client/runtime/library").Decimal;
            total: import("@prisma/client/runtime/library").Decimal;
        }[];
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        documentType: import(".prisma/client").$Enums.EwayDocumentType;
        status: import(".prisma/client").$Enums.EwayBillStatus;
        invoiceId: string | null;
        remarks: string | null;
        totalValue: import("@prisma/client/runtime/library").Decimal;
        transactionType: import(".prisma/client").$Enums.EwayTransactionType;
        documentNumber: string;
        customerId: string | null;
        salesOrderId: string | null;
        ewayBillNumber: string;
        supplyType: import(".prisma/client").$Enums.EwaySupplyType;
        subType: import(".prisma/client").$Enums.EwaySubType;
        documentDate: Date;
        fromGstin: string | null;
        fromName: string;
        fromAddress1: string | null;
        fromAddress2: string | null;
        fromPlace: string | null;
        fromPincode: string | null;
        fromStateCode: string | null;
        toGstin: string | null;
        toName: string;
        toAddress1: string | null;
        toAddress2: string | null;
        toPlace: string | null;
        toPincode: string | null;
        toStateCode: string | null;
        transporterGstin: string | null;
        transporterName: string | null;
        transporterId: string | null;
        transportMode: import(".prisma/client").$Enums.EwayTransportMode;
        transDocNumber: string | null;
        transDocDate: Date | null;
        vehicleNumber: string | null;
        vehicleType: import(".prisma/client").$Enums.EwayVehicleType;
        distanceKm: number | null;
        taxableValue: import("@prisma/client/runtime/library").Decimal;
        cgstValue: import("@prisma/client/runtime/library").Decimal;
        sgstValue: import("@prisma/client/runtime/library").Decimal;
        igstValue: import("@prisma/client/runtime/library").Decimal;
        cessValue: import("@prisma/client/runtime/library").Decimal;
        validUpto: Date | null;
        generatedAt: Date | null;
        cancelledAt: Date | null;
        cancelReason: string | null;
    }>;
    create(dto: CreateEwayBillDto, user: RequestUser): Promise<{
        items: {
            id: string;
            description: string | null;
            hsnCode: string;
            gstRate: import("@prisma/client/runtime/library").Decimal;
            productId: string | null;
            quantity: import("@prisma/client/runtime/library").Decimal;
            ewayBillId: string;
            productName: string;
            unit: string;
            taxableAmount: import("@prisma/client/runtime/library").Decimal;
            cgst: import("@prisma/client/runtime/library").Decimal;
            sgst: import("@prisma/client/runtime/library").Decimal;
            igst: import("@prisma/client/runtime/library").Decimal;
            cess: import("@prisma/client/runtime/library").Decimal;
            total: import("@prisma/client/runtime/library").Decimal;
        }[];
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        documentType: import(".prisma/client").$Enums.EwayDocumentType;
        status: import(".prisma/client").$Enums.EwayBillStatus;
        invoiceId: string | null;
        remarks: string | null;
        totalValue: import("@prisma/client/runtime/library").Decimal;
        transactionType: import(".prisma/client").$Enums.EwayTransactionType;
        documentNumber: string;
        customerId: string | null;
        salesOrderId: string | null;
        ewayBillNumber: string;
        supplyType: import(".prisma/client").$Enums.EwaySupplyType;
        subType: import(".prisma/client").$Enums.EwaySubType;
        documentDate: Date;
        fromGstin: string | null;
        fromName: string;
        fromAddress1: string | null;
        fromAddress2: string | null;
        fromPlace: string | null;
        fromPincode: string | null;
        fromStateCode: string | null;
        toGstin: string | null;
        toName: string;
        toAddress1: string | null;
        toAddress2: string | null;
        toPlace: string | null;
        toPincode: string | null;
        toStateCode: string | null;
        transporterGstin: string | null;
        transporterName: string | null;
        transporterId: string | null;
        transportMode: import(".prisma/client").$Enums.EwayTransportMode;
        transDocNumber: string | null;
        transDocDate: Date | null;
        vehicleNumber: string | null;
        vehicleType: import(".prisma/client").$Enums.EwayVehicleType;
        distanceKm: number | null;
        taxableValue: import("@prisma/client/runtime/library").Decimal;
        cgstValue: import("@prisma/client/runtime/library").Decimal;
        sgstValue: import("@prisma/client/runtime/library").Decimal;
        igstValue: import("@prisma/client/runtime/library").Decimal;
        cessValue: import("@prisma/client/runtime/library").Decimal;
        validUpto: Date | null;
        generatedAt: Date | null;
        cancelledAt: Date | null;
        cancelReason: string | null;
    }>;
    createFromInvoice(dto: GenerateFromInvoiceDto, user: RequestUser): Promise<{
        items: {
            id: string;
            description: string | null;
            hsnCode: string;
            gstRate: import("@prisma/client/runtime/library").Decimal;
            productId: string | null;
            quantity: import("@prisma/client/runtime/library").Decimal;
            ewayBillId: string;
            productName: string;
            unit: string;
            taxableAmount: import("@prisma/client/runtime/library").Decimal;
            cgst: import("@prisma/client/runtime/library").Decimal;
            sgst: import("@prisma/client/runtime/library").Decimal;
            igst: import("@prisma/client/runtime/library").Decimal;
            cess: import("@prisma/client/runtime/library").Decimal;
            total: import("@prisma/client/runtime/library").Decimal;
        }[];
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        documentType: import(".prisma/client").$Enums.EwayDocumentType;
        status: import(".prisma/client").$Enums.EwayBillStatus;
        invoiceId: string | null;
        remarks: string | null;
        totalValue: import("@prisma/client/runtime/library").Decimal;
        transactionType: import(".prisma/client").$Enums.EwayTransactionType;
        documentNumber: string;
        customerId: string | null;
        salesOrderId: string | null;
        ewayBillNumber: string;
        supplyType: import(".prisma/client").$Enums.EwaySupplyType;
        subType: import(".prisma/client").$Enums.EwaySubType;
        documentDate: Date;
        fromGstin: string | null;
        fromName: string;
        fromAddress1: string | null;
        fromAddress2: string | null;
        fromPlace: string | null;
        fromPincode: string | null;
        fromStateCode: string | null;
        toGstin: string | null;
        toName: string;
        toAddress1: string | null;
        toAddress2: string | null;
        toPlace: string | null;
        toPincode: string | null;
        toStateCode: string | null;
        transporterGstin: string | null;
        transporterName: string | null;
        transporterId: string | null;
        transportMode: import(".prisma/client").$Enums.EwayTransportMode;
        transDocNumber: string | null;
        transDocDate: Date | null;
        vehicleNumber: string | null;
        vehicleType: import(".prisma/client").$Enums.EwayVehicleType;
        distanceKm: number | null;
        taxableValue: import("@prisma/client/runtime/library").Decimal;
        cgstValue: import("@prisma/client/runtime/library").Decimal;
        sgstValue: import("@prisma/client/runtime/library").Decimal;
        igstValue: import("@prisma/client/runtime/library").Decimal;
        cessValue: import("@prisma/client/runtime/library").Decimal;
        validUpto: Date | null;
        generatedAt: Date | null;
        cancelledAt: Date | null;
        cancelReason: string | null;
    }>;
    update(id: string, dto: UpdateEwayBillDto, user: RequestUser): Promise<{
        items: {
            id: string;
            description: string | null;
            hsnCode: string;
            gstRate: import("@prisma/client/runtime/library").Decimal;
            productId: string | null;
            quantity: import("@prisma/client/runtime/library").Decimal;
            ewayBillId: string;
            productName: string;
            unit: string;
            taxableAmount: import("@prisma/client/runtime/library").Decimal;
            cgst: import("@prisma/client/runtime/library").Decimal;
            sgst: import("@prisma/client/runtime/library").Decimal;
            igst: import("@prisma/client/runtime/library").Decimal;
            cess: import("@prisma/client/runtime/library").Decimal;
            total: import("@prisma/client/runtime/library").Decimal;
        }[];
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        documentType: import(".prisma/client").$Enums.EwayDocumentType;
        status: import(".prisma/client").$Enums.EwayBillStatus;
        invoiceId: string | null;
        remarks: string | null;
        totalValue: import("@prisma/client/runtime/library").Decimal;
        transactionType: import(".prisma/client").$Enums.EwayTransactionType;
        documentNumber: string;
        customerId: string | null;
        salesOrderId: string | null;
        ewayBillNumber: string;
        supplyType: import(".prisma/client").$Enums.EwaySupplyType;
        subType: import(".prisma/client").$Enums.EwaySubType;
        documentDate: Date;
        fromGstin: string | null;
        fromName: string;
        fromAddress1: string | null;
        fromAddress2: string | null;
        fromPlace: string | null;
        fromPincode: string | null;
        fromStateCode: string | null;
        toGstin: string | null;
        toName: string;
        toAddress1: string | null;
        toAddress2: string | null;
        toPlace: string | null;
        toPincode: string | null;
        toStateCode: string | null;
        transporterGstin: string | null;
        transporterName: string | null;
        transporterId: string | null;
        transportMode: import(".prisma/client").$Enums.EwayTransportMode;
        transDocNumber: string | null;
        transDocDate: Date | null;
        vehicleNumber: string | null;
        vehicleType: import(".prisma/client").$Enums.EwayVehicleType;
        distanceKm: number | null;
        taxableValue: import("@prisma/client/runtime/library").Decimal;
        cgstValue: import("@prisma/client/runtime/library").Decimal;
        sgstValue: import("@prisma/client/runtime/library").Decimal;
        igstValue: import("@prisma/client/runtime/library").Decimal;
        cessValue: import("@prisma/client/runtime/library").Decimal;
        validUpto: Date | null;
        generatedAt: Date | null;
        cancelledAt: Date | null;
        cancelReason: string | null;
    }>;
    generate(id: string, user: RequestUser): Promise<{
        items: {
            id: string;
            description: string | null;
            hsnCode: string;
            gstRate: import("@prisma/client/runtime/library").Decimal;
            productId: string | null;
            quantity: import("@prisma/client/runtime/library").Decimal;
            ewayBillId: string;
            productName: string;
            unit: string;
            taxableAmount: import("@prisma/client/runtime/library").Decimal;
            cgst: import("@prisma/client/runtime/library").Decimal;
            sgst: import("@prisma/client/runtime/library").Decimal;
            igst: import("@prisma/client/runtime/library").Decimal;
            cess: import("@prisma/client/runtime/library").Decimal;
            total: import("@prisma/client/runtime/library").Decimal;
        }[];
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        documentType: import(".prisma/client").$Enums.EwayDocumentType;
        status: import(".prisma/client").$Enums.EwayBillStatus;
        invoiceId: string | null;
        remarks: string | null;
        totalValue: import("@prisma/client/runtime/library").Decimal;
        transactionType: import(".prisma/client").$Enums.EwayTransactionType;
        documentNumber: string;
        customerId: string | null;
        salesOrderId: string | null;
        ewayBillNumber: string;
        supplyType: import(".prisma/client").$Enums.EwaySupplyType;
        subType: import(".prisma/client").$Enums.EwaySubType;
        documentDate: Date;
        fromGstin: string | null;
        fromName: string;
        fromAddress1: string | null;
        fromAddress2: string | null;
        fromPlace: string | null;
        fromPincode: string | null;
        fromStateCode: string | null;
        toGstin: string | null;
        toName: string;
        toAddress1: string | null;
        toAddress2: string | null;
        toPlace: string | null;
        toPincode: string | null;
        toStateCode: string | null;
        transporterGstin: string | null;
        transporterName: string | null;
        transporterId: string | null;
        transportMode: import(".prisma/client").$Enums.EwayTransportMode;
        transDocNumber: string | null;
        transDocDate: Date | null;
        vehicleNumber: string | null;
        vehicleType: import(".prisma/client").$Enums.EwayVehicleType;
        distanceKm: number | null;
        taxableValue: import("@prisma/client/runtime/library").Decimal;
        cgstValue: import("@prisma/client/runtime/library").Decimal;
        sgstValue: import("@prisma/client/runtime/library").Decimal;
        igstValue: import("@prisma/client/runtime/library").Decimal;
        cessValue: import("@prisma/client/runtime/library").Decimal;
        validUpto: Date | null;
        generatedAt: Date | null;
        cancelledAt: Date | null;
        cancelReason: string | null;
    }>;
    cancel(id: string, dto: CancelEwayBillDto, user: RequestUser): Promise<{
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        documentType: import(".prisma/client").$Enums.EwayDocumentType;
        status: import(".prisma/client").$Enums.EwayBillStatus;
        invoiceId: string | null;
        remarks: string | null;
        totalValue: import("@prisma/client/runtime/library").Decimal;
        transactionType: import(".prisma/client").$Enums.EwayTransactionType;
        documentNumber: string;
        customerId: string | null;
        salesOrderId: string | null;
        ewayBillNumber: string;
        supplyType: import(".prisma/client").$Enums.EwaySupplyType;
        subType: import(".prisma/client").$Enums.EwaySubType;
        documentDate: Date;
        fromGstin: string | null;
        fromName: string;
        fromAddress1: string | null;
        fromAddress2: string | null;
        fromPlace: string | null;
        fromPincode: string | null;
        fromStateCode: string | null;
        toGstin: string | null;
        toName: string;
        toAddress1: string | null;
        toAddress2: string | null;
        toPlace: string | null;
        toPincode: string | null;
        toStateCode: string | null;
        transporterGstin: string | null;
        transporterName: string | null;
        transporterId: string | null;
        transportMode: import(".prisma/client").$Enums.EwayTransportMode;
        transDocNumber: string | null;
        transDocDate: Date | null;
        vehicleNumber: string | null;
        vehicleType: import(".prisma/client").$Enums.EwayVehicleType;
        distanceKm: number | null;
        taxableValue: import("@prisma/client/runtime/library").Decimal;
        cgstValue: import("@prisma/client/runtime/library").Decimal;
        sgstValue: import("@prisma/client/runtime/library").Decimal;
        igstValue: import("@prisma/client/runtime/library").Decimal;
        cessValue: import("@prisma/client/runtime/library").Decimal;
        validUpto: Date | null;
        generatedAt: Date | null;
        cancelledAt: Date | null;
        cancelReason: string | null;
    }>;
}
