import { Prisma } from '@prisma/client';
import { PrismaService } from '../../prisma/prisma.service';
import type { RequestUser } from '../../common/types/request-user';
import { CreateEwayBillDto, UpdateEwayBillDto, GenerateFromInvoiceDto, EwayBillFilterDto } from './dto/eway-bill.dto';
export declare class EwayBillsService {
    private readonly prisma;
    constructor(prisma: PrismaService);
    private scopeWhere;
    list(user: RequestUser, filter: EwayBillFilterDto): Promise<({
        invoice: {
            invoiceNumber: string;
        } | null;
        items: {
            id: string;
            description: string | null;
            hsnCode: string;
            gstRate: Prisma.Decimal;
            productId: string | null;
            quantity: Prisma.Decimal;
            ewayBillId: string;
            productName: string;
            unit: string;
            taxableAmount: Prisma.Decimal;
            cgst: Prisma.Decimal;
            sgst: Prisma.Decimal;
            igst: Prisma.Decimal;
            cess: Prisma.Decimal;
            total: Prisma.Decimal;
        }[];
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        documentType: import(".prisma/client").$Enums.EwayDocumentType;
        status: import(".prisma/client").$Enums.EwayBillStatus;
        invoiceId: string | null;
        remarks: string | null;
        totalValue: Prisma.Decimal;
        transactionType: import(".prisma/client").$Enums.EwayTransactionType;
        documentNumber: string;
        customerId: string | null;
        salesOrderId: string | null;
        ewayBillNumber: string;
        supplyType: import(".prisma/client").$Enums.EwaySupplyType;
        subType: import(".prisma/client").$Enums.EwaySubType;
        documentDate: Date;
        fromGstin: string | null;
        fromName: string;
        fromAddress1: string | null;
        fromAddress2: string | null;
        fromPlace: string | null;
        fromPincode: string | null;
        fromStateCode: string | null;
        toGstin: string | null;
        toName: string;
        toAddress1: string | null;
        toAddress2: string | null;
        toPlace: string | null;
        toPincode: string | null;
        toStateCode: string | null;
        transporterGstin: string | null;
        transporterName: string | null;
        transporterId: string | null;
        transportMode: import(".prisma/client").$Enums.EwayTransportMode;
        transDocNumber: string | null;
        transDocDate: Date | null;
        vehicleNumber: string | null;
        vehicleType: import(".prisma/client").$Enums.EwayVehicleType;
        distanceKm: number | null;
        taxableValue: Prisma.Decimal;
        cgstValue: Prisma.Decimal;
        sgstValue: Prisma.Decimal;
        igstValue: Prisma.Decimal;
        cessValue: Prisma.Decimal;
        validUpto: Date | null;
        generatedAt: Date | null;
        cancelledAt: Date | null;
        cancelReason: string | null;
    })[]>;
    get(user: RequestUser, id: string): Promise<{
        shop: {
            shopName: string;
        };
        invoice: {
            invoiceNumber: string;
        } | null;
        items: {
            id: string;
            description: string | null;
            hsnCode: string;
            gstRate: Prisma.Decimal;
            productId: string | null;
            quantity: Prisma.Decimal;
            ewayBillId: string;
            productName: string;
            unit: string;
            taxableAmount: Prisma.Decimal;
            cgst: Prisma.Decimal;
            sgst: Prisma.Decimal;
            igst: Prisma.Decimal;
            cess: Prisma.Decimal;
            total: Prisma.Decimal;
        }[];
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        documentType: import(".prisma/client").$Enums.EwayDocumentType;
        status: import(".prisma/client").$Enums.EwayBillStatus;
        invoiceId: string | null;
        remarks: string | null;
        totalValue: Prisma.Decimal;
        transactionType: import(".prisma/client").$Enums.EwayTransactionType;
        documentNumber: string;
        customerId: string | null;
        salesOrderId: string | null;
        ewayBillNumber: string;
        supplyType: import(".prisma/client").$Enums.EwaySupplyType;
        subType: import(".prisma/client").$Enums.EwaySubType;
        documentDate: Date;
        fromGstin: string | null;
        fromName: string;
        fromAddress1: string | null;
        fromAddress2: string | null;
        fromPlace: string | null;
        fromPincode: string | null;
        fromStateCode: string | null;
        toGstin: string | null;
        toName: string;
        toAddress1: string | null;
        toAddress2: string | null;
        toPlace: string | null;
        toPincode: string | null;
        toStateCode: string | null;
        transporterGstin: string | null;
        transporterName: string | null;
        transporterId: string | null;
        transportMode: import(".prisma/client").$Enums.EwayTransportMode;
        transDocNumber: string | null;
        transDocDate: Date | null;
        vehicleNumber: string | null;
        vehicleType: import(".prisma/client").$Enums.EwayVehicleType;
        distanceKm: number | null;
        taxableValue: Prisma.Decimal;
        cgstValue: Prisma.Decimal;
        sgstValue: Prisma.Decimal;
        igstValue: Prisma.Decimal;
        cessValue: Prisma.Decimal;
        validUpto: Date | null;
        generatedAt: Date | null;
        cancelledAt: Date | null;
        cancelReason: string | null;
    }>;
    create(user: RequestUser, dto: CreateEwayBillDto): Promise<{
        items: {
            id: string;
            description: string | null;
            hsnCode: string;
            gstRate: Prisma.Decimal;
            productId: string | null;
            quantity: Prisma.Decimal;
            ewayBillId: string;
            productName: string;
            unit: string;
            taxableAmount: Prisma.Decimal;
            cgst: Prisma.Decimal;
            sgst: Prisma.Decimal;
            igst: Prisma.Decimal;
            cess: Prisma.Decimal;
            total: Prisma.Decimal;
        }[];
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        documentType: import(".prisma/client").$Enums.EwayDocumentType;
        status: import(".prisma/client").$Enums.EwayBillStatus;
        invoiceId: string | null;
        remarks: string | null;
        totalValue: Prisma.Decimal;
        transactionType: import(".prisma/client").$Enums.EwayTransactionType;
        documentNumber: string;
        customerId: string | null;
        salesOrderId: string | null;
        ewayBillNumber: string;
        supplyType: import(".prisma/client").$Enums.EwaySupplyType;
        subType: import(".prisma/client").$Enums.EwaySubType;
        documentDate: Date;
        fromGstin: string | null;
        fromName: string;
        fromAddress1: string | null;
        fromAddress2: string | null;
        fromPlace: string | null;
        fromPincode: string | null;
        fromStateCode: string | null;
        toGstin: string | null;
        toName: string;
        toAddress1: string | null;
        toAddress2: string | null;
        toPlace: string | null;
        toPincode: string | null;
        toStateCode: string | null;
        transporterGstin: string | null;
        transporterName: string | null;
        transporterId: string | null;
        transportMode: import(".prisma/client").$Enums.EwayTransportMode;
        transDocNumber: string | null;
        transDocDate: Date | null;
        vehicleNumber: string | null;
        vehicleType: import(".prisma/client").$Enums.EwayVehicleType;
        distanceKm: number | null;
        taxableValue: Prisma.Decimal;
        cgstValue: Prisma.Decimal;
        sgstValue: Prisma.Decimal;
        igstValue: Prisma.Decimal;
        cessValue: Prisma.Decimal;
        validUpto: Date | null;
        generatedAt: Date | null;
        cancelledAt: Date | null;
        cancelReason: string | null;
    }>;
    createFromInvoice(user: RequestUser, dto: GenerateFromInvoiceDto): Promise<{
        items: {
            id: string;
            description: string | null;
            hsnCode: string;
            gstRate: Prisma.Decimal;
            productId: string | null;
            quantity: Prisma.Decimal;
            ewayBillId: string;
            productName: string;
            unit: string;
            taxableAmount: Prisma.Decimal;
            cgst: Prisma.Decimal;
            sgst: Prisma.Decimal;
            igst: Prisma.Decimal;
            cess: Prisma.Decimal;
            total: Prisma.Decimal;
        }[];
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        documentType: import(".prisma/client").$Enums.EwayDocumentType;
        status: import(".prisma/client").$Enums.EwayBillStatus;
        invoiceId: string | null;
        remarks: string | null;
        totalValue: Prisma.Decimal;
        transactionType: import(".prisma/client").$Enums.EwayTransactionType;
        documentNumber: string;
        customerId: string | null;
        salesOrderId: string | null;
        ewayBillNumber: string;
        supplyType: import(".prisma/client").$Enums.EwaySupplyType;
        subType: import(".prisma/client").$Enums.EwaySubType;
        documentDate: Date;
        fromGstin: string | null;
        fromName: string;
        fromAddress1: string | null;
        fromAddress2: string | null;
        fromPlace: string | null;
        fromPincode: string | null;
        fromStateCode: string | null;
        toGstin: string | null;
        toName: string;
        toAddress1: string | null;
        toAddress2: string | null;
        toPlace: string | null;
        toPincode: string | null;
        toStateCode: string | null;
        transporterGstin: string | null;
        transporterName: string | null;
        transporterId: string | null;
        transportMode: import(".prisma/client").$Enums.EwayTransportMode;
        transDocNumber: string | null;
        transDocDate: Date | null;
        vehicleNumber: string | null;
        vehicleType: import(".prisma/client").$Enums.EwayVehicleType;
        distanceKm: number | null;
        taxableValue: Prisma.Decimal;
        cgstValue: Prisma.Decimal;
        sgstValue: Prisma.Decimal;
        igstValue: Prisma.Decimal;
        cessValue: Prisma.Decimal;
        validUpto: Date | null;
        generatedAt: Date | null;
        cancelledAt: Date | null;
        cancelReason: string | null;
    }>;
    update(user: RequestUser, id: string, dto: UpdateEwayBillDto): Promise<{
        items: {
            id: string;
            description: string | null;
            hsnCode: string;
            gstRate: Prisma.Decimal;
            productId: string | null;
            quantity: Prisma.Decimal;
            ewayBillId: string;
            productName: string;
            unit: string;
            taxableAmount: Prisma.Decimal;
            cgst: Prisma.Decimal;
            sgst: Prisma.Decimal;
            igst: Prisma.Decimal;
            cess: Prisma.Decimal;
            total: Prisma.Decimal;
        }[];
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        documentType: import(".prisma/client").$Enums.EwayDocumentType;
        status: import(".prisma/client").$Enums.EwayBillStatus;
        invoiceId: string | null;
        remarks: string | null;
        totalValue: Prisma.Decimal;
        transactionType: import(".prisma/client").$Enums.EwayTransactionType;
        documentNumber: string;
        customerId: string | null;
        salesOrderId: string | null;
        ewayBillNumber: string;
        supplyType: import(".prisma/client").$Enums.EwaySupplyType;
        subType: import(".prisma/client").$Enums.EwaySubType;
        documentDate: Date;
        fromGstin: string | null;
        fromName: string;
        fromAddress1: string | null;
        fromAddress2: string | null;
        fromPlace: string | null;
        fromPincode: string | null;
        fromStateCode: string | null;
        toGstin: string | null;
        toName: string;
        toAddress1: string | null;
        toAddress2: string | null;
        toPlace: string | null;
        toPincode: string | null;
        toStateCode: string | null;
        transporterGstin: string | null;
        transporterName: string | null;
        transporterId: string | null;
        transportMode: import(".prisma/client").$Enums.EwayTransportMode;
        transDocNumber: string | null;
        transDocDate: Date | null;
        vehicleNumber: string | null;
        vehicleType: import(".prisma/client").$Enums.EwayVehicleType;
        distanceKm: number | null;
        taxableValue: Prisma.Decimal;
        cgstValue: Prisma.Decimal;
        sgstValue: Prisma.Decimal;
        igstValue: Prisma.Decimal;
        cessValue: Prisma.Decimal;
        validUpto: Date | null;
        generatedAt: Date | null;
        cancelledAt: Date | null;
        cancelReason: string | null;
    }>;
    generate(user: RequestUser, id: string): Promise<{
        items: {
            id: string;
            description: string | null;
            hsnCode: string;
            gstRate: Prisma.Decimal;
            productId: string | null;
            quantity: Prisma.Decimal;
            ewayBillId: string;
            productName: string;
            unit: string;
            taxableAmount: Prisma.Decimal;
            cgst: Prisma.Decimal;
            sgst: Prisma.Decimal;
            igst: Prisma.Decimal;
            cess: Prisma.Decimal;
            total: Prisma.Decimal;
        }[];
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        documentType: import(".prisma/client").$Enums.EwayDocumentType;
        status: import(".prisma/client").$Enums.EwayBillStatus;
        invoiceId: string | null;
        remarks: string | null;
        totalValue: Prisma.Decimal;
        transactionType: import(".prisma/client").$Enums.EwayTransactionType;
        documentNumber: string;
        customerId: string | null;
        salesOrderId: string | null;
        ewayBillNumber: string;
        supplyType: import(".prisma/client").$Enums.EwaySupplyType;
        subType: import(".prisma/client").$Enums.EwaySubType;
        documentDate: Date;
        fromGstin: string | null;
        fromName: string;
        fromAddress1: string | null;
        fromAddress2: string | null;
        fromPlace: string | null;
        fromPincode: string | null;
        fromStateCode: string | null;
        toGstin: string | null;
        toName: string;
        toAddress1: string | null;
        toAddress2: string | null;
        toPlace: string | null;
        toPincode: string | null;
        toStateCode: string | null;
        transporterGstin: string | null;
        transporterName: string | null;
        transporterId: string | null;
        transportMode: import(".prisma/client").$Enums.EwayTransportMode;
        transDocNumber: string | null;
        transDocDate: Date | null;
        vehicleNumber: string | null;
        vehicleType: import(".prisma/client").$Enums.EwayVehicleType;
        distanceKm: number | null;
        taxableValue: Prisma.Decimal;
        cgstValue: Prisma.Decimal;
        sgstValue: Prisma.Decimal;
        igstValue: Prisma.Decimal;
        cessValue: Prisma.Decimal;
        validUpto: Date | null;
        generatedAt: Date | null;
        cancelledAt: Date | null;
        cancelReason: string | null;
    }>;
    cancel(user: RequestUser, id: string, reason: string): Promise<{
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        documentType: import(".prisma/client").$Enums.EwayDocumentType;
        status: import(".prisma/client").$Enums.EwayBillStatus;
        invoiceId: string | null;
        remarks: string | null;
        totalValue: Prisma.Decimal;
        transactionType: import(".prisma/client").$Enums.EwayTransactionType;
        documentNumber: string;
        customerId: string | null;
        salesOrderId: string | null;
        ewayBillNumber: string;
        supplyType: import(".prisma/client").$Enums.EwaySupplyType;
        subType: import(".prisma/client").$Enums.EwaySubType;
        documentDate: Date;
        fromGstin: string | null;
        fromName: string;
        fromAddress1: string | null;
        fromAddress2: string | null;
        fromPlace: string | null;
        fromPincode: string | null;
        fromStateCode: string | null;
        toGstin: string | null;
        toName: string;
        toAddress1: string | null;
        toAddress2: string | null;
        toPlace: string | null;
        toPincode: string | null;
        toStateCode: string | null;
        transporterGstin: string | null;
        transporterName: string | null;
        transporterId: string | null;
        transportMode: import(".prisma/client").$Enums.EwayTransportMode;
        transDocNumber: string | null;
        transDocDate: Date | null;
        vehicleNumber: string | null;
        vehicleType: import(".prisma/client").$Enums.EwayVehicleType;
        distanceKm: number | null;
        taxableValue: Prisma.Decimal;
        cgstValue: Prisma.Decimal;
        sgstValue: Prisma.Decimal;
        igstValue: Prisma.Decimal;
        cessValue: Prisma.Decimal;
        validUpto: Date | null;
        generatedAt: Date | null;
        cancelledAt: Date | null;
        cancelReason: string | null;
    }>;
    stats(user: RequestUser): Promise<{
        draft: number;
        generated: number;
        cancelled: number;
        expired: number;
    }>;
    private mapItem;
    private summariseItems;
    private validateForGeneration;
    private draftNumber;
    private officialNumber;
    private validUpto;
    generatePdf(user: RequestUser, billId: string): Promise<Buffer>;
}
