import { DocumentEmailTrigger } from '@prisma/client';
import { Queue } from 'bullmq';
import type { RequestUser } from '../../common/types/request-user';
import { DocumentPdfService } from '../../common/pdf/document-pdf.service';
import { MailService } from '../../common/mail/mail.service';
import type { PurchaseOrderEmailContent } from '../../common/mail/purchase-order-supplier.template';
import type { ReturnNoticeEmailContent } from '../../common/mail/return-notice.template';
import type { SalesQuotationEmailContent } from '../../common/mail/sales-quotation.template';
import type { GoodsReceiptSupplierEmailContent, InvoiceCreatedEmailContent, PaymentReceivedEmailContent, SalesOrderCustomerEmailContent, SupplierBillIssuedEmailContent, SupplierPaymentRecordedEmailContent } from '../../common/mail/transactional-email.templates';
import { PrismaService } from '../../prisma/prisma.service';
import { AuditService } from '../audit/audit.service';
import { ReturnImageStorageService } from '../../common/upload/return-image-storage.service';
import { EmailNotificationsService } from '../email-notifications/email-notifications.service';
import type { DocumentEmailHistoryRow, DocumentEmailSendResult, DocumentEmailSummary, EmailOverrides } from './document-email.types';
type OutboxJobData = {
    outboxId: string;
};
export declare class DocumentEmailService {
    private readonly prisma;
    private readonly documentPdf;
    private readonly mail;
    private readonly emailNotifications;
    private readonly audit;
    private readonly returnImages;
    private readonly queue;
    private readonly logger;
    constructor(prisma: PrismaService, documentPdf: DocumentPdfService, mail: MailService, emailNotifications: EmailNotificationsService, audit: AuditService, returnImages: ReturnImageStorageService, queue: Queue<OutboxJobData>);
    listHistory(entityType: string, entityId: string): Promise<DocumentEmailHistoryRow[]>;
    getLatestSummary(entityType: string, entityId: string): Promise<DocumentEmailSummary | null>;
    sendPurchaseOrderEmail(user: RequestUser, args: {
        poId: string;
        companyId: string;
        shopId: string;
        recipient: string;
        content: PurchaseOrderEmailContent;
        prepared: EmailOverrides;
        documentNumber: string;
        trigger: DocumentEmailTrigger;
    }): Promise<DocumentEmailSendResult>;
    sendInvoiceEmail(user: RequestUser, args: {
        invoiceId: string;
        companyId: string;
        shopId: string;
        recipient: string;
        content: InvoiceCreatedEmailContent;
        prepared: EmailOverrides;
        documentNumber: string;
        trigger: DocumentEmailTrigger;
    }): Promise<DocumentEmailSendResult>;
    sendPaymentEmail(user: RequestUser, args: {
        paymentId: string;
        companyId: string;
        shopId: string;
        recipient: string;
        content: PaymentReceivedEmailContent;
        prepared: EmailOverrides;
        documentNumber: string;
        trigger: DocumentEmailTrigger;
    }): Promise<DocumentEmailSendResult>;
    sendSalesOrderEmail(user: RequestUser, args: {
        salesOrderId: string;
        companyId: string;
        shopId: string;
        recipient: string;
        content: SalesOrderCustomerEmailContent;
        prepared: EmailOverrides;
        documentNumber: string;
        trigger: DocumentEmailTrigger;
    }): Promise<DocumentEmailSendResult>;
    sendSupplierBillEmail(user: RequestUser, args: {
        billId: string;
        companyId: string;
        shopId: string;
        recipient: string;
        content: SupplierBillIssuedEmailContent;
        prepared: EmailOverrides;
        documentNumber: string;
        trigger: DocumentEmailTrigger;
    }): Promise<DocumentEmailSendResult>;
    sendSupplierPaymentEmail(user: RequestUser, args: {
        paymentId: string;
        companyId: string;
        shopId: string;
        recipient: string;
        content: SupplierPaymentRecordedEmailContent;
        prepared: EmailOverrides;
        documentNumber: string;
        trigger: DocumentEmailTrigger;
    }): Promise<DocumentEmailSendResult>;
    sendGoodsReceiptEmail(user: RequestUser, args: {
        grId: string;
        companyId: string;
        shopId: string;
        recipient: string;
        content: GoodsReceiptSupplierEmailContent;
        prepared: EmailOverrides;
        documentNumber: string;
        trigger: DocumentEmailTrigger;
    }): Promise<DocumentEmailSendResult>;
    sendSalesQuotationEmail(user: RequestUser, args: {
        quoteId: string;
        companyId: string;
        shopId: string;
        recipient: string;
        content: SalesQuotationEmailContent;
        prepared: EmailOverrides;
        documentNumber: string;
        trigger: DocumentEmailTrigger;
    }): Promise<DocumentEmailSendResult>;
    sendGoodsReturnEmail(user: RequestUser, args: {
        returnId: string;
        companyId: string;
        shopId: string;
        recipient: string;
        content: ReturnNoticeEmailContent;
        prepared: EmailOverrides;
        documentNumber: string;
        trigger: DocumentEmailTrigger;
        cc?: string;
    }): Promise<DocumentEmailSendResult>;
    private enqueueDocumentEmail;
    processOutbox(outboxId: string, actorUserId?: string): Promise<DocumentEmailSendResult>;
    scheduleBackgroundRetry(outboxId: string, lastError: string): Promise<void>;
    private renderPdfForPayload;
    private loadReturnImageAttachments;
    private sendMailForPayload;
    private writeAudit;
    private serializeHistoryRow;
}
export {};
