import { PrismaService } from '../../prisma/prisma.service';
import type { RequestUser } from '../../common/types/request-user';
import { CreateCompanyDto } from './dto/create-company.dto';
import { UpdateCompanyDto } from './dto/update-company.dto';
import { BrandingProfileService } from '../../common/branding/branding-profile.service';
import { BrandingResolverService } from '../../common/branding/branding-resolver.service';
import type { UpdateBrandingProfileDto } from '../../common/branding/dto/update-branding-profile.dto';
export declare class CompaniesService {
    private readonly prisma;
    private readonly branding;
    private readonly brandingResolver;
    constructor(prisma: PrismaService, branding: BrandingProfileService, brandingResolver: BrandingResolverService);
    list(user: RequestUser): Promise<{
        id: string;
        companyCode: string;
        companyName: string;
        address: string | null;
        brandingProfileId: string | null;
        isActive: boolean;
        subscriptionPlan: import(".prisma/client").$Enums.SubscriptionPlan;
        billingCycle: import(".prisma/client").$Enums.BillingCycle | null;
        subscriptionStatus: import(".prisma/client").$Enums.SubscriptionStatus;
        trialStartsAt: Date | null;
        trialEndsAt: Date | null;
        subscriptionEndsAt: Date | null;
        platformMarketingOptOut: boolean;
        razorpaySubscriptionId: string | null;
        paidActivatedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
    }[]>;
    create(user: RequestUser, dto: CreateCompanyDto): Promise<void>;
    get(user: RequestUser, id: string): Promise<{
        id: string;
        companyCode: string;
        companyName: string;
        address: string | null;
        brandingProfileId: string | null;
        isActive: boolean;
        subscriptionPlan: import(".prisma/client").$Enums.SubscriptionPlan;
        billingCycle: import(".prisma/client").$Enums.BillingCycle | null;
        subscriptionStatus: import(".prisma/client").$Enums.SubscriptionStatus;
        trialStartsAt: Date | null;
        trialEndsAt: Date | null;
        subscriptionEndsAt: Date | null;
        platformMarketingOptOut: boolean;
        razorpaySubscriptionId: string | null;
        paidActivatedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
    }>;
    update(user: RequestUser, id: string, dto: UpdateCompanyDto): Promise<{
        id: string;
        companyCode: string;
        companyName: string;
        address: string | null;
        brandingProfileId: string | null;
        isActive: boolean;
        subscriptionPlan: import(".prisma/client").$Enums.SubscriptionPlan;
        billingCycle: import(".prisma/client").$Enums.BillingCycle | null;
        subscriptionStatus: import(".prisma/client").$Enums.SubscriptionStatus;
        trialStartsAt: Date | null;
        trialEndsAt: Date | null;
        subscriptionEndsAt: Date | null;
        platformMarketingOptOut: boolean;
        razorpaySubscriptionId: string | null;
        paidActivatedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
    }>;
    updateBranding(user: RequestUser, id: string, dto: UpdateBrandingProfileDto, logo?: Express.Multer.File): Promise<{
        id: string;
        companyName: string | null;
        address: string | null;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        brandingVersion: number;
        logoAssetId: string | null;
        watermarkAssetId: string | null;
        sealAssetId: string | null;
        signatureAssetId: string | null;
        letterheadAssetId: string | null;
        gstNumber: string | null;
        footerText: string | null;
        email: string | null;
        phone: string | null;
        website: string | null;
        primaryColor: string | null;
        secondaryColor: string | null;
        accentColor: string | null;
    }>;
    getBranding(user: RequestUser, id: string): Promise<{
        profile: import("../../common/branding/branding.types").ResolvedBrandingProfile;
        health: {
            score: number;
            missing: string[];
        };
    }>;
    remove(user: RequestUser, id: string): Promise<{
        id: string;
        companyCode: string;
        companyName: string;
        address: string | null;
        brandingProfileId: string | null;
        isActive: boolean;
        subscriptionPlan: import(".prisma/client").$Enums.SubscriptionPlan;
        billingCycle: import(".prisma/client").$Enums.BillingCycle | null;
        subscriptionStatus: import(".prisma/client").$Enums.SubscriptionStatus;
        trialStartsAt: Date | null;
        trialEndsAt: Date | null;
        subscriptionEndsAt: Date | null;
        platformMarketingOptOut: boolean;
        razorpaySubscriptionId: string | null;
        paidActivatedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
    }>;
}
