import type { RequestUser } from '../../common/types/request-user';
import { CreateRfqDto } from './dto/create-rfq.dto';
import { UpdateRfqDto } from './dto/update-rfq.dto';
import { RfqsService } from './rfqs.service';
export declare class RfqsController {
    private readonly rfqs;
    constructor(rfqs: RfqsService);
    list(user: RequestUser): Promise<{
        fulfillment: {
            totalLines: number;
            linesFullyOrdered: number;
            linesRemaining: number;
            maxPos: number;
            posCreated: number;
            posRemaining: number;
            lines: {
                rfqItemId: string;
                productId: string | null | undefined;
                rfqQty: number;
                orderedQty: number;
                remainingQty: number;
            }[];
        };
        shop: {
            id: string;
            address: string;
            brandingProfileId: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
            taxId: string | null;
            contactPerson: string;
            mobile: string;
            costingMethod: import(".prisma/client").$Enums.CostingMethod;
            functionalCurrency: string;
        };
        suppliers: ({
            supplier: {
                deletedAt: Date | null;
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                email: string | null;
                phone: string | null;
                companyId: string | null;
                taxId: string | null;
                contactPerson: string | null;
                supplierCode: string;
                supplierName: string;
                vatNumber: string | null;
                rating: number;
                categories: string[];
                street: string | null;
                city: string | null;
                state: string | null;
                postalCode: string | null;
                country: string | null;
                paymentTerms: string | null;
                bankName: string | null;
                accountNumber: string | null;
                routingNumber: string | null;
                iban: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            supplierId: string;
            rfqId: string;
        })[];
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: import("@prisma/client/runtime/library").Decimal;
                purchasePrice: import("@prisma/client/runtime/library").Decimal;
                sellingPrice: import("@prisma/client/runtime/library").Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            } | null;
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            description: string | null;
            uom: string;
            productId: string | null;
            rfqHeaderId: string;
            quantity: import("@prisma/client/runtime/library").Decimal;
            specifications: string | null;
        })[];
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.DocumentStatus;
        rfqNumber: string;
        rfqDate: Date;
        deadline: Date | null;
        title: string;
        notes: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
        templateVersion: number;
        postedAt: Date | null;
    }[]>;
    create(user: RequestUser, dto: CreateRfqDto): Promise<{
        shop: {
            id: string;
            address: string;
            brandingProfileId: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
            taxId: string | null;
            contactPerson: string;
            mobile: string;
            costingMethod: import(".prisma/client").$Enums.CostingMethod;
            functionalCurrency: string;
        };
        suppliers: ({
            supplier: {
                deletedAt: Date | null;
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                email: string | null;
                phone: string | null;
                companyId: string | null;
                taxId: string | null;
                contactPerson: string | null;
                supplierCode: string;
                supplierName: string;
                vatNumber: string | null;
                rating: number;
                categories: string[];
                street: string | null;
                city: string | null;
                state: string | null;
                postalCode: string | null;
                country: string | null;
                paymentTerms: string | null;
                bankName: string | null;
                accountNumber: string | null;
                routingNumber: string | null;
                iban: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            supplierId: string;
            rfqId: string;
        })[];
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: import("@prisma/client/runtime/library").Decimal;
                purchasePrice: import("@prisma/client/runtime/library").Decimal;
                sellingPrice: import("@prisma/client/runtime/library").Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            } | null;
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            description: string | null;
            uom: string;
            productId: string | null;
            rfqHeaderId: string;
            quantity: import("@prisma/client/runtime/library").Decimal;
            specifications: string | null;
        })[];
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.DocumentStatus;
        rfqNumber: string;
        rfqDate: Date;
        deadline: Date | null;
        title: string;
        notes: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
        templateVersion: number;
        postedAt: Date | null;
    }>;
    get(user: RequestUser, id: string): Promise<{
        fulfillment: {
            totalLines: number;
            linesFullyOrdered: number;
            linesRemaining: number;
            maxPos: number;
            posCreated: number;
            posRemaining: number;
            lines: {
                rfqItemId: string;
                productId: string | null | undefined;
                rfqQty: number;
                orderedQty: number;
                remainingQty: number;
            }[];
        };
        shop: {
            id: string;
            address: string;
            brandingProfileId: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
            taxId: string | null;
            contactPerson: string;
            mobile: string;
            costingMethod: import(".prisma/client").$Enums.CostingMethod;
            functionalCurrency: string;
        };
        suppliers: ({
            supplier: {
                deletedAt: Date | null;
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                email: string | null;
                phone: string | null;
                companyId: string | null;
                taxId: string | null;
                contactPerson: string | null;
                supplierCode: string;
                supplierName: string;
                vatNumber: string | null;
                rating: number;
                categories: string[];
                street: string | null;
                city: string | null;
                state: string | null;
                postalCode: string | null;
                country: string | null;
                paymentTerms: string | null;
                bankName: string | null;
                accountNumber: string | null;
                routingNumber: string | null;
                iban: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            supplierId: string;
            rfqId: string;
        })[];
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: import("@prisma/client/runtime/library").Decimal;
                purchasePrice: import("@prisma/client/runtime/library").Decimal;
                sellingPrice: import("@prisma/client/runtime/library").Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            } | null;
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            description: string | null;
            uom: string;
            productId: string | null;
            rfqHeaderId: string;
            quantity: import("@prisma/client/runtime/library").Decimal;
            specifications: string | null;
        })[];
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.DocumentStatus;
        rfqNumber: string;
        rfqDate: Date;
        deadline: Date | null;
        title: string;
        notes: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
        templateVersion: number;
        postedAt: Date | null;
    }>;
    fulfillment(user: RequestUser, id: string): Promise<{
        rfqId: string;
        fulfillment: {
            totalLines: number;
            linesFullyOrdered: number;
            linesRemaining: number;
            maxPos: number;
            posCreated: number;
            posRemaining: number;
            lines: {
                rfqItemId: string;
                productId: string | null | undefined;
                rfqQty: number;
                orderedQty: number;
                remainingQty: number;
            }[];
        };
    }>;
    deletionImpact(user: RequestUser, id: string): Promise<{
        canDelete: boolean;
        quotationCount: number;
        contractCount: number;
        reason: string | null;
    }>;
    update(user: RequestUser, id: string, dto: UpdateRfqDto, ifUnmodifiedSince?: string): Promise<{
        shop: {
            id: string;
            address: string;
            brandingProfileId: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
            taxId: string | null;
            contactPerson: string;
            mobile: string;
            costingMethod: import(".prisma/client").$Enums.CostingMethod;
            functionalCurrency: string;
        };
        suppliers: ({
            supplier: {
                deletedAt: Date | null;
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                email: string | null;
                phone: string | null;
                companyId: string | null;
                taxId: string | null;
                contactPerson: string | null;
                supplierCode: string;
                supplierName: string;
                vatNumber: string | null;
                rating: number;
                categories: string[];
                street: string | null;
                city: string | null;
                state: string | null;
                postalCode: string | null;
                country: string | null;
                paymentTerms: string | null;
                bankName: string | null;
                accountNumber: string | null;
                routingNumber: string | null;
                iban: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            supplierId: string;
            rfqId: string;
        })[];
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: import("@prisma/client/runtime/library").Decimal;
                purchasePrice: import("@prisma/client/runtime/library").Decimal;
                sellingPrice: import("@prisma/client/runtime/library").Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            } | null;
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            description: string | null;
            uom: string;
            productId: string | null;
            rfqHeaderId: string;
            quantity: import("@prisma/client/runtime/library").Decimal;
            specifications: string | null;
        })[];
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.DocumentStatus;
        rfqNumber: string;
        rfqDate: Date;
        deadline: Date | null;
        title: string;
        notes: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
        templateVersion: number;
        postedAt: Date | null;
    }>;
    send(user: RequestUser, id: string): Promise<({
        shop: {
            id: string;
            address: string;
            brandingProfileId: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
            taxId: string | null;
            contactPerson: string;
            mobile: string;
            costingMethod: import(".prisma/client").$Enums.CostingMethod;
            functionalCurrency: string;
        };
        suppliers: ({
            supplier: {
                deletedAt: Date | null;
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                email: string | null;
                phone: string | null;
                companyId: string | null;
                taxId: string | null;
                contactPerson: string | null;
                supplierCode: string;
                supplierName: string;
                vatNumber: string | null;
                rating: number;
                categories: string[];
                street: string | null;
                city: string | null;
                state: string | null;
                postalCode: string | null;
                country: string | null;
                paymentTerms: string | null;
                bankName: string | null;
                accountNumber: string | null;
                routingNumber: string | null;
                iban: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            supplierId: string;
            rfqId: string;
        })[];
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: import("@prisma/client/runtime/library").Decimal;
                purchasePrice: import("@prisma/client/runtime/library").Decimal;
                sellingPrice: import("@prisma/client/runtime/library").Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            } | null;
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            description: string | null;
            uom: string;
            productId: string | null;
            rfqHeaderId: string;
            quantity: import("@prisma/client/runtime/library").Decimal;
            specifications: string | null;
        })[];
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.DocumentStatus;
        rfqNumber: string;
        rfqDate: Date;
        deadline: Date | null;
        title: string;
        notes: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
        templateVersion: number;
        postedAt: Date | null;
    }) | {
        emailDelivery: import("../../common/mail/mail.service").RfqInviteDeliverySummary;
        shop: {
            id: string;
            address: string;
            brandingProfileId: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
            taxId: string | null;
            contactPerson: string;
            mobile: string;
            costingMethod: import(".prisma/client").$Enums.CostingMethod;
            functionalCurrency: string;
        };
        suppliers: ({
            supplier: {
                deletedAt: Date | null;
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                email: string | null;
                phone: string | null;
                companyId: string | null;
                taxId: string | null;
                contactPerson: string | null;
                supplierCode: string;
                supplierName: string;
                vatNumber: string | null;
                rating: number;
                categories: string[];
                street: string | null;
                city: string | null;
                state: string | null;
                postalCode: string | null;
                country: string | null;
                paymentTerms: string | null;
                bankName: string | null;
                accountNumber: string | null;
                routingNumber: string | null;
                iban: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            supplierId: string;
            rfqId: string;
        })[];
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: import("@prisma/client/runtime/library").Decimal;
                purchasePrice: import("@prisma/client/runtime/library").Decimal;
                sellingPrice: import("@prisma/client/runtime/library").Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            } | null;
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            description: string | null;
            uom: string;
            productId: string | null;
            rfqHeaderId: string;
            quantity: import("@prisma/client/runtime/library").Decimal;
            specifications: string | null;
        })[];
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.DocumentStatus;
        rfqNumber: string;
        rfqDate: Date;
        deadline: Date | null;
        title: string;
        notes: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
        templateVersion: number;
        postedAt: Date | null;
    }>;
    resendInvites(user: RequestUser, id: string): Promise<{
        emailDelivery: import("../../common/mail/mail.service").RfqInviteDeliverySummary;
        fulfillment: {
            totalLines: number;
            linesFullyOrdered: number;
            linesRemaining: number;
            maxPos: number;
            posCreated: number;
            posRemaining: number;
            lines: {
                rfqItemId: string;
                productId: string | null | undefined;
                rfqQty: number;
                orderedQty: number;
                remainingQty: number;
            }[];
        };
        shop: {
            id: string;
            address: string;
            brandingProfileId: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
            taxId: string | null;
            contactPerson: string;
            mobile: string;
            costingMethod: import(".prisma/client").$Enums.CostingMethod;
            functionalCurrency: string;
        };
        suppliers: ({
            supplier: {
                deletedAt: Date | null;
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                email: string | null;
                phone: string | null;
                companyId: string | null;
                taxId: string | null;
                contactPerson: string | null;
                supplierCode: string;
                supplierName: string;
                vatNumber: string | null;
                rating: number;
                categories: string[];
                street: string | null;
                city: string | null;
                state: string | null;
                postalCode: string | null;
                country: string | null;
                paymentTerms: string | null;
                bankName: string | null;
                accountNumber: string | null;
                routingNumber: string | null;
                iban: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            supplierId: string;
            rfqId: string;
        })[];
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: import("@prisma/client/runtime/library").Decimal;
                purchasePrice: import("@prisma/client/runtime/library").Decimal;
                sellingPrice: import("@prisma/client/runtime/library").Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            } | null;
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            description: string | null;
            uom: string;
            productId: string | null;
            rfqHeaderId: string;
            quantity: import("@prisma/client/runtime/library").Decimal;
            specifications: string | null;
        })[];
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.DocumentStatus;
        rfqNumber: string;
        rfqDate: Date;
        deadline: Date | null;
        title: string;
        notes: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
        templateVersion: number;
        postedAt: Date | null;
    }>;
    close(user: RequestUser, id: string): Promise<{
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.DocumentStatus;
        rfqNumber: string;
        rfqDate: Date;
        deadline: Date | null;
        title: string;
        notes: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
        templateVersion: number;
        postedAt: Date | null;
    }>;
    remove(user: RequestUser, id: string): Promise<{
        id: string;
        rfqNumber: string;
        deleted: boolean;
    }>;
}
