import { Prisma } from '@prisma/client';
import { PrismaService } from '../../prisma/prisma.service';
import type { RequestUser } from '../../common/types/request-user';
import { AuditService } from '../audit/audit.service';
import { DocumentNumberService } from '../stock/document-number.service';
import { CreateSupplierPaymentDto } from './dto/create-supplier-payment.dto';
import { ReverseSupplierPaymentDto } from './dto/reverse-supplier-payment.dto';
import { EmailNotificationsService } from '../email-notifications/email-notifications.service';
import { DocumentEmailService } from '../document-email/document-email.service';
export declare class SupplierPaymentsService {
    private readonly prisma;
    private readonly audit;
    private readonly numbers;
    private readonly emailNotifications;
    private readonly documentEmail;
    constructor(prisma: PrismaService, audit: AuditService, numbers: DocumentNumberService, emailNotifications: EmailNotificationsService, documentEmail: DocumentEmailService);
    list(user: RequestUser, query?: {
        cursor?: string;
        take?: number;
        supplier_bill_id?: string;
    }): Promise<{
        data: {
            shopId: string;
            id: string;
            method: string | null;
            amount: Prisma.Decimal;
            reference: string | null;
            paymentNumber: string;
            paymentDate: Date;
            supplierBillId: string;
            supplierBill: {
                id: string;
                totalValue: Prisma.Decimal;
                paidValue: Prisma.Decimal;
                billNumber: string;
            };
        }[];
        meta: {
            nextCursor: string | null;
            limit: number;
            hasMore: boolean;
        };
    }>;
    create(user: RequestUser, dto: CreateSupplierPaymentDto): Promise<{
        shop: {
            id: string;
            address: string;
            brandingProfileId: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
            taxId: string | null;
            contactPerson: string;
            mobile: string;
            costingMethod: import(".prisma/client").$Enums.CostingMethod;
            functionalCurrency: string;
        };
        supplierBill: {
            supplier: {
                deletedAt: Date | null;
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                email: string | null;
                phone: string | null;
                companyId: string | null;
                taxId: string | null;
                contactPerson: string | null;
                supplierCode: string;
                supplierName: string;
                vatNumber: string | null;
                rating: number;
                categories: string[];
                street: string | null;
                city: string | null;
                state: string | null;
                postalCode: string | null;
                country: string | null;
                paymentTerms: string | null;
                bankName: string | null;
                accountNumber: string | null;
                routingNumber: string | null;
                iban: string | null;
            };
        } & {
            shopId: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            status: import(".prisma/client").$Enums.SupplierBillStatus;
            supplierId: string;
            remarks: string | null;
            brandingMode: import(".prisma/client").$Enums.BrandingMode;
            brandingSnapshot: Prisma.JsonValue | null;
            templateVersion: number;
            totalValue: Prisma.Decimal;
            purchaseOrderId: string | null;
            paidValue: Prisma.Decimal;
            dueDate: Date | null;
            goodsReceiptId: string | null;
            billNumber: string;
            billDate: Date;
        };
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        method: string | null;
        remarks: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: Prisma.JsonValue | null;
        templateVersion: number;
        amount: Prisma.Decimal;
        reference: string | null;
        paymentNumber: string;
        paymentDate: Date;
        supplierBillId: string;
    }>;
    reverse(user: RequestUser, id: string, dto?: ReverseSupplierPaymentDto): Promise<{
        ok: boolean;
        reversedPaymentId: string;
        supplierBillId: string;
        paidValue: string;
        status: "ISSUED" | "PARTIALLY_PAID" | "PAID";
    }>;
    get(user: RequestUser, id: string): Promise<{
        shop: {
            id: string;
            address: string;
            brandingProfileId: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
            taxId: string | null;
            contactPerson: string;
            mobile: string;
            costingMethod: import(".prisma/client").$Enums.CostingMethod;
            functionalCurrency: string;
        };
        supplierBill: {
            supplier: {
                deletedAt: Date | null;
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                email: string | null;
                phone: string | null;
                companyId: string | null;
                taxId: string | null;
                contactPerson: string | null;
                supplierCode: string;
                supplierName: string;
                vatNumber: string | null;
                rating: number;
                categories: string[];
                street: string | null;
                city: string | null;
                state: string | null;
                postalCode: string | null;
                country: string | null;
                paymentTerms: string | null;
                bankName: string | null;
                accountNumber: string | null;
                routingNumber: string | null;
                iban: string | null;
            };
        } & {
            shopId: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            status: import(".prisma/client").$Enums.SupplierBillStatus;
            supplierId: string;
            remarks: string | null;
            brandingMode: import(".prisma/client").$Enums.BrandingMode;
            brandingSnapshot: Prisma.JsonValue | null;
            templateVersion: number;
            totalValue: Prisma.Decimal;
            purchaseOrderId: string | null;
            paidValue: Prisma.Decimal;
            dueDate: Date | null;
            goodsReceiptId: string | null;
            billNumber: string;
            billDate: Date;
        };
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        method: string | null;
        remarks: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: Prisma.JsonValue | null;
        templateVersion: number;
        amount: Prisma.Decimal;
        reference: string | null;
        paymentNumber: string;
        paymentDate: Date;
        supplierBillId: string;
    }>;
    sendToSupplier(user: RequestUser, id: string, options?: {
        resend?: boolean;
    }): Promise<import("../document-email/document-email.types").DocumentEmailSendResult>;
    private buildSupplierPaymentEmailContent;
    private autoSendSupplierPaymentEmail;
}
