-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "AlertType" ADD VALUE 'GOODS_RECEIPT_CREATED';
ALTER TYPE "AlertType" ADD VALUE 'GOODS_RECEIPT_APPROVED';
ALTER TYPE "AlertType" ADD VALUE 'GOODS_RECEIPT_REJECTED';
ALTER TYPE "AlertType" ADD VALUE 'PURCHASE_ORDER_CREATED';
ALTER TYPE "AlertType" ADD VALUE 'PURCHASE_ORDER_APPROVED';
ALTER TYPE "AlertType" ADD VALUE 'PURCHASE_ORDER_REJECTED';
ALTER TYPE "AlertType" ADD VALUE 'RFQ_CREATED';
ALTER TYPE "AlertType" ADD VALUE 'RFQ_RESPONSE_RECEIVED';
ALTER TYPE "AlertType" ADD VALUE 'RFQ_APPROVED';
ALTER TYPE "AlertType" ADD VALUE 'RFQ_REJECTED';
ALTER TYPE "AlertType" ADD VALUE 'SALES_QUOTATION_CREATED';
ALTER TYPE "AlertType" ADD VALUE 'SALES_QUOTATION_APPROVED';
ALTER TYPE "AlertType" ADD VALUE 'SALES_QUOTATION_REJECTED';
ALTER TYPE "AlertType" ADD VALUE 'WAREHOUSE_TRANSFER_COMPLETED';
ALTER TYPE "AlertType" ADD VALUE 'CRITICAL_STOCK';
ALTER TYPE "AlertType" ADD VALUE 'NEGATIVE_STOCK_PREVENTION';
ALTER TYPE "AlertType" ADD VALUE 'INVENTORY_ADJUSTMENT_COMPLETED';
ALTER TYPE "AlertType" ADD VALUE 'WAREHOUSE_CAPACITY_ALERT';
ALTER TYPE "AlertType" ADD VALUE 'NEW_DEVICE_LOGIN';
ALTER TYPE "AlertType" ADD VALUE 'PASSWORD_CHANGED';
ALTER TYPE "AlertType" ADD VALUE 'SESSION_REVOKED';
ALTER TYPE "AlertType" ADD VALUE 'BIOMETRIC_LOGIN_ENABLED';
ALTER TYPE "AlertType" ADD VALUE 'LOGIN_ATTEMPT_LOCKOUT';
ALTER TYPE "AlertType" ADD VALUE 'SYSTEM_MAINTENANCE';
ALTER TYPE "AlertType" ADD VALUE 'VERSION_UPDATE';
ALTER TYPE "AlertType" ADD VALUE 'COMPANY_ANNOUNCEMENT';
ALTER TYPE "AlertType" ADD VALUE 'FEATURE_RELEASE';
