import { DocumentStatus, Prisma } from '@prisma/client';
import { NotificationService } from '../notifications/services/notification.service';
import { PrismaService } from '../../prisma/prisma.service';
import type { RequestUser } from '../../common/types/request-user';
import { DocumentNumberService } from '../stock/document-number.service';
import { StockService } from '../stock/stock.service';
import { InventoryLotService } from '../stock/inventory-lot.service';
import { AuditService } from '../audit/audit.service';
type Line = {
    productId: string;
    quantity: number;
    uom: string;
};
export declare class GoodsIssuesService {
    private readonly prisma;
    private readonly stock;
    private readonly numbers;
    private readonly audit;
    private readonly inventoryLots;
    private readonly notifications;
    constructor(prisma: PrismaService, stock: StockService, numbers: DocumentNumberService, audit: AuditService, inventoryLots: InventoryLotService, notifications: NotificationService);
    private serializeListRow;
    private available;
    list(user: RequestUser, query: {
        shop_id?: string;
        date_from?: string;
        date_to?: string;
        status?: DocumentStatus;
        cursor?: string;
        take?: number;
    }): Promise<{
        data: {
            id: string;
            giNumber: string;
            giDate: string;
            shopId: string;
            issueReason: string;
            issueType: string;
            otherReason: string | null;
            remarks: string | null;
            status: import(".prisma/client").$Enums.DocumentStatus;
            postedAt: string | null;
            createdAt: string;
            updatedAt: string;
            itemCount: number;
            shop: {
                id: string;
                shopName: string;
                shopNumber: string;
            } | undefined;
        }[];
        meta: {
            nextCursor: string | null;
            limit: number;
            hasMore: boolean;
        };
    }>;
    create(user: RequestUser, params: {
        giDate: string;
        shopId: string;
        issueType?: string;
        issueReason?: string;
        otherReason?: string;
        remarks?: string;
        items: Line[];
    }): Promise<{
        shop: {
            id: string;
            address: string;
            brandingProfileId: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
            taxId: string | null;
            contactPerson: string;
            mobile: string;
            costingMethod: import(".prisma/client").$Enums.CostingMethod;
            functionalCurrency: string;
        };
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: Prisma.Decimal;
                purchasePrice: Prisma.Decimal;
                sellingPrice: Prisma.Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            uom: string;
            productId: string;
            quantity: Prisma.Decimal;
            giHeaderId: string;
            availableStockSnapshot: Prisma.Decimal;
        })[];
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.DocumentStatus;
        remarks: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: Prisma.JsonValue | null;
        templateVersion: number;
        postedAt: Date | null;
        giNumber: string;
        giDate: Date;
        issueReason: string;
        issueType: string;
        otherReason: string | null;
    }>;
    get(user: RequestUser, id: string): Promise<{
        shop: {
            id: string;
            address: string;
            brandingProfileId: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
            taxId: string | null;
            contactPerson: string;
            mobile: string;
            costingMethod: import(".prisma/client").$Enums.CostingMethod;
            functionalCurrency: string;
        };
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: Prisma.Decimal;
                purchasePrice: Prisma.Decimal;
                sellingPrice: Prisma.Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            uom: string;
            productId: string;
            quantity: Prisma.Decimal;
            giHeaderId: string;
            availableStockSnapshot: Prisma.Decimal;
        })[];
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.DocumentStatus;
        remarks: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: Prisma.JsonValue | null;
        templateVersion: number;
        postedAt: Date | null;
        giNumber: string;
        giDate: Date;
        issueReason: string;
        issueType: string;
        otherReason: string | null;
    }>;
    update(user: RequestUser, id: string, dto: Partial<{
        giDate: string;
        shopId: string;
        issueType: string;
        issueReason: string;
        otherReason?: string;
        remarks?: string;
        items: Line[];
    }>): Promise<{
        shop: {
            id: string;
            address: string;
            brandingProfileId: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
            taxId: string | null;
            contactPerson: string;
            mobile: string;
            costingMethod: import(".prisma/client").$Enums.CostingMethod;
            functionalCurrency: string;
        };
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: Prisma.Decimal;
                purchasePrice: Prisma.Decimal;
                sellingPrice: Prisma.Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            uom: string;
            productId: string;
            quantity: Prisma.Decimal;
            giHeaderId: string;
            availableStockSnapshot: Prisma.Decimal;
        })[];
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.DocumentStatus;
        remarks: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: Prisma.JsonValue | null;
        templateVersion: number;
        postedAt: Date | null;
        giNumber: string;
        giDate: Date;
        issueReason: string;
        issueType: string;
        otherReason: string | null;
    }>;
    post(user: RequestUser, id: string): Promise<{
        shop: {
            id: string;
            address: string;
            brandingProfileId: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
            taxId: string | null;
            contactPerson: string;
            mobile: string;
            costingMethod: import(".prisma/client").$Enums.CostingMethod;
            functionalCurrency: string;
        };
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: Prisma.Decimal;
                purchasePrice: Prisma.Decimal;
                sellingPrice: Prisma.Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            uom: string;
            productId: string;
            quantity: Prisma.Decimal;
            giHeaderId: string;
            availableStockSnapshot: Prisma.Decimal;
        })[];
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.DocumentStatus;
        remarks: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: Prisma.JsonValue | null;
        templateVersion: number;
        postedAt: Date | null;
        giNumber: string;
        giDate: Date;
        issueReason: string;
        issueType: string;
        otherReason: string | null;
    }>;
    print(user: RequestUser, id: string): Promise<string>;
    remove(user: RequestUser, id: string): Promise<{
        ok: boolean;
    }>;
}
export {};
