import { NotFoundException } from '@nestjs/common';
import type { PrismaService } from '../../../prisma/prisma.service';
import {
  documentPdfFilename,
  formatDocumentDate,
  formatDocumentMoney,
} from '../document-pdf.formatters';
import {
  buildDocumentLayoutHtml,
  type DocumentLayoutViewModel,
} from '../templates/document-layout.template';
import { loadShopCompanyContext, supplierPartyLines } from './shop-company';

const MIN_ROWS = 6;

function reasonLabel(code: string): string {
  const labels: Record<string, string> = {
    DAMAGED: 'Damaged',
    EXPIRED: 'Expired',
    WRONG_ITEM: 'Wrong item',
    QUALITY: 'Quality issue',
    OTHER: 'Other',
  };
  return labels[code] ?? code;
}

export async function loadGoodsReturnForPdf(prisma: PrismaService, id: string) {
  const ret = await prisma.supplierReturn.findUnique({
    where: { id },
    include: {
      supplier: true,
      shop: { select: { shopName: true } },
      goodsReceipt: { select: { grNumber: true } },
      items: {
        include: {
          product: { select: { productCode: true, description: true } },
          goodsReceiptItem: { include: { product: { select: { productCode: true, description: true } } } },
        },
      },
    },
  });
  if (!ret) throw new NotFoundException('Supplier return not found');
  return ret;
}

export async function buildGoodsReturnPdfViewModel(
  prisma: PrismaService,
  ret: Awaited<ReturnType<typeof loadGoodsReturnForPdf>>,
): Promise<DocumentLayoutViewModel> {
  const ctx = await loadShopCompanyContext(prisma, ret.shopId);

  const lines = ret.items.map((item) => ({
    code: item.product?.productCode ?? item.goodsReceiptItem?.product?.productCode ?? item.productId.slice(0, 8),
    description: item.product?.description ?? item.goodsReceiptItem?.product?.description ?? '—',
    qty: formatDocumentMoney(Number(item.quantity)),
    unitPrice: item.grnQuantity?.toString() ?? item.goodsReceiptItem?.quantity.toString() ?? '—',
    extra: reasonLabel(item.reasonCode ?? 'OTHER'),
    amount: formatDocumentMoney(Number(item.quantity)),
  }));

  const metaRows = [
    { label: 'Status', value: ret.status },
    { label: 'Goods Receipt', value: ret.goodsReceipt?.grNumber ?? '—' },
    { label: 'Plant', value: ret.shop?.shopName ?? ctx.shopName },
    ...(ret.supplierRef ? [{ label: 'Supplier Ref', value: ret.supplierRef }] : []),
  ];

  return {
    documentTitle: 'GOODS RETURN',
    documentNumber: ret.returnNumber,
    documentDate: formatDocumentDate(ret.returnDate),
    companyName: ctx.companyName,
    companyLines: ctx.companyLines,
    partyLabel: 'Supplier',
    partyName: ret.supplier?.supplierName ?? ret.supplierName,
    partyLines: ret.supplier ? supplierPartyLines(ret.supplier) : [ret.supplierName],
    metaRows,
    lines,
    showExtraColumn: true,
    extraColumnHeader: 'Reason',
    padRowCount: Math.max(0, MIN_ROWS - lines.length),
    totals: [{ label: 'Return Lines', value: String(ret.items.length), bold: true }],
    notes: ret.remarks ?? undefined,
    footerNote: 'This document was generated by SoftdigitIMS.',
  };
}

export function goodsReturnPdfFilename(returnNumber: string): string {
  return documentPdfFilename('goods-return', returnNumber);
}

export function renderGoodsReturnHtml(viewModel: DocumentLayoutViewModel): string {
  return buildDocumentLayoutHtml(viewModel);
}
