import { NotFoundException } from '@nestjs/common';
import type { PrismaService } from '../../../prisma/prisma.service';
import {
  documentPdfFilename,
  formatDocumentDate,
  formatDocumentMoney,
} from '../document-pdf.formatters';
import {
  buildDocumentLayoutHtml,
  type DocumentLayoutViewModel,
} from '../templates/document-layout.template';
import { loadShopCompanyContext } from './shop-company';

const MIN_ROWS = 8;

export async function loadGoodsIssueForPdf(prisma: PrismaService, id: string) {
  const gi = await prisma.goodsIssueHeader.findUnique({
    where: { id },
    include: {
      shop: { select: { shopName: true, address: true } },
      items: { include: { product: { select: { productCode: true, description: true } } } },
    },
  });
  if (!gi) throw new NotFoundException('Goods issue not found');
  return gi;
}

export async function buildGoodsIssuePdfViewModel(
  prisma: PrismaService,
  gi: Awaited<ReturnType<typeof loadGoodsIssueForPdf>>,
): Promise<DocumentLayoutViewModel> {
  const ctx = await loadShopCompanyContext(prisma, gi.shopId);

  const lines = gi.items.map((item) => ({
    code: item.product?.productCode ?? item.productId.slice(0, 8),
    description: item.product?.description ?? '—',
    qty: `${formatDocumentMoney(Number(item.quantity))} ${item.uom}`,
    unitPrice: '—',
    amount: formatDocumentMoney(Number(item.quantity)),
  }));

  const metaRows = [
    { label: 'Status', value: gi.status },
    { label: 'Plant', value: gi.shop?.shopName ?? ctx.shopName },
    { label: 'Issue Reason', value: gi.issueReason },
    ...(gi.postedAt ? [{ label: 'Posted At', value: formatDocumentDate(gi.postedAt) }] : []),
  ];

  return {
    documentTitle: 'GOODS ISSUE',
    documentNumber: gi.giNumber,
    documentDate: formatDocumentDate(gi.giDate),
    companyName: ctx.companyName,
    companyLines: ctx.companyLines,
    partyLabel: 'Issuing Plant',
    partyName: gi.shop?.shopName ?? ctx.shopName,
    partyLines: ctx.shopLines,
    metaRows,
    lines,
    showExtraColumn: false,
    extraColumnHeader: '',
    padRowCount: Math.max(0, MIN_ROWS - lines.length),
    totals: [{ label: 'Total Lines', value: String(gi.items.length), bold: true }],
    notes: gi.remarks ?? undefined,
    footerNote: 'This document was generated by Retail IMS.',
  };
}

export function goodsIssuePdfFilename(giNumber: string): string {
  return documentPdfFilename('goods-issue', giNumber);
}

export function renderGoodsIssueHtml(viewModel: DocumentLayoutViewModel): string {
  return buildDocumentLayoutHtml(viewModel);
}
