import { NotFoundException } from '@nestjs/common';
import type { PrismaService } from '../../../prisma/prisma.service';
import {
  documentPdfFilename,
  formatDocumentCurrency,
  formatDocumentDate,
  formatDocumentMoney,
} from '../document-pdf.formatters';
import {
  buildDocumentLayoutHtml,
  type DocumentLayoutViewModel,
} from '../templates/document-layout.template';
import { loadShopCompanyContext, supplierPartyLines } from './shop-company';

const MIN_ROWS = 8;

export async function loadGoodsReceiptForPdf(prisma: PrismaService, id: string) {
  const gr = await prisma.goodsReceiptHeader.findUnique({
    where: { id },
    include: {
      shop: { select: { shopName: true } },
      purchaseOrder: { select: { poNumber: true } },
      items: { include: { product: { select: { productCode: true, description: true } } } },
    },
  });
  if (!gr) throw new NotFoundException('Goods receipt not found');
  return gr;
}

function formatReceiptType(value?: string | null): string {
  if (!value) return 'Full Receipt';
  return value === 'PARTIAL' ? 'Partial Receipt' : 'Full Receipt';
}

function formatInwardShift(value?: string | null): string {
  if (!value) return '—';
  return value === 'NIGHT_SHIFT' ? 'Night Shift' : 'Day Shift';
}

export async function buildGoodsReceiptPdfViewModel(
  prisma: PrismaService,
  gr: Awaited<ReturnType<typeof loadGoodsReceiptForPdf>>,
): Promise<DocumentLayoutViewModel> {
  const ctx = await loadShopCompanyContext(prisma, gr.shopId);

  const supplierRow = gr.purchaseOrderId
    ? await prisma.supplier.findFirst({
        where: {
          companyId: ctx.companyId,
          supplierName: { equals: gr.supplierName.trim(), mode: 'insensitive' },
        },
      })
    : await prisma.supplier.findFirst({
        where: {
          companyId: ctx.companyId,
          supplierName: { equals: gr.supplierName.trim(), mode: 'insensitive' },
        },
      });

  const lines = gr.items.map((item) => ({
    code: item.product?.productCode ?? item.productId.slice(0, 8),
    description: item.product?.description ?? '—',
    qty: `${formatDocumentMoney(Number(item.quantity))} ${item.uom}`,
    unitPrice: formatDocumentCurrency(Number(item.purchaseRate)),
    amount: formatDocumentCurrency(Number(item.lineValue)),
  }));

  const subtotal = gr.items.reduce((sum, item) => sum + Number(item.lineValue), 0);
  const grandTotal = gr.totalValue != null ? Number(gr.totalValue) : subtotal;

  const metaRows = [
    { label: 'Status', value: gr.status },
    { label: 'Plant', value: gr.shop?.shopName ?? ctx.shopName },
    { label: 'Receipt Type', value: formatReceiptType(gr.receiptType) },
    ...(gr.receiptSource === 'OUTSIDE'
      ? [
          { label: 'Purchase Order', value: 'Others' },
          ...(gr.inwardShift ? [{ label: 'Inward Shift', value: formatInwardShift(gr.inwardShift) }] : []),
        ]
      : gr.purchaseOrder
      ? [{ label: 'Purchase Order', value: gr.purchaseOrder.poNumber }]
      : []),
    ...(gr.supplierRef ? [{ label: 'Supplier Ref', value: gr.supplierRef }] : []),
  ];

  return {
    documentTitle: 'GOODS RECEIPT',
    documentNumber: gr.grNumber,
    documentDate: formatDocumentDate(gr.grDate),
    companyName: ctx.companyName,
    companyLines: ctx.companyLines,
    partyLabel: 'Supplier',
    partyName: supplierRow?.supplierName ?? gr.supplierName,
    partyLines: supplierRow ? supplierPartyLines(supplierRow) : [gr.supplierName],
    metaRows,
    lines,
    showExtraColumn: false,
    extraColumnHeader: '',
    padRowCount: Math.max(0, MIN_ROWS - lines.length),
    totals: [
      { label: 'Subtotal', value: formatDocumentCurrency(subtotal) },
      { label: 'Grand Total', value: formatDocumentCurrency(grandTotal), bold: true },
    ],
    notes: gr.remarks ?? undefined,
    footerNote: 'This document was generated by Retail IMS.',
  };
}

export function goodsReceiptPdfFilename(grNumber: string): string {
  return documentPdfFilename('goods-receipt', grNumber);
}

export function renderGoodsReceiptHtml(viewModel: DocumentLayoutViewModel): string {
  return buildDocumentLayoutHtml(viewModel);
}
