import { NotFoundException } from '@nestjs/common';
import type { PrismaService } from '../../../prisma/prisma.service';
import {
  documentPdfFilename,
  formatDocumentCurrency,
  formatDocumentDate,
  formatDocumentMoney,
} from '../document-pdf.formatters';
import {
  buildDocumentLayoutHtml,
  type DocumentLayoutViewModel,
} from '../templates/document-layout.template';
import { customerPartyLines, loadShopCompanyContext } from './shop-company';

const MIN_ROWS = 8;

export async function loadInvoiceForPdf(prisma: PrismaService, id: string) {
  const invoice = await prisma.invoiceHeader.findUnique({
    where: { id },
    include: {
      customer: true,
      salesOrder: {
        include: {
          items: { include: { product: { select: { productCode: true, description: true } } } },
        },
      },
    },
  });
  if (!invoice) throw new NotFoundException('Invoice not found');
  return invoice;
}

export async function buildInvoicePdfViewModel(
  prisma: PrismaService,
  invoice: Awaited<ReturnType<typeof loadInvoiceForPdf>>,
): Promise<DocumentLayoutViewModel> {
  const ctx = await loadShopCompanyContext(prisma, invoice.shopId);
  const currency = invoice.currency || 'INR';

  const soItems = invoice.salesOrder?.items ?? [];
  const lines =
    soItems.length > 0
      ? soItems.map((item) => ({
          code: item.product?.productCode ?? item.productId.slice(0, 8),
          description: item.product?.description ?? '—',
          qty: formatDocumentMoney(Number(item.quantity)),
          unitPrice: formatDocumentCurrency(Number(item.unitPrice), currency),
          extra: formatDocumentCurrency(Number(item.taxAmount), currency),
          amount: formatDocumentCurrency(Number(item.lineValue), currency),
        }))
      : [
          {
            code: '—',
            description: 'Invoice total (no line detail)',
            qty: '1',
            unitPrice: formatDocumentCurrency(Number(invoice.totalValue), currency),
            extra: formatDocumentCurrency(Number(invoice.taxAmount), currency),
            amount: formatDocumentCurrency(Number(invoice.totalValue), currency),
          },
        ];

  const subtotal = soItems.length
    ? soItems.reduce((sum, item) => sum + Number(item.lineValue) - Number(item.taxAmount), 0)
    : Number(invoice.totalValue) - Number(invoice.taxAmount);
  const discount = Number(invoice.discountAmount);
  const tax = Number(invoice.taxAmount);
  const grandTotal = Number(invoice.totalValue);
  const paid = Number(invoice.paidValue);
  const balance = Math.max(grandTotal - paid, 0);

  const metaRows = [
    { label: 'Status', value: invoice.status },
    ...(invoice.salesOrder ? [{ label: 'Sales Order', value: invoice.salesOrder.soNumber }] : []),
    ...(invoice.dueDate ? [{ label: 'Due Date', value: formatDocumentDate(invoice.dueDate) }] : []),
    { label: 'Plant', value: ctx.shopName },
  ];

  return {
    documentTitle: 'TAX INVOICE',
    documentNumber: invoice.invoiceNumber,
    documentDate: formatDocumentDate(invoice.invoiceDate),
    companyName: ctx.companyName,
    companyLines: ctx.companyLines,
    partyLabel: 'Bill To',
    partyName: invoice.customer.customerName,
    partyLines: customerPartyLines(invoice.customer),
    metaRows,
    lines,
    showExtraColumn: true,
    extraColumnHeader: 'Tax',
    padRowCount: Math.max(0, MIN_ROWS - lines.length),
    totals: [
      { label: 'Subtotal', value: formatDocumentCurrency(subtotal, currency) },
      ...(discount > 0
        ? [{ label: 'Discount', value: formatDocumentCurrency(discount, currency) }]
        : []),
      { label: 'Tax', value: formatDocumentCurrency(tax, currency) },
      { label: 'Grand Total', value: formatDocumentCurrency(grandTotal, currency), bold: true },
      ...(paid > 0 ? [{ label: 'Paid', value: formatDocumentCurrency(paid, currency) }] : []),
      ...(balance > 0 && paid > 0
        ? [{ label: 'Balance Due', value: formatDocumentCurrency(balance, currency), bold: true }]
        : []),
    ],
    notes: invoice.remarks ?? undefined,
    footerNote: 'This document was generated by Retail IMS.',
  };
}

export function invoicePdfFilename(invoiceNumber: string): string {
  return documentPdfFilename('invoice', invoiceNumber);
}

export function renderInvoiceHtml(viewModel: DocumentLayoutViewModel): string {
  return buildDocumentLayoutHtml(viewModel);
}
