import { NotFoundException } from '@nestjs/common';
import type { PrismaService } from '../../../prisma/prisma.service';
import {
  documentPdfFilename,
  formatDocumentCurrency,
  formatDocumentDate,
} from '../document-pdf.formatters';
import {
  buildDocumentLayoutHtml,
  type DocumentLayoutViewModel,
} from '../templates/document-layout.template';
import { customerPartyLines, loadShopCompanyContext } from './shop-company';

export async function loadPaymentReceiptForPdf(prisma: PrismaService, id: string) {
  const payment = await prisma.paymentReceipt.findUnique({
    where: { id },
    include: {
      invoice: { include: { customer: true } },
    },
  });
  if (!payment) throw new NotFoundException('Payment receipt not found');
  return payment;
}

export async function buildPaymentReceiptPdfViewModel(
  prisma: PrismaService,
  payment: Awaited<ReturnType<typeof loadPaymentReceiptForPdf>>,
): Promise<DocumentLayoutViewModel> {
  const ctx = await loadShopCompanyContext(prisma, payment.shopId);
  const invoice = payment.invoice;
  const customer = invoice.customer;

  const invoiceTotal = Number(invoice.totalValue);
  const paidAfter = Number(invoice.paidValue);
  const amount = Number(payment.amount);
  const balance = Math.max(invoiceTotal - paidAfter, 0);
  const paymentType = balance <= 0 ? 'Full' : 'Partial';

  const metaRows = [
    { label: 'Invoice', value: invoice.invoiceNumber },
    { label: 'Receipt Date', value: formatDocumentDate(payment.receiptDate) },
    { label: 'Payment Type', value: paymentType },
    ...(payment.method ? [{ label: 'Method', value: payment.method }] : []),
    ...(payment.reference ? [{ label: 'Reference', value: payment.reference }] : []),
    { label: 'Invoice Total', value: formatDocumentCurrency(invoiceTotal) },
    { label: 'Amount Paid', value: formatDocumentCurrency(amount) },
    { label: 'Balance Due', value: formatDocumentCurrency(balance) },
  ];

  return {
    documentTitle: 'PAYMENT RECEIPT',
    documentNumber: payment.receiptNumber,
    documentDate: formatDocumentDate(payment.receiptDate),
    companyName: ctx.companyName,
    companyLines: ctx.companyLines,
    partyLabel: 'Received From',
    partyName: customer.customerName,
    partyLines: customerPartyLines(customer),
    metaRows,
    lines: [
      {
        code: invoice.invoiceNumber,
        description: `Payment against invoice ${invoice.invoiceNumber}`,
        qty: '1',
        unitPrice: formatDocumentCurrency(amount),
        amount: formatDocumentCurrency(amount),
      },
    ],
    showExtraColumn: false,
    extraColumnHeader: '',
    padRowCount: 7,
    totals: [
      { label: 'Amount Received', value: formatDocumentCurrency(amount), bold: true },
      { label: 'Balance on Invoice', value: formatDocumentCurrency(balance), bold: true },
    ],
    notes: payment.remarks ?? undefined,
    footerNote: 'This document was generated by SoftdigitIMS.',
  };
}

export function paymentReceiptPdfFilename(receiptNumber: string): string {
  return documentPdfFilename('payment', receiptNumber);
}

export function renderPaymentReceiptHtml(viewModel: DocumentLayoutViewModel): string {
  return buildDocumentLayoutHtml(viewModel);
}
