import { NotFoundException } from '@nestjs/common';
import type { PrismaService } from '../../../prisma/prisma.service';
import {
  documentPdfFilename,
  formatDocumentCurrency,
  formatDocumentDate,
  formatDocumentMoney,
} from '../document-pdf.formatters';
import {
  buildDocumentLayoutHtml,
  type DocumentLayoutViewModel,
} from '../templates/document-layout.template';
import { customerPartyLines, loadShopCompanyContext } from './shop-company';

const MIN_ROWS = 8;

export async function loadSalesOrderForPdf(prisma: PrismaService, id: string) {
  const order = await prisma.salesOrderHeader.findUnique({
    where: { id },
    include: {
      customer: true,
      shop: { select: { shopName: true } },
      salesQuotation: { select: { quoteNumber: true } },
      items: { include: { product: { select: { productCode: true, description: true } } } },
    },
  });
  if (!order) throw new NotFoundException('Sales order not found');
  return order;
}

export async function buildSalesOrderPdfViewModel(
  prisma: PrismaService,
  order: Awaited<ReturnType<typeof loadSalesOrderForPdf>>,
): Promise<DocumentLayoutViewModel> {
  const ctx = await loadShopCompanyContext(prisma, order.shopId);
  const currency = order.currency || 'INR';

  const lines = order.items.map((item) => ({
    code: item.product?.productCode ?? item.productId.slice(0, 8),
    description: item.product?.description ?? '—',
    qty: formatDocumentMoney(Number(item.quantity)),
    unitPrice: formatDocumentCurrency(Number(item.unitPrice), currency),
    extra: formatDocumentCurrency(Number(item.taxAmount), currency),
    amount: formatDocumentCurrency(Number(item.lineValue), currency),
  }));

  const subtotal = order.items.reduce(
    (sum, item) => sum + Number(item.lineValue) - Number(item.taxAmount),
    0,
  );
  const discount = Number(order.discountAmount);
  const tax = Number(order.taxAmount);
  const storedTotal = order.totalValue != null ? Number(order.totalValue) : null;
  const computedTotal = subtotal - discount + tax;
  const grandTotal = storedTotal != null && storedTotal > 0 ? storedTotal : computedTotal;

  const metaRows = [
    { label: 'Status', value: order.status },
    ...(order.expectedDate
      ? [{ label: 'Expected Date', value: formatDocumentDate(order.expectedDate) }]
      : []),
    { label: 'Plant', value: order.shop?.shopName ?? ctx.shopName },
    ...(order.salesQuotation
      ? [{ label: 'Quotation', value: order.salesQuotation.quoteNumber }]
      : []),
  ];

  return {
    documentTitle: 'SALES ORDER',
    documentNumber: order.soNumber,
    documentDate: formatDocumentDate(order.orderDate),
    companyName: ctx.companyName,
    companyLines: ctx.companyLines,
    partyLabel: 'Customer',
    partyName: order.customer?.customerName ?? '—',
    partyLines: order.customer ? customerPartyLines(order.customer) : [],
    metaRows,
    lines,
    showExtraColumn: true,
    extraColumnHeader: 'Tax',
    padRowCount: Math.max(0, MIN_ROWS - lines.length),
    totals: [
      { label: 'Subtotal', value: formatDocumentCurrency(subtotal, currency) },
      ...(discount > 0
        ? [{ label: 'Discount', value: formatDocumentCurrency(discount, currency) }]
        : []),
      { label: 'Tax', value: formatDocumentCurrency(tax, currency) },
      { label: 'Grand Total', value: formatDocumentCurrency(grandTotal, currency), bold: true },
    ],
    notes: order.remarks ?? undefined,
    footerNote: 'This document was generated by Retail IMS.',
  };
}

export function salesOrderPdfFilename(soNumber: string): string {
  return documentPdfFilename('sales-order', soNumber);
}

export function renderSalesOrderHtml(viewModel: DocumentLayoutViewModel): string {
  return buildDocumentLayoutHtml(viewModel);
}
