import { NotFoundException } from '@nestjs/common';
import type { PrismaService } from '../../../prisma/prisma.service';
import {
  documentPdfFilename,
  formatDocumentCurrency,
  formatDocumentDate,
  formatDocumentMoney,
} from '../document-pdf.formatters';
import {
  buildDocumentLayoutHtml,
  type DocumentLayoutViewModel,
} from '../templates/document-layout.template';
import { customerPartyLines, loadShopCompanyContext } from './shop-company';

const MIN_ROWS = 8;

export async function loadSalesQuotationForPdf(prisma: PrismaService, id: string) {
  const quote = await prisma.salesQuotationHeader.findUnique({
    where: { id },
    include: {
      customer: true,
      shop: { select: { shopName: true } },
      items: { include: { product: { select: { productCode: true, description: true } } } },
    },
  });
  if (!quote) throw new NotFoundException('Sales quotation not found');
  return quote;
}

export async function buildSalesQuotationPdfViewModel(
  prisma: PrismaService,
  quote: Awaited<ReturnType<typeof loadSalesQuotationForPdf>>,
): Promise<DocumentLayoutViewModel> {
  const ctx = await loadShopCompanyContext(prisma, quote.shopId);

  const lines = quote.items.map((item) => ({
    code: item.product?.productCode ?? item.productId.slice(0, 8),
    description: item.product?.description ?? '—',
    qty: `${formatDocumentMoney(Number(item.quantity))} ${item.uom}`,
    unitPrice: formatDocumentCurrency(Number(item.unitPrice)),
    amount: formatDocumentCurrency(Number(item.lineValue)),
  }));

  const subtotal = quote.items.reduce((sum, item) => sum + Number(item.lineValue), 0);
  const grandTotal = quote.totalValue != null ? Number(quote.totalValue) : subtotal;

  const metaRows = [
    { label: 'Status', value: quote.status },
    { label: 'Plant', value: quote.shop?.shopName ?? ctx.shopName },
    ...(quote.validUntil ? [{ label: 'Valid Until', value: formatDocumentDate(quote.validUntil) }] : []),
  ];

  return {
    documentTitle: 'SALES QUOTATION',
    documentNumber: quote.quoteNumber,
    documentDate: formatDocumentDate(quote.quoteDate),
    companyName: ctx.companyName,
    companyLines: ctx.companyLines,
    partyLabel: 'Customer',
    partyName: quote.customer.customerName,
    partyLines: customerPartyLines(quote.customer),
    metaRows,
    lines,
    showExtraColumn: false,
    extraColumnHeader: '',
    padRowCount: Math.max(0, MIN_ROWS - lines.length),
    totals: [
      { label: 'Subtotal', value: formatDocumentCurrency(subtotal) },
      { label: 'Grand Total', value: formatDocumentCurrency(grandTotal), bold: true },
    ],
    notes: quote.remarks ?? undefined,
    footerNote: 'This document was generated by Retail IMS.',
  };
}

export function salesQuotationPdfFilename(quoteNumber: string): string {
  return documentPdfFilename('sales-quotation', quoteNumber);
}

export function renderSalesQuotationHtml(viewModel: DocumentLayoutViewModel): string {
  return buildDocumentLayoutHtml(viewModel);
}
