import { NotFoundException } from '@nestjs/common';
import type { PrismaService } from '../../../prisma/prisma.service';
import {
  documentPdfFilename,
  formatDocumentCurrency,
  formatDocumentDate,
} from '../document-pdf.formatters';
import {
  buildDocumentLayoutHtml,
  type DocumentLayoutViewModel,
} from '../templates/document-layout.template';
import { loadShopCompanyContext, supplierPartyLines } from './shop-company';

export async function loadSupplierPaymentForPdf(prisma: PrismaService, id: string) {
  const payment = await prisma.supplierPayment.findUnique({
    where: { id },
    include: {
      supplierBill: {
        include: { supplier: true },
      },
    },
  });
  if (!payment) throw new NotFoundException('Supplier payment not found');
  return payment;
}

export async function buildSupplierPaymentPdfViewModel(
  prisma: PrismaService,
  payment: Awaited<ReturnType<typeof loadSupplierPaymentForPdf>>,
): Promise<DocumentLayoutViewModel> {
  const ctx = await loadShopCompanyContext(prisma, payment.shopId);
  const bill = payment.supplierBill;
  const supplier = bill.supplier;

  const billTotal = Number(bill.totalValue);
  const paidAfter = Number(bill.paidValue);
  const amount = Number(payment.amount);
  const balance = Math.max(billTotal - paidAfter, 0);
  const paymentType = balance <= 0 ? 'Full' : 'Partial';

  const metaRows = [
    { label: 'Supplier Bill', value: bill.billNumber },
    { label: 'Payment Date', value: formatDocumentDate(payment.paymentDate) },
    { label: 'Payment Type', value: paymentType },
    ...(payment.method ? [{ label: 'Method', value: payment.method }] : []),
    ...(payment.reference ? [{ label: 'Reference', value: payment.reference }] : []),
    { label: 'Bill Total', value: formatDocumentCurrency(billTotal) },
    { label: 'Amount Paid', value: formatDocumentCurrency(amount) },
    { label: 'Balance Due', value: formatDocumentCurrency(balance) },
  ];

  return {
    documentTitle: 'SUPPLIER PAYMENT',
    documentNumber: payment.paymentNumber,
    documentDate: formatDocumentDate(payment.paymentDate),
    companyName: ctx.companyName,
    companyLines: ctx.companyLines,
    partyLabel: 'Supplier',
    partyName: supplier.supplierName,
    partyLines: supplierPartyLines(supplier),
    metaRows,
    lines: [
      {
        code: bill.billNumber,
        description: `Payment against supplier bill ${bill.billNumber}`,
        qty: '1',
        unitPrice: formatDocumentCurrency(amount),
        amount: formatDocumentCurrency(amount),
      },
    ],
    showExtraColumn: false,
    extraColumnHeader: '',
    padRowCount: 7,
    totals: [
      { label: 'Amount Paid', value: formatDocumentCurrency(amount), bold: true },
      { label: 'Balance on Bill', value: formatDocumentCurrency(balance), bold: true },
    ],
    notes: payment.remarks ?? undefined,
    footerNote: 'This document was generated by SoftdigitIMS.',
  };
}

export function supplierPaymentPdfFilename(paymentNumber: string): string {
  return documentPdfFilename('supplier-payment', paymentNumber);
}

export function renderSupplierPaymentHtml(viewModel: DocumentLayoutViewModel): string {
  return buildDocumentLayoutHtml(viewModel);
}
