import { NotFoundException } from '@nestjs/common';
import type { PrismaService } from '../../../prisma/prisma.service';
import {
  documentPdfFilename,
  formatDocumentCurrency,
  formatDocumentDate,
  formatDocumentMoney,
} from '../document-pdf.formatters';
import {
  buildDocumentLayoutHtml,
  type DocumentLayoutViewModel,
} from '../templates/document-layout.template';
import { loadShopCompanyContext, supplierPartyLines } from './shop-company';

const MIN_ROWS = 8;

export async function loadSupplierBillForPdf(prisma: PrismaService, id: string) {
  const bill = await prisma.supplierBillHeader.findUnique({
    where: { id },
    include: {
      supplier: true,
      purchaseOrder: { select: { poNumber: true } },
      goodsReceipt: { select: { grNumber: true } },
      items: { include: { product: { select: { productCode: true, description: true } } } },
    },
  });
  if (!bill) throw new NotFoundException('Supplier bill not found');
  return bill;
}

export async function buildSupplierBillPdfViewModel(
  prisma: PrismaService,
  bill: Awaited<ReturnType<typeof loadSupplierBillForPdf>>,
): Promise<DocumentLayoutViewModel> {
  const ctx = await loadShopCompanyContext(prisma, bill.shopId);

  const lines = bill.items.map((item) => ({
    code: item.product?.productCode ?? item.productId.slice(0, 8),
    description: item.product?.description ?? '—',
    qty: `${formatDocumentMoney(Number(item.quantity))} ${item.uom}`,
    unitPrice: formatDocumentCurrency(Number(item.unitCost)),
    amount: formatDocumentCurrency(Number(item.lineValue)),
  }));

  const subtotal = bill.items.reduce((sum, item) => sum + Number(item.lineValue), 0);
  const grandTotal = Number(bill.totalValue);
  const paid = Number(bill.paidValue);
  const balance = Math.max(grandTotal - paid, 0);

  const metaRows = [
    { label: 'Status', value: bill.status },
    ...(bill.purchaseOrder ? [{ label: 'Purchase Order', value: bill.purchaseOrder.poNumber }] : []),
    ...(bill.goodsReceipt ? [{ label: 'Goods Receipt', value: bill.goodsReceipt.grNumber }] : []),
    ...(bill.dueDate ? [{ label: 'Due Date', value: formatDocumentDate(bill.dueDate) }] : []),
    { label: 'Plant', value: ctx.shopName },
  ];

  return {
    documentTitle: 'SUPPLIER BILL',
    documentNumber: bill.billNumber,
    documentDate: formatDocumentDate(bill.billDate),
    companyName: ctx.companyName,
    companyLines: ctx.companyLines,
    partyLabel: 'Supplier',
    partyName: bill.supplier.supplierName,
    partyLines: supplierPartyLines(bill.supplier),
    metaRows,
    lines,
    showExtraColumn: false,
    extraColumnHeader: '',
    padRowCount: Math.max(0, MIN_ROWS - lines.length),
    totals: [
      { label: 'Subtotal', value: formatDocumentCurrency(subtotal) },
      { label: 'Grand Total', value: formatDocumentCurrency(grandTotal), bold: true },
      ...(paid > 0 ? [{ label: 'Paid', value: formatDocumentCurrency(paid) }] : []),
      ...(balance > 0 && paid > 0
        ? [{ label: 'Balance Due', value: formatDocumentCurrency(balance), bold: true }]
        : []),
    ],
    notes: bill.remarks ?? undefined,
    footerNote: 'This document was generated by Retail IMS.',
  };
}

export function supplierBillPdfFilename(billNumber: string): string {
  return documentPdfFilename('supplier-bill', billNumber);
}

export function renderSupplierBillHtml(viewModel: DocumentLayoutViewModel): string {
  return buildDocumentLayoutHtml(viewModel);
}
