import type { RequestUser } from '../../common/types/request-user';
import { CreateSalesOrderDto } from './dto/create-sales-order.dto';
import { ListSalesOrdersDto } from './dto/list-sales-orders.dto';
import { UpdateSalesOrderDto } from './dto/update-sales-order.dto';
import { SalesOrdersService } from './sales-orders.service';
export declare class SalesOrdersController {
    private readonly salesOrders;
    constructor(salesOrders: SalesOrdersService);
    list(user: RequestUser, query: ListSalesOrdersDto): Promise<{
        data: {
            shopId: string;
            shop: {
                id: string;
                shopNumber: string;
                shopName: string;
            };
            customer: {
                id: string;
                customerCode: string;
                customerName: string;
            };
            id: string;
            status: import(".prisma/client").$Enums.SalesOrderStatus;
            remarks: string | null;
            totalValue: import("@prisma/client/runtime/library").Decimal | null;
            customerId: string;
            soNumber: string;
            orderDate: Date;
            expectedDate: Date | null;
        }[];
        meta: {
            nextCursor: string | null;
            limit: number;
            hasMore: boolean;
        };
    }>;
    create(user: RequestUser, dto: CreateSalesOrderDto, idempotencyKey?: string): Promise<{
        customer: {
            shopId: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string | null;
            phone: string | null;
            taxId: string | null;
            street: string | null;
            city: string | null;
            state: string | null;
            postalCode: string | null;
            country: string | null;
            customerCode: string;
            customerName: string;
            pan: string | null;
        };
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: import("@prisma/client/runtime/library").Decimal;
                purchasePrice: import("@prisma/client/runtime/library").Decimal;
                sellingPrice: import("@prisma/client/runtime/library").Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            uom: string;
            productId: string;
            quantity: import("@prisma/client/runtime/library").Decimal;
            unitPrice: import("@prisma/client/runtime/library").Decimal;
            lineValue: import("@prisma/client/runtime/library").Decimal;
            discountAmount: import("@prisma/client/runtime/library").Decimal;
            taxAmount: import("@prisma/client/runtime/library").Decimal;
            taxRate: import("@prisma/client/runtime/library").Decimal;
            soHeaderId: string;
            shippedQty: import("@prisma/client/runtime/library").Decimal;
            cgstRate: import("@prisma/client/runtime/library").Decimal;
            sgstRate: import("@prisma/client/runtime/library").Decimal;
            igstRate: import("@prisma/client/runtime/library").Decimal;
        })[];
    } & {
        shopId: string;
        currency: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.SalesOrderStatus;
        remarks: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
        templateVersion: number;
        totalValue: import("@prisma/client/runtime/library").Decimal | null;
        fxRateUsed: import("@prisma/client/runtime/library").Decimal | null;
        discountAmount: import("@prisma/client/runtime/library").Decimal;
        taxAmount: import("@prisma/client/runtime/library").Decimal;
        customerId: string;
        soNumber: string;
        orderDate: Date;
        expectedDate: Date | null;
        fulfillmentStatus: import(".prisma/client").$Enums.FulfillmentStatus;
        gstSupplyType: import(".prisma/client").$Enums.GstSupplyType;
        subtotalBeforeTax: import("@prisma/client/runtime/library").Decimal;
        totalCgst: import("@prisma/client/runtime/library").Decimal;
        totalSgst: import("@prisma/client/runtime/library").Decimal;
        totalIgst: import("@prisma/client/runtime/library").Decimal;
    }>;
    get(user: RequestUser, id: string): Promise<{
        shop: {
            id: string;
            shopNumber: string;
            shopName: string;
        };
        customer: {
            shopId: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string | null;
            phone: string | null;
            taxId: string | null;
            street: string | null;
            city: string | null;
            state: string | null;
            postalCode: string | null;
            country: string | null;
            customerCode: string;
            customerName: string;
            pan: string | null;
        };
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: import("@prisma/client/runtime/library").Decimal;
                purchasePrice: import("@prisma/client/runtime/library").Decimal;
                sellingPrice: import("@prisma/client/runtime/library").Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            uom: string;
            productId: string;
            quantity: import("@prisma/client/runtime/library").Decimal;
            unitPrice: import("@prisma/client/runtime/library").Decimal;
            lineValue: import("@prisma/client/runtime/library").Decimal;
            discountAmount: import("@prisma/client/runtime/library").Decimal;
            taxAmount: import("@prisma/client/runtime/library").Decimal;
            taxRate: import("@prisma/client/runtime/library").Decimal;
            soHeaderId: string;
            shippedQty: import("@prisma/client/runtime/library").Decimal;
            cgstRate: import("@prisma/client/runtime/library").Decimal;
            sgstRate: import("@prisma/client/runtime/library").Decimal;
            igstRate: import("@prisma/client/runtime/library").Decimal;
        })[];
        salesQuotation: {
            id: string;
            quoteNumber: string;
        } | null;
    } & {
        shopId: string;
        currency: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.SalesOrderStatus;
        remarks: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
        templateVersion: number;
        totalValue: import("@prisma/client/runtime/library").Decimal | null;
        fxRateUsed: import("@prisma/client/runtime/library").Decimal | null;
        discountAmount: import("@prisma/client/runtime/library").Decimal;
        taxAmount: import("@prisma/client/runtime/library").Decimal;
        customerId: string;
        soNumber: string;
        orderDate: Date;
        expectedDate: Date | null;
        fulfillmentStatus: import(".prisma/client").$Enums.FulfillmentStatus;
        gstSupplyType: import(".prisma/client").$Enums.GstSupplyType;
        subtotalBeforeTax: import("@prisma/client/runtime/library").Decimal;
        totalCgst: import("@prisma/client/runtime/library").Decimal;
        totalSgst: import("@prisma/client/runtime/library").Decimal;
        totalIgst: import("@prisma/client/runtime/library").Decimal;
    }>;
    update(user: RequestUser, id: string, dto: UpdateSalesOrderDto): Promise<{
        shop: {
            id: string;
            shopNumber: string;
            shopName: string;
        };
        customer: {
            shopId: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string | null;
            phone: string | null;
            taxId: string | null;
            street: string | null;
            city: string | null;
            state: string | null;
            postalCode: string | null;
            country: string | null;
            customerCode: string;
            customerName: string;
            pan: string | null;
        };
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: import("@prisma/client/runtime/library").Decimal;
                purchasePrice: import("@prisma/client/runtime/library").Decimal;
                sellingPrice: import("@prisma/client/runtime/library").Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            uom: string;
            productId: string;
            quantity: import("@prisma/client/runtime/library").Decimal;
            unitPrice: import("@prisma/client/runtime/library").Decimal;
            lineValue: import("@prisma/client/runtime/library").Decimal;
            discountAmount: import("@prisma/client/runtime/library").Decimal;
            taxAmount: import("@prisma/client/runtime/library").Decimal;
            taxRate: import("@prisma/client/runtime/library").Decimal;
            soHeaderId: string;
            shippedQty: import("@prisma/client/runtime/library").Decimal;
            cgstRate: import("@prisma/client/runtime/library").Decimal;
            sgstRate: import("@prisma/client/runtime/library").Decimal;
            igstRate: import("@prisma/client/runtime/library").Decimal;
        })[];
        salesQuotation: {
            id: string;
            quoteNumber: string;
        } | null;
    } & {
        shopId: string;
        currency: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.SalesOrderStatus;
        remarks: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
        templateVersion: number;
        totalValue: import("@prisma/client/runtime/library").Decimal | null;
        fxRateUsed: import("@prisma/client/runtime/library").Decimal | null;
        discountAmount: import("@prisma/client/runtime/library").Decimal;
        taxAmount: import("@prisma/client/runtime/library").Decimal;
        customerId: string;
        soNumber: string;
        orderDate: Date;
        expectedDate: Date | null;
        fulfillmentStatus: import(".prisma/client").$Enums.FulfillmentStatus;
        gstSupplyType: import(".prisma/client").$Enums.GstSupplyType;
        subtotalBeforeTax: import("@prisma/client/runtime/library").Decimal;
        totalCgst: import("@prisma/client/runtime/library").Decimal;
        totalSgst: import("@prisma/client/runtime/library").Decimal;
        totalIgst: import("@prisma/client/runtime/library").Decimal;
    }>;
    remove(user: RequestUser, id: string): Promise<{
        deleted: boolean;
        id: string;
    }>;
    confirm(user: RequestUser, id: string): Promise<{
        shop: {
            shopName: string;
        };
        customer: {
            shopId: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string | null;
            phone: string | null;
            taxId: string | null;
            street: string | null;
            city: string | null;
            state: string | null;
            postalCode: string | null;
            country: string | null;
            customerCode: string;
            customerName: string;
            pan: string | null;
        };
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: import("@prisma/client/runtime/library").Decimal;
                purchasePrice: import("@prisma/client/runtime/library").Decimal;
                sellingPrice: import("@prisma/client/runtime/library").Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            uom: string;
            productId: string;
            quantity: import("@prisma/client/runtime/library").Decimal;
            unitPrice: import("@prisma/client/runtime/library").Decimal;
            lineValue: import("@prisma/client/runtime/library").Decimal;
            discountAmount: import("@prisma/client/runtime/library").Decimal;
            taxAmount: import("@prisma/client/runtime/library").Decimal;
            taxRate: import("@prisma/client/runtime/library").Decimal;
            soHeaderId: string;
            shippedQty: import("@prisma/client/runtime/library").Decimal;
            cgstRate: import("@prisma/client/runtime/library").Decimal;
            sgstRate: import("@prisma/client/runtime/library").Decimal;
            igstRate: import("@prisma/client/runtime/library").Decimal;
        })[];
    } & {
        shopId: string;
        currency: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.SalesOrderStatus;
        remarks: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
        templateVersion: number;
        totalValue: import("@prisma/client/runtime/library").Decimal | null;
        fxRateUsed: import("@prisma/client/runtime/library").Decimal | null;
        discountAmount: import("@prisma/client/runtime/library").Decimal;
        taxAmount: import("@prisma/client/runtime/library").Decimal;
        customerId: string;
        soNumber: string;
        orderDate: Date;
        expectedDate: Date | null;
        fulfillmentStatus: import(".prisma/client").$Enums.FulfillmentStatus;
        gstSupplyType: import(".prisma/client").$Enums.GstSupplyType;
        subtotalBeforeTax: import("@prisma/client/runtime/library").Decimal;
        totalCgst: import("@prisma/client/runtime/library").Decimal;
        totalSgst: import("@prisma/client/runtime/library").Decimal;
        totalIgst: import("@prisma/client/runtime/library").Decimal;
    }>;
    send(user: RequestUser, id: string, resend?: string): Promise<import("../document-email/document-email.types").DocumentEmailSendResult>;
    fulfill(user: RequestUser, id: string): Promise<{
        shop: {
            id: string;
            shopNumber: string;
            shopName: string;
        };
        customer: {
            shopId: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string | null;
            phone: string | null;
            taxId: string | null;
            street: string | null;
            city: string | null;
            state: string | null;
            postalCode: string | null;
            country: string | null;
            customerCode: string;
            customerName: string;
            pan: string | null;
        };
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: import("@prisma/client/runtime/library").Decimal;
                purchasePrice: import("@prisma/client/runtime/library").Decimal;
                sellingPrice: import("@prisma/client/runtime/library").Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            uom: string;
            productId: string;
            quantity: import("@prisma/client/runtime/library").Decimal;
            unitPrice: import("@prisma/client/runtime/library").Decimal;
            lineValue: import("@prisma/client/runtime/library").Decimal;
            discountAmount: import("@prisma/client/runtime/library").Decimal;
            taxAmount: import("@prisma/client/runtime/library").Decimal;
            taxRate: import("@prisma/client/runtime/library").Decimal;
            soHeaderId: string;
            shippedQty: import("@prisma/client/runtime/library").Decimal;
            cgstRate: import("@prisma/client/runtime/library").Decimal;
            sgstRate: import("@prisma/client/runtime/library").Decimal;
            igstRate: import("@prisma/client/runtime/library").Decimal;
        })[];
        salesQuotation: {
            id: string;
            quoteNumber: string;
        } | null;
    } & {
        shopId: string;
        currency: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.SalesOrderStatus;
        remarks: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
        templateVersion: number;
        totalValue: import("@prisma/client/runtime/library").Decimal | null;
        fxRateUsed: import("@prisma/client/runtime/library").Decimal | null;
        discountAmount: import("@prisma/client/runtime/library").Decimal;
        taxAmount: import("@prisma/client/runtime/library").Decimal;
        customerId: string;
        soNumber: string;
        orderDate: Date;
        expectedDate: Date | null;
        fulfillmentStatus: import(".prisma/client").$Enums.FulfillmentStatus;
        gstSupplyType: import(".prisma/client").$Enums.GstSupplyType;
        subtotalBeforeTax: import("@prisma/client/runtime/library").Decimal;
        totalCgst: import("@prisma/client/runtime/library").Decimal;
        totalSgst: import("@prisma/client/runtime/library").Decimal;
        totalIgst: import("@prisma/client/runtime/library").Decimal;
    }>;
}
