import { Prisma, SalesOrderStatus } from '@prisma/client';
import { PrismaService } from '../../prisma/prisma.service';
import type { RequestUser } from '../../common/types/request-user';
import { AuditService } from '../audit/audit.service';
import { DocumentNumberService } from '../stock/document-number.service';
import { CostingService } from '../stock/costing.service';
import { StockService } from '../stock/stock.service';
import { CreateSalesOrderDto } from './dto/create-sales-order.dto';
import { UpdateSalesOrderDto } from './dto/update-sales-order.dto';
import { SubscriptionService } from '../billing/subscription.service';
import { EmailNotificationsService } from '../email-notifications/email-notifications.service';
import { DocumentEmailService } from '../document-email/document-email.service';
export type SalesOrderListQuery = {
    shop_id?: string;
    status?: SalesOrderStatus;
    customer_id?: string;
    date_from?: string;
    date_to?: string;
    cursor?: string;
    take?: number;
};
export declare class SalesOrdersService {
    private readonly prisma;
    private readonly stock;
    private readonly numbers;
    private readonly audit;
    private readonly costing;
    private readonly subscriptions;
    private readonly emailNotifications;
    private readonly documentEmail;
    constructor(prisma: PrismaService, stock: StockService, numbers: DocumentNumberService, audit: AuditService, costing: CostingService, subscriptions: SubscriptionService, emailNotifications: EmailNotificationsService, documentEmail: DocumentEmailService);
    list(user: RequestUser, query?: SalesOrderListQuery): Promise<{
        data: {
            shopId: string;
            shop: {
                id: string;
                shopNumber: string;
                shopName: string;
            };
            customer: {
                id: string;
                customerCode: string;
                customerName: string;
            };
            id: string;
            status: import(".prisma/client").$Enums.SalesOrderStatus;
            remarks: string | null;
            totalValue: Prisma.Decimal | null;
            customerId: string;
            soNumber: string;
            orderDate: Date;
            expectedDate: Date | null;
        }[];
        meta: {
            nextCursor: string | null;
            limit: number;
            hasMore: boolean;
        };
    }>;
    private resolveSupplyType;
    private computeLineTotals;
    create(user: RequestUser, dto: CreateSalesOrderDto): Promise<{
        customer: {
            shopId: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string | null;
            phone: string | null;
            taxId: string | null;
            street: string | null;
            city: string | null;
            state: string | null;
            postalCode: string | null;
            country: string | null;
            customerCode: string;
            customerName: string;
            pan: string | null;
        };
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: Prisma.Decimal;
                purchasePrice: Prisma.Decimal;
                sellingPrice: Prisma.Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            uom: string;
            productId: string;
            quantity: Prisma.Decimal;
            unitPrice: Prisma.Decimal;
            lineValue: Prisma.Decimal;
            discountAmount: Prisma.Decimal;
            taxAmount: Prisma.Decimal;
            taxRate: Prisma.Decimal;
            soHeaderId: string;
            shippedQty: Prisma.Decimal;
            cgstRate: Prisma.Decimal;
            sgstRate: Prisma.Decimal;
            igstRate: Prisma.Decimal;
        })[];
    } & {
        shopId: string;
        currency: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.SalesOrderStatus;
        remarks: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: Prisma.JsonValue | null;
        templateVersion: number;
        totalValue: Prisma.Decimal | null;
        fxRateUsed: Prisma.Decimal | null;
        discountAmount: Prisma.Decimal;
        taxAmount: Prisma.Decimal;
        customerId: string;
        soNumber: string;
        orderDate: Date;
        expectedDate: Date | null;
        fulfillmentStatus: import(".prisma/client").$Enums.FulfillmentStatus;
        gstSupplyType: import(".prisma/client").$Enums.GstSupplyType;
        subtotalBeforeTax: Prisma.Decimal;
        totalCgst: Prisma.Decimal;
        totalSgst: Prisma.Decimal;
        totalIgst: Prisma.Decimal;
    }>;
    get(user: RequestUser, id: string): Promise<{
        shop: {
            id: string;
            shopNumber: string;
            shopName: string;
        };
        customer: {
            shopId: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string | null;
            phone: string | null;
            taxId: string | null;
            street: string | null;
            city: string | null;
            state: string | null;
            postalCode: string | null;
            country: string | null;
            customerCode: string;
            customerName: string;
            pan: string | null;
        };
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: Prisma.Decimal;
                purchasePrice: Prisma.Decimal;
                sellingPrice: Prisma.Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            uom: string;
            productId: string;
            quantity: Prisma.Decimal;
            unitPrice: Prisma.Decimal;
            lineValue: Prisma.Decimal;
            discountAmount: Prisma.Decimal;
            taxAmount: Prisma.Decimal;
            taxRate: Prisma.Decimal;
            soHeaderId: string;
            shippedQty: Prisma.Decimal;
            cgstRate: Prisma.Decimal;
            sgstRate: Prisma.Decimal;
            igstRate: Prisma.Decimal;
        })[];
        salesQuotation: {
            id: string;
            quoteNumber: string;
        } | null;
    } & {
        shopId: string;
        currency: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.SalesOrderStatus;
        remarks: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: Prisma.JsonValue | null;
        templateVersion: number;
        totalValue: Prisma.Decimal | null;
        fxRateUsed: Prisma.Decimal | null;
        discountAmount: Prisma.Decimal;
        taxAmount: Prisma.Decimal;
        customerId: string;
        soNumber: string;
        orderDate: Date;
        expectedDate: Date | null;
        fulfillmentStatus: import(".prisma/client").$Enums.FulfillmentStatus;
        gstSupplyType: import(".prisma/client").$Enums.GstSupplyType;
        subtotalBeforeTax: Prisma.Decimal;
        totalCgst: Prisma.Decimal;
        totalSgst: Prisma.Decimal;
        totalIgst: Prisma.Decimal;
    }>;
    update(user: RequestUser, id: string, dto: UpdateSalesOrderDto): Promise<{
        shop: {
            id: string;
            shopNumber: string;
            shopName: string;
        };
        customer: {
            shopId: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string | null;
            phone: string | null;
            taxId: string | null;
            street: string | null;
            city: string | null;
            state: string | null;
            postalCode: string | null;
            country: string | null;
            customerCode: string;
            customerName: string;
            pan: string | null;
        };
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: Prisma.Decimal;
                purchasePrice: Prisma.Decimal;
                sellingPrice: Prisma.Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            uom: string;
            productId: string;
            quantity: Prisma.Decimal;
            unitPrice: Prisma.Decimal;
            lineValue: Prisma.Decimal;
            discountAmount: Prisma.Decimal;
            taxAmount: Prisma.Decimal;
            taxRate: Prisma.Decimal;
            soHeaderId: string;
            shippedQty: Prisma.Decimal;
            cgstRate: Prisma.Decimal;
            sgstRate: Prisma.Decimal;
            igstRate: Prisma.Decimal;
        })[];
        salesQuotation: {
            id: string;
            quoteNumber: string;
        } | null;
    } & {
        shopId: string;
        currency: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.SalesOrderStatus;
        remarks: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: Prisma.JsonValue | null;
        templateVersion: number;
        totalValue: Prisma.Decimal | null;
        fxRateUsed: Prisma.Decimal | null;
        discountAmount: Prisma.Decimal;
        taxAmount: Prisma.Decimal;
        customerId: string;
        soNumber: string;
        orderDate: Date;
        expectedDate: Date | null;
        fulfillmentStatus: import(".prisma/client").$Enums.FulfillmentStatus;
        gstSupplyType: import(".prisma/client").$Enums.GstSupplyType;
        subtotalBeforeTax: Prisma.Decimal;
        totalCgst: Prisma.Decimal;
        totalSgst: Prisma.Decimal;
        totalIgst: Prisma.Decimal;
    }>;
    remove(user: RequestUser, id: string): Promise<{
        deleted: boolean;
        id: string;
    }>;
    confirm(user: RequestUser, id: string): Promise<{
        shop: {
            shopName: string;
        };
        customer: {
            shopId: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string | null;
            phone: string | null;
            taxId: string | null;
            street: string | null;
            city: string | null;
            state: string | null;
            postalCode: string | null;
            country: string | null;
            customerCode: string;
            customerName: string;
            pan: string | null;
        };
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: Prisma.Decimal;
                purchasePrice: Prisma.Decimal;
                sellingPrice: Prisma.Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            uom: string;
            productId: string;
            quantity: Prisma.Decimal;
            unitPrice: Prisma.Decimal;
            lineValue: Prisma.Decimal;
            discountAmount: Prisma.Decimal;
            taxAmount: Prisma.Decimal;
            taxRate: Prisma.Decimal;
            soHeaderId: string;
            shippedQty: Prisma.Decimal;
            cgstRate: Prisma.Decimal;
            sgstRate: Prisma.Decimal;
            igstRate: Prisma.Decimal;
        })[];
    } & {
        shopId: string;
        currency: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.SalesOrderStatus;
        remarks: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: Prisma.JsonValue | null;
        templateVersion: number;
        totalValue: Prisma.Decimal | null;
        fxRateUsed: Prisma.Decimal | null;
        discountAmount: Prisma.Decimal;
        taxAmount: Prisma.Decimal;
        customerId: string;
        soNumber: string;
        orderDate: Date;
        expectedDate: Date | null;
        fulfillmentStatus: import(".prisma/client").$Enums.FulfillmentStatus;
        gstSupplyType: import(".prisma/client").$Enums.GstSupplyType;
        subtotalBeforeTax: Prisma.Decimal;
        totalCgst: Prisma.Decimal;
        totalSgst: Prisma.Decimal;
        totalIgst: Prisma.Decimal;
    }>;
    sendToCustomer(user: RequestUser, id: string, options?: {
        resend?: boolean;
    }): Promise<import("../document-email/document-email.types").DocumentEmailSendResult>;
    private buildSalesOrderEmailContent;
    private autoSendSalesOrderEmail;
    fulfill(user: RequestUser, id: string): Promise<{
        shop: {
            id: string;
            shopNumber: string;
            shopName: string;
        };
        customer: {
            shopId: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string | null;
            phone: string | null;
            taxId: string | null;
            street: string | null;
            city: string | null;
            state: string | null;
            postalCode: string | null;
            country: string | null;
            customerCode: string;
            customerName: string;
            pan: string | null;
        };
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: Prisma.Decimal;
                purchasePrice: Prisma.Decimal;
                sellingPrice: Prisma.Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            uom: string;
            productId: string;
            quantity: Prisma.Decimal;
            unitPrice: Prisma.Decimal;
            lineValue: Prisma.Decimal;
            discountAmount: Prisma.Decimal;
            taxAmount: Prisma.Decimal;
            taxRate: Prisma.Decimal;
            soHeaderId: string;
            shippedQty: Prisma.Decimal;
            cgstRate: Prisma.Decimal;
            sgstRate: Prisma.Decimal;
            igstRate: Prisma.Decimal;
        })[];
        salesQuotation: {
            id: string;
            quoteNumber: string;
        } | null;
    } & {
        shopId: string;
        currency: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.SalesOrderStatus;
        remarks: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: Prisma.JsonValue | null;
        templateVersion: number;
        totalValue: Prisma.Decimal | null;
        fxRateUsed: Prisma.Decimal | null;
        discountAmount: Prisma.Decimal;
        taxAmount: Prisma.Decimal;
        customerId: string;
        soNumber: string;
        orderDate: Date;
        expectedDate: Date | null;
        fulfillmentStatus: import(".prisma/client").$Enums.FulfillmentStatus;
        gstSupplyType: import(".prisma/client").$Enums.GstSupplyType;
        subtotalBeforeTax: Prisma.Decimal;
        totalCgst: Prisma.Decimal;
        totalSgst: Prisma.Decimal;
        totalIgst: Prisma.Decimal;
    }>;
    fulfillItem(user: RequestUser, soId: string, itemId: string, qty: Prisma.Decimal | number): Promise<{
        customer: {
            shopId: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string | null;
            phone: string | null;
            taxId: string | null;
            street: string | null;
            city: string | null;
            state: string | null;
            postalCode: string | null;
            country: string | null;
            customerCode: string;
            customerName: string;
            pan: string | null;
        };
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: Prisma.Decimal;
                purchasePrice: Prisma.Decimal;
                sellingPrice: Prisma.Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            uom: string;
            productId: string;
            quantity: Prisma.Decimal;
            unitPrice: Prisma.Decimal;
            lineValue: Prisma.Decimal;
            discountAmount: Prisma.Decimal;
            taxAmount: Prisma.Decimal;
            taxRate: Prisma.Decimal;
            soHeaderId: string;
            shippedQty: Prisma.Decimal;
            cgstRate: Prisma.Decimal;
            sgstRate: Prisma.Decimal;
            igstRate: Prisma.Decimal;
        })[];
    } & {
        shopId: string;
        currency: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.SalesOrderStatus;
        remarks: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: Prisma.JsonValue | null;
        templateVersion: number;
        totalValue: Prisma.Decimal | null;
        fxRateUsed: Prisma.Decimal | null;
        discountAmount: Prisma.Decimal;
        taxAmount: Prisma.Decimal;
        customerId: string;
        soNumber: string;
        orderDate: Date;
        expectedDate: Date | null;
        fulfillmentStatus: import(".prisma/client").$Enums.FulfillmentStatus;
        gstSupplyType: import(".prisma/client").$Enums.GstSupplyType;
        subtotalBeforeTax: Prisma.Decimal;
        totalCgst: Prisma.Decimal;
        totalSgst: Prisma.Decimal;
        totalIgst: Prisma.Decimal;
    }>;
}
