import { ConfigService } from '@nestjs/config';
import { type BillingInterval, type PlanId } from '../../common/plans/plan-config';
import { MailService } from '../../common/mail/mail.service';
import { WhatsAppAdapter } from "../agent-platform/channels/whatsapp/whatsapp.adapter";
import { RazorpayService } from '../billing/razorpay.service';
import { LifecycleOrchestratorService } from '../subscription-lifecycle/lifecycle-orchestrator.service';
import { PrismaService } from '../../prisma/prisma.service';
import { AuthService, type LoginContext } from './auth.service';
import { SignupCompletePaidDto } from './dto/signup-complete-paid.dto';
import { SignupFinalizeDto } from './dto/signup-finalize.dto';
import { SignupRequestDto } from './dto/signup-request.dto';
import { SignupResendDto } from './dto/signup-resend.dto';
import { SignupVerifyDto } from './dto/signup-verify.dto';
export type SignupPendingPayload = {
    companyName: string;
    companyAddress?: string;
    plantName: string;
    plantAddress: string;
    contactPerson: string;
    mobile: string;
    adminName: string;
    passwordHash: string;
    plan: PlanId;
    billing: BillingInterval;
    otpVerifiedAt?: string;
    paymentVerifiedAt?: string;
    paymentOrderId?: string;
    paymentPaymentId?: string;
    mfaMethod?: 'totp';
    mfaVerifiedAt?: string;
    backupCodeHashes?: string[];
};
export type SignupSessionResult = Awaited<ReturnType<AuthService['issueSessionForUser']>>;
export type SignupMfaChallengeResult = {
    mfaSetupRequired: true;
    challengeToken: string;
    email: string;
    expiresAt: string;
};
export type SignupVerifyResult = SignupMfaChallengeResult | {
    requiresPayment: true;
    email: string;
    plan: 'pro' | 'plus';
    billing: BillingInterval;
    signupToken: string;
    expiresAt: string;
};
export declare class SignupService {
    private readonly prisma;
    private readonly config;
    private readonly mail;
    private readonly auth;
    private readonly razorpay;
    private readonly lifecycle;
    private readonly whatsapp;
    private readonly logger;
    constructor(prisma: PrismaService, config: ConfigService, mail: MailService, auth: AuthService, razorpay: RazorpayService, lifecycle: LifecycleOrchestratorService, whatsapp: WhatsAppAdapter);
    private signupEnabled;
    private otpTtlMs;
    private signupSessionTtlMs;
    private maxOtpAttempts;
    private bcryptRounds;
    private generateOtp;
    private hashToken;
    private nextSignupToken;
    private uniqueCompanyCode;
    private uniqueShopNumber;
    private assertSignupEnabled;
    private isPaidSignupPlan;
    private assertEmailAvailable;
    private loadPendingByToken;
    private rotateSignupSession;
    private createWorkspaceFromPending;
    private normalizePhone;
    private maskPhone;
    private sendWhatsAppOtp;
    requestSignup(dto: SignupRequestDto): Promise<{
        expiresAt: string;
        phoneMasked?: string | undefined;
        ok: boolean;
        message: string;
        email: string;
        phoneOtpSent: boolean;
    }>;
    resendOtp(dto: SignupResendDto): Promise<{
        expiresAt: string;
        phoneMasked?: string | undefined;
        ok: boolean;
        message: string;
        email: string;
        phoneOtpSent: boolean;
    }>;
    verifySignup(dto: SignupVerifyDto, _ctx: LoginContext): Promise<SignupVerifyResult>;
    completePaidSignup(dto: SignupCompletePaidDto, _ctx: LoginContext): Promise<SignupMfaChallengeResult>;
    finalizeSignup(dto: SignupFinalizeDto, ctx: LoginContext): Promise<SignupSessionResult>;
}
