#!/usr/bin/env bash
# Point-in-time recovery (PITR) using physical base backup + WAL archive.
#
# WARNING: This stops PostgreSQL and replaces PGDATA. Run only during maintenance.
#
# Usage:
#   sudo ./pg-restore-pitr.sh [base_tarball] [recovery_target_time_iso]
#
# Example recovery target:
#   2026-05-26T10:30:00Z
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/lib.sh"

require_cmd tar
require_cmd psql

BASE_TAR="${1:-${FULL_DIR}/latest-base.tar.gz}"
RECOVERY_TARGET="${2:-}"

[[ -f "$BASE_TAR" ]] || fail "Base backup not found: $BASE_TAR"
verify_checksum "$BASE_TAR"

PGDATA="${PGDATA:-/var/lib/postgresql/$(ls /etc/postgresql 2>/dev/null | head -n1)/main}"
PGDATA="${PGDATA:-/var/lib/postgresql/data}"

if [[ ! -d "$PGDATA" ]]; then
  fail "PGDATA not found: $PGDATA (set PGDATA env var)"
fi

STAGING="$(mktemp -d /tmp/pg-pitr-XXXXXX)"
RESTORED="${STAGING}/restored"

log "PITR restore starting"
log "  base: $BASE_TAR"
log "  PGDATA: $PGDATA"
log "  WAL archive: $WAL_DIR"
if [[ -n "$RECOVERY_TARGET" ]]; then
  log "  recovery_target_time: $RECOVERY_TARGET"
fi

mkdir -p "$RESTORED"
tar -xzf "$BASE_TAR" -C "$STAGING"

# pg_basebackup -Ft creates base.tar.gz and pg_wal.tar.gz inside extracted dir
BASE_EXTRACT="$(find "$STAGING" -maxdepth 2 -name 'base.tar.gz' | head -n1 || true)"
WAL_BUNDLE="$(find "$STAGING" -maxdepth 2 -name 'pg_wal.tar.gz' | head -n1 || true)"

if [[ -z "$BASE_EXTRACT" ]]; then
  fail "Could not locate base.tar.gz inside ${BASE_TAR}"
fi

mkdir -p "$RESTORED"
tar -xzf "$BASE_EXTRACT" -C "$RESTORED"
if [[ -n "$WAL_BUNDLE" ]]; then
  tar -xzf "$WAL_BUNDLE" -C "$RESTORED"
fi

cat >"${RESTORED}/recovery.signal" <<EOF
# Generated by pg-restore-pitr.sh on $(timestamp)
EOF

RESTORE_CMD="cp ${WAL_DIR}/%f %p"
if [[ -n "$RECOVERY_TARGET" ]]; then
  cat >>"${RESTORED}/postgresql.auto.conf" <<EOF
restore_command = '${RESTORE_CMD}'
recovery_target_time = '${RECOVERY_TARGET}'
recovery_target_action = 'promote'
EOF
else
  cat >>"${RESTORED}/postgresql.auto.conf" <<EOF
restore_command = '${RESTORE_CMD}'
recovery_target_action = 'promote'
EOF
fi

log "Stopping PostgreSQL..."
systemctl stop postgresql || systemctl stop "postgresql@$(ls /etc/postgresql | head -n1)-main" || true

BACKUP_PGDATA="${PGDATA}.pre-pitr-$(date +%s)"
log "Moving current PGDATA -> ${BACKUP_PGDATA}"
mv "$PGDATA" "$BACKUP_PGDATA"
mkdir -p "$(dirname "$PGDATA")"
mv "$RESTORED" "$PGDATA"
chown -R postgres:postgres "$PGDATA"

log "Starting PostgreSQL in recovery mode..."
systemctl start postgresql || systemctl start "postgresql@$(ls /etc/postgresql | head -n1)-main"

log "Monitor recovery:"
log "  sudo -u postgres psql -c \"SELECT pg_is_in_recovery(), pg_last_wal_replay_lsn();\""
log "When pg_is_in_recovery = false, recovery is complete."
log "Previous data directory preserved at: ${BACKUP_PGDATA}"
