import { DocumentStatus } from '@prisma/client';
import type { RequestUser } from '../../common/types/request-user';
import { CreateGoodsReceiptDto } from './dto/create-goods-receipt.dto';
import { UpdateGoodsReceiptDto } from './dto/update-goods-receipt.dto';
import { GoodsReceiptsService } from './goods-receipts.service';
export declare class GoodsReceiptsController {
    private readonly service;
    constructor(service: GoodsReceiptsService);
    list(user: RequestUser, shopId?: string, dateFrom?: string, dateTo?: string, status?: DocumentStatus, cursor?: string, take?: string): Promise<{
        data: {
            totalValue: import("@prisma/client/runtime/library").Decimal;
            shop: {
                id: string;
                address: string;
                brandingProfileId: string | null;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                email: string;
                companyId: string | null;
                shopNumber: string;
                shopName: string;
                taxId: string | null;
                contactPerson: string;
                mobile: string;
                costingMethod: import(".prisma/client").$Enums.CostingMethod;
                functionalCurrency: string;
            };
            items: {
                product: {
                    id: string;
                    description: string;
                    productCode: string;
                };
                id: string;
                uom: string;
                productId: string;
                storageLocationId: string | null;
                batchNumber: string | null;
                expiryDate: Date | null;
                quantity: import("@prisma/client/runtime/library").Decimal;
                lineValue: import("@prisma/client/runtime/library").Decimal;
                purchaseRate: import("@prisma/client/runtime/library").Decimal;
                serialNumber: string | null;
            }[];
            shopId: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            status: import(".prisma/client").$Enums.DocumentStatus;
            remarks: string | null;
            supplierName: string;
            brandingMode: import(".prisma/client").$Enums.BrandingMode;
            brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
            templateVersion: number;
            postedAt: Date | null;
            grNumber: string;
            grDate: Date;
            purchaseOrderId: string | null;
            receiptType: import(".prisma/client").$Enums.ReceiptType;
            receiptSource: import(".prisma/client").$Enums.ReceiptSource;
            inwardShift: import(".prisma/client").$Enums.InwardShift | null;
            supplierRef: string | null;
        }[];
        meta: {
            nextCursor: string | null;
            limit: number;
            hasMore: boolean;
        };
    }>;
    create(user: RequestUser, dto: CreateGoodsReceiptDto, idempotencyKey?: string): Promise<{
        shop: {
            id: string;
            address: string;
            brandingProfileId: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
            taxId: string | null;
            contactPerson: string;
            mobile: string;
            costingMethod: import(".prisma/client").$Enums.CostingMethod;
            functionalCurrency: string;
        };
        items: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            uom: string;
            productId: string;
            storageLocationId: string | null;
            batchNumber: string | null;
            expiryDate: Date | null;
            quantity: import("@prisma/client/runtime/library").Decimal;
            lineValue: import("@prisma/client/runtime/library").Decimal;
            grHeaderId: string;
            purchaseRate: import("@prisma/client/runtime/library").Decimal;
            serialNumber: string | null;
        }[];
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.DocumentStatus;
        remarks: string | null;
        supplierName: string;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
        templateVersion: number;
        postedAt: Date | null;
        totalValue: import("@prisma/client/runtime/library").Decimal | null;
        grNumber: string;
        grDate: Date;
        purchaseOrderId: string | null;
        receiptType: import(".prisma/client").$Enums.ReceiptType;
        receiptSource: import(".prisma/client").$Enums.ReceiptSource;
        inwardShift: import(".prisma/client").$Enums.InwardShift | null;
        supplierRef: string | null;
    }>;
    print(user: RequestUser, id: string): Promise<string>;
    get(user: RequestUser, id: string): Promise<{
        shop: {
            id: string;
            address: string;
            brandingProfileId: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
            taxId: string | null;
            contactPerson: string;
            mobile: string;
            costingMethod: import(".prisma/client").$Enums.CostingMethod;
            functionalCurrency: string;
        };
        items: ({
            storageLocation: {
                shopId: string;
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                name: string;
                code: string;
                description: string | null;
            } | null;
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: import("@prisma/client/runtime/library").Decimal;
                purchasePrice: import("@prisma/client/runtime/library").Decimal;
                sellingPrice: import("@prisma/client/runtime/library").Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            uom: string;
            productId: string;
            storageLocationId: string | null;
            batchNumber: string | null;
            expiryDate: Date | null;
            quantity: import("@prisma/client/runtime/library").Decimal;
            lineValue: import("@prisma/client/runtime/library").Decimal;
            grHeaderId: string;
            purchaseRate: import("@prisma/client/runtime/library").Decimal;
            serialNumber: string | null;
        })[];
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.DocumentStatus;
        remarks: string | null;
        supplierName: string;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
        templateVersion: number;
        postedAt: Date | null;
        totalValue: import("@prisma/client/runtime/library").Decimal | null;
        grNumber: string;
        grDate: Date;
        purchaseOrderId: string | null;
        receiptType: import(".prisma/client").$Enums.ReceiptType;
        receiptSource: import(".prisma/client").$Enums.ReceiptSource;
        inwardShift: import(".prisma/client").$Enums.InwardShift | null;
        supplierRef: string | null;
    }>;
    update(user: RequestUser, id: string, dto: UpdateGoodsReceiptDto): Promise<{
        shop: {
            id: string;
            address: string;
            brandingProfileId: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
            taxId: string | null;
            contactPerson: string;
            mobile: string;
            costingMethod: import(".prisma/client").$Enums.CostingMethod;
            functionalCurrency: string;
        };
        items: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            uom: string;
            productId: string;
            storageLocationId: string | null;
            batchNumber: string | null;
            expiryDate: Date | null;
            quantity: import("@prisma/client/runtime/library").Decimal;
            lineValue: import("@prisma/client/runtime/library").Decimal;
            grHeaderId: string;
            purchaseRate: import("@prisma/client/runtime/library").Decimal;
            serialNumber: string | null;
        }[];
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.DocumentStatus;
        remarks: string | null;
        supplierName: string;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
        templateVersion: number;
        postedAt: Date | null;
        totalValue: import("@prisma/client/runtime/library").Decimal | null;
        grNumber: string;
        grDate: Date;
        purchaseOrderId: string | null;
        receiptType: import(".prisma/client").$Enums.ReceiptType;
        receiptSource: import(".prisma/client").$Enums.ReceiptSource;
        inwardShift: import(".prisma/client").$Enums.InwardShift | null;
        supplierRef: string | null;
    }>;
    post(user: RequestUser, id: string): Promise<{
        shop: {
            id: string;
            address: string;
            brandingProfileId: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
            taxId: string | null;
            contactPerson: string;
            mobile: string;
            costingMethod: import(".prisma/client").$Enums.CostingMethod;
            functionalCurrency: string;
        };
        items: ({
            storageLocation: {
                shopId: string;
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                name: string;
                code: string;
                description: string | null;
            } | null;
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: import("@prisma/client/runtime/library").Decimal;
                purchasePrice: import("@prisma/client/runtime/library").Decimal;
                sellingPrice: import("@prisma/client/runtime/library").Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            uom: string;
            productId: string;
            storageLocationId: string | null;
            batchNumber: string | null;
            expiryDate: Date | null;
            quantity: import("@prisma/client/runtime/library").Decimal;
            lineValue: import("@prisma/client/runtime/library").Decimal;
            grHeaderId: string;
            purchaseRate: import("@prisma/client/runtime/library").Decimal;
            serialNumber: string | null;
        })[];
        purchaseOrder: {
            poNumber: string;
        } | null;
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.DocumentStatus;
        remarks: string | null;
        supplierName: string;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
        templateVersion: number;
        postedAt: Date | null;
        totalValue: import("@prisma/client/runtime/library").Decimal | null;
        grNumber: string;
        grDate: Date;
        purchaseOrderId: string | null;
        receiptType: import(".prisma/client").$Enums.ReceiptType;
        receiptSource: import(".prisma/client").$Enums.ReceiptSource;
        inwardShift: import(".prisma/client").$Enums.InwardShift | null;
        supplierRef: string | null;
    }>;
    send(user: RequestUser, id: string, resend?: string): Promise<import("../document-email/document-email.types").DocumentEmailSendResult>;
    remove(user: RequestUser, id: string): Promise<{
        ok: boolean;
    }>;
}
