import { DocumentStatus, Prisma } from '@prisma/client';
import { NotificationService } from '../notifications/services/notification.service';
import { DocumentPdfService } from '../../common/pdf/document-pdf.service';
import { PrismaService } from '../../prisma/prisma.service';
import type { RequestUser } from '../../common/types/request-user';
import { DocumentNumberService } from '../stock/document-number.service';
import { StockService } from '../stock/stock.service';
import { CostingService } from '../stock/costing.service';
import { AuditService } from '../audit/audit.service';
import { CreateGoodsReceiptDto } from './dto/create-goods-receipt.dto';
import { UpdateGoodsReceiptDto } from './dto/update-goods-receipt.dto';
import { EmailNotificationsService } from '../email-notifications/email-notifications.service';
import { DocumentEmailService } from '../document-email/document-email.service';
export declare class GoodsReceiptsService {
    private readonly prisma;
    private readonly stock;
    private readonly numbers;
    private readonly audit;
    private readonly costing;
    private readonly emailNotifications;
    private readonly documentPdf;
    private readonly documentEmail;
    private readonly notifications;
    constructor(prisma: PrismaService, stock: StockService, numbers: DocumentNumberService, audit: AuditService, costing: CostingService, emailNotifications: EmailNotificationsService, documentPdf: DocumentPdfService, documentEmail: DocumentEmailService, notifications: NotificationService);
    private assertStorageLocationsForShop;
    private validateAgainstPurchaseOrder;
    private ensureProductPlantForReceipt;
    list(user: RequestUser, query: {
        shop_id?: string;
        date_from?: string;
        date_to?: string;
        status?: DocumentStatus;
        cursor?: string;
        take?: number;
    }): Promise<{
        data: {
            totalValue: Prisma.Decimal;
            shop: {
                id: string;
                address: string;
                brandingProfileId: string | null;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                email: string;
                companyId: string | null;
                shopNumber: string;
                shopName: string;
                taxId: string | null;
                contactPerson: string;
                mobile: string;
                costingMethod: import(".prisma/client").$Enums.CostingMethod;
                functionalCurrency: string;
            };
            items: {
                product: {
                    id: string;
                    description: string;
                    productCode: string;
                };
                id: string;
                uom: string;
                productId: string;
                storageLocationId: string | null;
                batchNumber: string | null;
                expiryDate: Date | null;
                quantity: Prisma.Decimal;
                lineValue: Prisma.Decimal;
                purchaseRate: Prisma.Decimal;
                serialNumber: string | null;
            }[];
            shopId: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            status: import(".prisma/client").$Enums.DocumentStatus;
            remarks: string | null;
            supplierName: string;
            brandingMode: import(".prisma/client").$Enums.BrandingMode;
            brandingSnapshot: Prisma.JsonValue | null;
            templateVersion: number;
            postedAt: Date | null;
            grNumber: string;
            grDate: Date;
            purchaseOrderId: string | null;
            receiptType: import(".prisma/client").$Enums.ReceiptType;
            receiptSource: import(".prisma/client").$Enums.ReceiptSource;
            inwardShift: import(".prisma/client").$Enums.InwardShift | null;
            supplierRef: string | null;
        }[];
        meta: {
            nextCursor: string | null;
            limit: number;
            hasMore: boolean;
        };
    }>;
    create(user: RequestUser, dto: CreateGoodsReceiptDto): Promise<{
        shop: {
            id: string;
            address: string;
            brandingProfileId: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
            taxId: string | null;
            contactPerson: string;
            mobile: string;
            costingMethod: import(".prisma/client").$Enums.CostingMethod;
            functionalCurrency: string;
        };
        items: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            uom: string;
            productId: string;
            storageLocationId: string | null;
            batchNumber: string | null;
            expiryDate: Date | null;
            quantity: Prisma.Decimal;
            lineValue: Prisma.Decimal;
            grHeaderId: string;
            purchaseRate: Prisma.Decimal;
            serialNumber: string | null;
        }[];
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.DocumentStatus;
        remarks: string | null;
        supplierName: string;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: Prisma.JsonValue | null;
        templateVersion: number;
        postedAt: Date | null;
        totalValue: Prisma.Decimal | null;
        grNumber: string;
        grDate: Date;
        purchaseOrderId: string | null;
        receiptType: import(".prisma/client").$Enums.ReceiptType;
        receiptSource: import(".prisma/client").$Enums.ReceiptSource;
        inwardShift: import(".prisma/client").$Enums.InwardShift | null;
        supplierRef: string | null;
    }>;
    get(user: RequestUser, id: string): Promise<{
        shop: {
            id: string;
            address: string;
            brandingProfileId: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
            taxId: string | null;
            contactPerson: string;
            mobile: string;
            costingMethod: import(".prisma/client").$Enums.CostingMethod;
            functionalCurrency: string;
        };
        items: ({
            storageLocation: {
                shopId: string;
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                name: string;
                code: string;
                description: string | null;
            } | null;
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: Prisma.Decimal;
                purchasePrice: Prisma.Decimal;
                sellingPrice: Prisma.Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            uom: string;
            productId: string;
            storageLocationId: string | null;
            batchNumber: string | null;
            expiryDate: Date | null;
            quantity: Prisma.Decimal;
            lineValue: Prisma.Decimal;
            grHeaderId: string;
            purchaseRate: Prisma.Decimal;
            serialNumber: string | null;
        })[];
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.DocumentStatus;
        remarks: string | null;
        supplierName: string;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: Prisma.JsonValue | null;
        templateVersion: number;
        postedAt: Date | null;
        totalValue: Prisma.Decimal | null;
        grNumber: string;
        grDate: Date;
        purchaseOrderId: string | null;
        receiptType: import(".prisma/client").$Enums.ReceiptType;
        receiptSource: import(".prisma/client").$Enums.ReceiptSource;
        inwardShift: import(".prisma/client").$Enums.InwardShift | null;
        supplierRef: string | null;
    }>;
    update(user: RequestUser, id: string, dto: UpdateGoodsReceiptDto): Promise<{
        shop: {
            id: string;
            address: string;
            brandingProfileId: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
            taxId: string | null;
            contactPerson: string;
            mobile: string;
            costingMethod: import(".prisma/client").$Enums.CostingMethod;
            functionalCurrency: string;
        };
        items: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            uom: string;
            productId: string;
            storageLocationId: string | null;
            batchNumber: string | null;
            expiryDate: Date | null;
            quantity: Prisma.Decimal;
            lineValue: Prisma.Decimal;
            grHeaderId: string;
            purchaseRate: Prisma.Decimal;
            serialNumber: string | null;
        }[];
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.DocumentStatus;
        remarks: string | null;
        supplierName: string;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: Prisma.JsonValue | null;
        templateVersion: number;
        postedAt: Date | null;
        totalValue: Prisma.Decimal | null;
        grNumber: string;
        grDate: Date;
        purchaseOrderId: string | null;
        receiptType: import(".prisma/client").$Enums.ReceiptType;
        receiptSource: import(".prisma/client").$Enums.ReceiptSource;
        inwardShift: import(".prisma/client").$Enums.InwardShift | null;
        supplierRef: string | null;
    }>;
    post(user: RequestUser, id: string): Promise<{
        shop: {
            id: string;
            address: string;
            brandingProfileId: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
            taxId: string | null;
            contactPerson: string;
            mobile: string;
            costingMethod: import(".prisma/client").$Enums.CostingMethod;
            functionalCurrency: string;
        };
        items: ({
            storageLocation: {
                shopId: string;
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                name: string;
                code: string;
                description: string | null;
            } | null;
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: Prisma.Decimal;
                purchasePrice: Prisma.Decimal;
                sellingPrice: Prisma.Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            uom: string;
            productId: string;
            storageLocationId: string | null;
            batchNumber: string | null;
            expiryDate: Date | null;
            quantity: Prisma.Decimal;
            lineValue: Prisma.Decimal;
            grHeaderId: string;
            purchaseRate: Prisma.Decimal;
            serialNumber: string | null;
        })[];
        purchaseOrder: {
            poNumber: string;
        } | null;
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.DocumentStatus;
        remarks: string | null;
        supplierName: string;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: Prisma.JsonValue | null;
        templateVersion: number;
        postedAt: Date | null;
        totalValue: Prisma.Decimal | null;
        grNumber: string;
        grDate: Date;
        purchaseOrderId: string | null;
        receiptType: import(".prisma/client").$Enums.ReceiptType;
        receiptSource: import(".prisma/client").$Enums.ReceiptSource;
        inwardShift: import(".prisma/client").$Enums.InwardShift | null;
        supplierRef: string | null;
    }>;
    private buildGoodsReceiptEmailContent;
    sendToSupplier(user: RequestUser, id: string, options?: {
        resend?: boolean;
    }): Promise<import("../document-email/document-email.types").DocumentEmailSendResult>;
    private autoSendGoodsReceiptEmail;
    print(user: RequestUser, id: string): Promise<string>;
    remove(user: RequestUser, id: string): Promise<{
        ok: boolean;
    }>;
}
