import { ConfigService } from '@nestjs/config';
import { Prisma } from '@prisma/client';
import { MailService } from '../../common/mail/mail.service';
import { PrismaService } from '../../prisma/prisma.service';
import type { RequestUser } from '../../common/types/request-user';
import { DocumentNumberService } from '../stock/document-number.service';
import { CreateSalesQuotationDto } from './dto/create-sales-quotation.dto';
import { UpdateSalesQuotationDto } from './dto/update-sales-quotation.dto';
import { SubscriptionService } from '../billing/subscription.service';
import { EmailNotificationsService } from '../email-notifications/email-notifications.service';
import { DocumentEmailService } from '../document-email/document-email.service';
import type { DocumentEmailSendResult } from '../document-email/document-email.types';
export declare class SalesQuotationsService {
    private readonly prisma;
    private readonly numbers;
    private readonly mail;
    private readonly config;
    private readonly subscriptions;
    private readonly emailNotifications;
    private readonly documentEmail;
    constructor(prisma: PrismaService, numbers: DocumentNumberService, mail: MailService, config: ConfigService, subscriptions: SubscriptionService, emailNotifications: EmailNotificationsService, documentEmail: DocumentEmailService);
    private computeLines;
    private newPortalToken;
    private emailQuotation;
    private withEmailDelivery;
    list(user: RequestUser, customerId?: string): Promise<({
        customer: {
            id: string;
            email: string | null;
            customerCode: string;
            customerName: string;
        };
        items: ({
            product: {
                id: string;
                description: string;
                productCode: string;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            uom: string;
            productId: string;
            quantity: Prisma.Decimal;
            unitPrice: Prisma.Decimal;
            lineValue: Prisma.Decimal;
            quoteHeaderId: string;
        })[];
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.SalesQuotationStatus;
        remarks: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: Prisma.JsonValue | null;
        templateVersion: number;
        quoteNumber: string;
        quoteDate: Date;
        totalValue: Prisma.Decimal | null;
        validUntil: Date | null;
        customerId: string;
        salesOrderId: string | null;
        portalToken: string | null;
        customerRequestedTotal: Prisma.Decimal | null;
        customerRequestNote: string | null;
        customerRespondedAt: Date | null;
    })[]>;
    get(user: RequestUser, id: string): Promise<{
        shop: {
            id: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
        };
        customer: {
            shopId: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string | null;
            phone: string | null;
            taxId: string | null;
            street: string | null;
            city: string | null;
            state: string | null;
            postalCode: string | null;
            country: string | null;
            customerCode: string;
            customerName: string;
            pan: string | null;
        };
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: Prisma.Decimal;
                purchasePrice: Prisma.Decimal;
                sellingPrice: Prisma.Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            uom: string;
            productId: string;
            quantity: Prisma.Decimal;
            unitPrice: Prisma.Decimal;
            lineValue: Prisma.Decimal;
            quoteHeaderId: string;
        })[];
        salesOrder: {
            id: string;
            status: import(".prisma/client").$Enums.SalesOrderStatus;
            soNumber: string;
        } | null;
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.SalesQuotationStatus;
        remarks: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: Prisma.JsonValue | null;
        templateVersion: number;
        quoteNumber: string;
        quoteDate: Date;
        totalValue: Prisma.Decimal | null;
        validUntil: Date | null;
        customerId: string;
        salesOrderId: string | null;
        portalToken: string | null;
        customerRequestedTotal: Prisma.Decimal | null;
        customerRequestNote: string | null;
        customerRespondedAt: Date | null;
    }>;
    create(user: RequestUser, dto: CreateSalesQuotationDto): Promise<{
        customer: {
            shopId: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string | null;
            phone: string | null;
            taxId: string | null;
            street: string | null;
            city: string | null;
            state: string | null;
            postalCode: string | null;
            country: string | null;
            customerCode: string;
            customerName: string;
            pan: string | null;
        };
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: Prisma.Decimal;
                purchasePrice: Prisma.Decimal;
                sellingPrice: Prisma.Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            uom: string;
            productId: string;
            quantity: Prisma.Decimal;
            unitPrice: Prisma.Decimal;
            lineValue: Prisma.Decimal;
            quoteHeaderId: string;
        })[];
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.SalesQuotationStatus;
        remarks: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: Prisma.JsonValue | null;
        templateVersion: number;
        quoteNumber: string;
        quoteDate: Date;
        totalValue: Prisma.Decimal | null;
        validUntil: Date | null;
        customerId: string;
        salesOrderId: string | null;
        portalToken: string | null;
        customerRequestedTotal: Prisma.Decimal | null;
        customerRequestNote: string | null;
        customerRespondedAt: Date | null;
    }>;
    update(user: RequestUser, id: string, dto: UpdateSalesQuotationDto): Promise<{
        shop: {
            id: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
        };
        customer: {
            shopId: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string | null;
            phone: string | null;
            taxId: string | null;
            street: string | null;
            city: string | null;
            state: string | null;
            postalCode: string | null;
            country: string | null;
            customerCode: string;
            customerName: string;
            pan: string | null;
        };
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: Prisma.Decimal;
                purchasePrice: Prisma.Decimal;
                sellingPrice: Prisma.Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            uom: string;
            productId: string;
            quantity: Prisma.Decimal;
            unitPrice: Prisma.Decimal;
            lineValue: Prisma.Decimal;
            quoteHeaderId: string;
        })[];
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.SalesQuotationStatus;
        remarks: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: Prisma.JsonValue | null;
        templateVersion: number;
        quoteNumber: string;
        quoteDate: Date;
        totalValue: Prisma.Decimal | null;
        validUntil: Date | null;
        customerId: string;
        salesOrderId: string | null;
        portalToken: string | null;
        customerRequestedTotal: Prisma.Decimal | null;
        customerRequestNote: string | null;
        customerRespondedAt: Date | null;
    }>;
    send(user: RequestUser, id: string): Promise<{
        shop: {
            id: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
        };
        customer: {
            shopId: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string | null;
            phone: string | null;
            taxId: string | null;
            street: string | null;
            city: string | null;
            state: string | null;
            postalCode: string | null;
            country: string | null;
            customerCode: string;
            customerName: string;
            pan: string | null;
        };
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: Prisma.Decimal;
                purchasePrice: Prisma.Decimal;
                sellingPrice: Prisma.Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            uom: string;
            productId: string;
            quantity: Prisma.Decimal;
            unitPrice: Prisma.Decimal;
            lineValue: Prisma.Decimal;
            quoteHeaderId: string;
        })[];
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.SalesQuotationStatus;
        remarks: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: Prisma.JsonValue | null;
        templateVersion: number;
        quoteNumber: string;
        quoteDate: Date;
        totalValue: Prisma.Decimal | null;
        validUntil: Date | null;
        customerId: string;
        salesOrderId: string | null;
        portalToken: string | null;
        customerRequestedTotal: Prisma.Decimal | null;
        customerRequestNote: string | null;
        customerRespondedAt: Date | null;
    } & {
        emailDelivery: {
            messageId: string;
            to: string;
            from: string;
            replyTo: string;
        } | undefined;
    }>;
    sendEmail(user: RequestUser, id: string, options?: {
        resend?: boolean;
    }): Promise<DocumentEmailSendResult | ({
        shop: {
            id: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
        };
        customer: {
            shopId: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string | null;
            phone: string | null;
            taxId: string | null;
            street: string | null;
            city: string | null;
            state: string | null;
            postalCode: string | null;
            country: string | null;
            customerCode: string;
            customerName: string;
            pan: string | null;
        };
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: Prisma.Decimal;
                purchasePrice: Prisma.Decimal;
                sellingPrice: Prisma.Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            uom: string;
            productId: string;
            quantity: Prisma.Decimal;
            unitPrice: Prisma.Decimal;
            lineValue: Prisma.Decimal;
            quoteHeaderId: string;
        })[];
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.SalesQuotationStatus;
        remarks: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: Prisma.JsonValue | null;
        templateVersion: number;
        quoteNumber: string;
        quoteDate: Date;
        totalValue: Prisma.Decimal | null;
        validUntil: Date | null;
        customerId: string;
        salesOrderId: string | null;
        portalToken: string | null;
        customerRequestedTotal: Prisma.Decimal | null;
        customerRequestNote: string | null;
        customerRespondedAt: Date | null;
    } & {
        emailDelivery: {
            messageId: string;
            to: string;
            from: string;
            replyTo: string;
        } | undefined;
    })>;
    resend(user: RequestUser, id: string): Promise<{
        shop: {
            id: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
        };
        customer: {
            shopId: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string | null;
            phone: string | null;
            taxId: string | null;
            street: string | null;
            city: string | null;
            state: string | null;
            postalCode: string | null;
            country: string | null;
            customerCode: string;
            customerName: string;
            pan: string | null;
        };
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: Prisma.Decimal;
                purchasePrice: Prisma.Decimal;
                sellingPrice: Prisma.Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            uom: string;
            productId: string;
            quantity: Prisma.Decimal;
            unitPrice: Prisma.Decimal;
            lineValue: Prisma.Decimal;
            quoteHeaderId: string;
        })[];
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.SalesQuotationStatus;
        remarks: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: Prisma.JsonValue | null;
        templateVersion: number;
        quoteNumber: string;
        quoteDate: Date;
        totalValue: Prisma.Decimal | null;
        validUntil: Date | null;
        customerId: string;
        salesOrderId: string | null;
        portalToken: string | null;
        customerRequestedTotal: Prisma.Decimal | null;
        customerRequestNote: string | null;
        customerRespondedAt: Date | null;
    } & {
        emailDelivery: {
            messageId: string;
            to: string;
            from: string;
            replyTo: string;
        } | undefined;
    }>;
    cancel(user: RequestUser, id: string): Promise<{
        customer: {
            shopId: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string | null;
            phone: string | null;
            taxId: string | null;
            street: string | null;
            city: string | null;
            state: string | null;
            postalCode: string | null;
            country: string | null;
            customerCode: string;
            customerName: string;
            pan: string | null;
        };
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: Prisma.Decimal;
                purchasePrice: Prisma.Decimal;
                sellingPrice: Prisma.Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            uom: string;
            productId: string;
            quantity: Prisma.Decimal;
            unitPrice: Prisma.Decimal;
            lineValue: Prisma.Decimal;
            quoteHeaderId: string;
        })[];
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.SalesQuotationStatus;
        remarks: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: Prisma.JsonValue | null;
        templateVersion: number;
        quoteNumber: string;
        quoteDate: Date;
        totalValue: Prisma.Decimal | null;
        validUntil: Date | null;
        customerId: string;
        salesOrderId: string | null;
        portalToken: string | null;
        customerRequestedTotal: Prisma.Decimal | null;
        customerRequestNote: string | null;
        customerRespondedAt: Date | null;
    }>;
    accept(user: RequestUser, id: string): Promise<{
        customer: {
            shopId: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string | null;
            phone: string | null;
            taxId: string | null;
            street: string | null;
            city: string | null;
            state: string | null;
            postalCode: string | null;
            country: string | null;
            customerCode: string;
            customerName: string;
            pan: string | null;
        };
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: Prisma.Decimal;
                purchasePrice: Prisma.Decimal;
                sellingPrice: Prisma.Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            uom: string;
            productId: string;
            quantity: Prisma.Decimal;
            unitPrice: Prisma.Decimal;
            lineValue: Prisma.Decimal;
            quoteHeaderId: string;
        })[];
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.SalesQuotationStatus;
        remarks: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: Prisma.JsonValue | null;
        templateVersion: number;
        quoteNumber: string;
        quoteDate: Date;
        totalValue: Prisma.Decimal | null;
        validUntil: Date | null;
        customerId: string;
        salesOrderId: string | null;
        portalToken: string | null;
        customerRequestedTotal: Prisma.Decimal | null;
        customerRequestNote: string | null;
        customerRespondedAt: Date | null;
    }>;
    convertToSalesOrder(user: RequestUser, id: string): Promise<{
        customer: {
            shopId: string;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string | null;
            phone: string | null;
            taxId: string | null;
            street: string | null;
            city: string | null;
            state: string | null;
            postalCode: string | null;
            country: string | null;
            customerCode: string;
            customerName: string;
            pan: string | null;
        };
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: Prisma.Decimal;
                purchasePrice: Prisma.Decimal;
                sellingPrice: Prisma.Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            uom: string;
            productId: string;
            quantity: Prisma.Decimal;
            unitPrice: Prisma.Decimal;
            lineValue: Prisma.Decimal;
            quoteHeaderId: string;
        })[];
        salesOrder: {
            id: string;
            status: import(".prisma/client").$Enums.SalesOrderStatus;
            soNumber: string;
        } | null;
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.SalesQuotationStatus;
        remarks: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: Prisma.JsonValue | null;
        templateVersion: number;
        quoteNumber: string;
        quoteDate: Date;
        totalValue: Prisma.Decimal | null;
        validUntil: Date | null;
        customerId: string;
        salesOrderId: string | null;
        portalToken: string | null;
        customerRequestedTotal: Prisma.Decimal | null;
        customerRequestNote: string | null;
        customerRespondedAt: Date | null;
    }>;
}
