import { PrismaService } from '../../prisma/prisma.service';
import type { RequestUser } from '../../common/types/request-user';
import { CreateShopDto } from './dto/create-shop.dto';
import { UpdateShopDto } from './dto/update-shop.dto';
import { SubscriptionService } from '../billing/subscription.service';
import { BrandingProfileService } from '../../common/branding/branding-profile.service';
import { BrandingResolverService } from '../../common/branding/branding-resolver.service';
import type { UpdateBrandingProfileDto } from '../../common/branding/dto/update-branding-profile.dto';
export declare class ShopsService {
    private readonly prisma;
    private readonly subscriptions;
    private readonly branding;
    private readonly brandingResolver;
    constructor(prisma: PrismaService, subscriptions: SubscriptionService, branding: BrandingProfileService, brandingResolver: BrandingResolverService);
    private repairOrphanShops;
    private assertPlantAccess;
    private purgeUnusedStorageLocations;
    list(user: RequestUser, query: {
        is_active?: boolean;
        cursor?: string;
        take?: number;
    }): Promise<{
        data: ({
            company: {
                id: string;
                companyCode: string;
                companyName: string;
                address: string | null;
                brandingProfileId: string | null;
                isActive: boolean;
                subscriptionPlan: import(".prisma/client").$Enums.SubscriptionPlan;
                billingCycle: import(".prisma/client").$Enums.BillingCycle | null;
                subscriptionStatus: import(".prisma/client").$Enums.SubscriptionStatus;
                trialStartsAt: Date | null;
                trialEndsAt: Date | null;
                subscriptionEndsAt: Date | null;
                platformMarketingOptOut: boolean;
                razorpaySubscriptionId: string | null;
                paidActivatedAt: Date | null;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
            } | null;
        } & {
            id: string;
            address: string;
            brandingProfileId: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
            taxId: string | null;
            contactPerson: string;
            mobile: string;
            costingMethod: import(".prisma/client").$Enums.CostingMethod;
            functionalCurrency: string;
        })[];
        meta: {
            nextCursor: string | null;
            limit: number;
            hasMore: boolean;
        };
    }>;
    create(user: RequestUser, dto: CreateShopDto): Promise<{
        company: {
            id: string;
            companyCode: string;
            companyName: string;
            address: string | null;
            brandingProfileId: string | null;
            isActive: boolean;
            subscriptionPlan: import(".prisma/client").$Enums.SubscriptionPlan;
            billingCycle: import(".prisma/client").$Enums.BillingCycle | null;
            subscriptionStatus: import(".prisma/client").$Enums.SubscriptionStatus;
            trialStartsAt: Date | null;
            trialEndsAt: Date | null;
            subscriptionEndsAt: Date | null;
            platformMarketingOptOut: boolean;
            razorpaySubscriptionId: string | null;
            paidActivatedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
        } | null;
    } & {
        id: string;
        address: string;
        brandingProfileId: string | null;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        email: string;
        companyId: string | null;
        shopNumber: string;
        shopName: string;
        taxId: string | null;
        contactPerson: string;
        mobile: string;
        costingMethod: import(".prisma/client").$Enums.CostingMethod;
        functionalCurrency: string;
    }>;
    get(user: RequestUser, id: string): Promise<{
        company: {
            id: string;
            companyCode: string;
            companyName: string;
            address: string | null;
            brandingProfileId: string | null;
            isActive: boolean;
            subscriptionPlan: import(".prisma/client").$Enums.SubscriptionPlan;
            billingCycle: import(".prisma/client").$Enums.BillingCycle | null;
            subscriptionStatus: import(".prisma/client").$Enums.SubscriptionStatus;
            trialStartsAt: Date | null;
            trialEndsAt: Date | null;
            subscriptionEndsAt: Date | null;
            platformMarketingOptOut: boolean;
            razorpaySubscriptionId: string | null;
            paidActivatedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
        } | null;
    } & {
        id: string;
        address: string;
        brandingProfileId: string | null;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        email: string;
        companyId: string | null;
        shopNumber: string;
        shopName: string;
        taxId: string | null;
        contactPerson: string;
        mobile: string;
        costingMethod: import(".prisma/client").$Enums.CostingMethod;
        functionalCurrency: string;
    }>;
    update(user: RequestUser, id: string, dto: UpdateShopDto): Promise<{
        company: {
            id: string;
            companyCode: string;
            companyName: string;
            address: string | null;
            brandingProfileId: string | null;
            isActive: boolean;
            subscriptionPlan: import(".prisma/client").$Enums.SubscriptionPlan;
            billingCycle: import(".prisma/client").$Enums.BillingCycle | null;
            subscriptionStatus: import(".prisma/client").$Enums.SubscriptionStatus;
            trialStartsAt: Date | null;
            trialEndsAt: Date | null;
            subscriptionEndsAt: Date | null;
            platformMarketingOptOut: boolean;
            razorpaySubscriptionId: string | null;
            paidActivatedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
        } | null;
    } & {
        id: string;
        address: string;
        brandingProfileId: string | null;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        email: string;
        companyId: string | null;
        shopNumber: string;
        shopName: string;
        taxId: string | null;
        contactPerson: string;
        mobile: string;
        costingMethod: import(".prisma/client").$Enums.CostingMethod;
        functionalCurrency: string;
    }>;
    updateBranding(user: RequestUser, id: string, dto: UpdateBrandingProfileDto, logo?: Express.Multer.File): Promise<{
        id: string;
        companyName: string | null;
        address: string | null;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        brandingVersion: number;
        logoAssetId: string | null;
        watermarkAssetId: string | null;
        sealAssetId: string | null;
        signatureAssetId: string | null;
        letterheadAssetId: string | null;
        gstNumber: string | null;
        footerText: string | null;
        email: string | null;
        phone: string | null;
        website: string | null;
        primaryColor: string | null;
        secondaryColor: string | null;
        accentColor: string | null;
    }>;
    getBranding(user: RequestUser, id: string): Promise<{
        profile: import("../../common/branding/branding.types").ResolvedBrandingProfile;
        health: {
            score: number;
            missing: string[];
        };
    }>;
    remove(user: RequestUser, id: string): Promise<{
        ok: boolean;
    }>;
}
