import type { RequestUser } from '../../common/types/request-user';
import { CreateSupplierBillDto } from './dto/create-supplier-bill.dto';
import { ListSupplierBillsDto } from './dto/list-supplier-bills.dto';
import { VoidSupplierBillDto } from './dto/void-supplier-bill.dto';
import { SupplierBillsService } from './supplier-bills.service';
export declare class SupplierBillsController {
    private readonly supplierBills;
    constructor(supplierBills: SupplierBillsService);
    list(user: RequestUser, query: ListSupplierBillsDto): Promise<{
        data: {
            shopId: string;
            supplier: {
                id: string;
                supplierCode: string;
                supplierName: string;
            };
            id: string;
            status: import(".prisma/client").$Enums.SupplierBillStatus;
            supplierId: string;
            totalValue: import("@prisma/client/runtime/library").Decimal;
            purchaseOrderId: string | null;
            paidValue: import("@prisma/client/runtime/library").Decimal;
            dueDate: Date | null;
            goodsReceiptId: string | null;
            billNumber: string;
            billDate: Date;
            purchaseOrder: {
                poNumber: string;
            } | null;
        }[];
        meta: {
            nextCursor: string | null;
            limit: number;
            hasMore: boolean;
        };
    }>;
    createFromGoodsReceipt(user: RequestUser, grId: string, dto: CreateSupplierBillDto): Promise<{
        supplier: {
            deletedAt: Date | null;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string | null;
            phone: string | null;
            companyId: string | null;
            taxId: string | null;
            contactPerson: string | null;
            supplierCode: string;
            supplierName: string;
            vatNumber: string | null;
            rating: number;
            categories: string[];
            street: string | null;
            city: string | null;
            state: string | null;
            postalCode: string | null;
            country: string | null;
            paymentTerms: string | null;
            bankName: string | null;
            accountNumber: string | null;
            routingNumber: string | null;
            iban: string | null;
        };
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: import("@prisma/client/runtime/library").Decimal;
                purchasePrice: import("@prisma/client/runtime/library").Decimal;
                sellingPrice: import("@prisma/client/runtime/library").Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            };
        } & {
            id: string;
            uom: string;
            productId: string;
            quantity: import("@prisma/client/runtime/library").Decimal;
            lineValue: import("@prisma/client/runtime/library").Decimal;
            unitCost: import("@prisma/client/runtime/library").Decimal;
            billHeaderId: string;
        })[];
        purchaseOrder: {
            shopId: string;
            supplier: string;
            currency: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            status: import(".prisma/client").$Enums.PurchaseOrderStatus;
            remarks: string | null;
            brandingMode: import(".prisma/client").$Enums.BrandingMode;
            brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
            templateVersion: number;
            rfqId: string | null;
            contractId: string | null;
            totalValue: import("@prisma/client/runtime/library").Decimal | null;
            poNumber: string;
            poDate: Date;
            fxRateUsed: import("@prisma/client/runtime/library").Decimal | null;
            discountAmount: import("@prisma/client/runtime/library").Decimal;
            taxAmount: import("@prisma/client/runtime/library").Decimal;
        } | null;
        goodsReceipt: {
            shopId: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            status: import(".prisma/client").$Enums.DocumentStatus;
            remarks: string | null;
            supplierName: string;
            brandingMode: import(".prisma/client").$Enums.BrandingMode;
            brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
            templateVersion: number;
            postedAt: Date | null;
            totalValue: import("@prisma/client/runtime/library").Decimal | null;
            grNumber: string;
            grDate: Date;
            purchaseOrderId: string | null;
            receiptType: import(".prisma/client").$Enums.ReceiptType;
            receiptSource: import(".prisma/client").$Enums.ReceiptSource;
            inwardShift: import(".prisma/client").$Enums.InwardShift | null;
            supplierRef: string | null;
        } | null;
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.SupplierBillStatus;
        supplierId: string;
        remarks: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
        templateVersion: number;
        totalValue: import("@prisma/client/runtime/library").Decimal;
        purchaseOrderId: string | null;
        paidValue: import("@prisma/client/runtime/library").Decimal;
        dueDate: Date | null;
        goodsReceiptId: string | null;
        billNumber: string;
        billDate: Date;
    }>;
    get(user: RequestUser, id: string): Promise<{
        supplier: {
            deletedAt: Date | null;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string | null;
            phone: string | null;
            companyId: string | null;
            taxId: string | null;
            contactPerson: string | null;
            supplierCode: string;
            supplierName: string;
            vatNumber: string | null;
            rating: number;
            categories: string[];
            street: string | null;
            city: string | null;
            state: string | null;
            postalCode: string | null;
            country: string | null;
            paymentTerms: string | null;
            bankName: string | null;
            accountNumber: string | null;
            routingNumber: string | null;
            iban: string | null;
        };
        payments: {
            shopId: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            method: string | null;
            remarks: string | null;
            brandingMode: import(".prisma/client").$Enums.BrandingMode;
            brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
            templateVersion: number;
            amount: import("@prisma/client/runtime/library").Decimal;
            reference: string | null;
            paymentNumber: string;
            paymentDate: Date;
            supplierBillId: string;
        }[];
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: import("@prisma/client/runtime/library").Decimal;
                purchasePrice: import("@prisma/client/runtime/library").Decimal;
                sellingPrice: import("@prisma/client/runtime/library").Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            };
        } & {
            id: string;
            uom: string;
            productId: string;
            quantity: import("@prisma/client/runtime/library").Decimal;
            lineValue: import("@prisma/client/runtime/library").Decimal;
            unitCost: import("@prisma/client/runtime/library").Decimal;
            billHeaderId: string;
        })[];
        purchaseOrder: {
            shopId: string;
            supplier: string;
            currency: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            status: import(".prisma/client").$Enums.PurchaseOrderStatus;
            remarks: string | null;
            brandingMode: import(".prisma/client").$Enums.BrandingMode;
            brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
            templateVersion: number;
            rfqId: string | null;
            contractId: string | null;
            totalValue: import("@prisma/client/runtime/library").Decimal | null;
            poNumber: string;
            poDate: Date;
            fxRateUsed: import("@prisma/client/runtime/library").Decimal | null;
            discountAmount: import("@prisma/client/runtime/library").Decimal;
            taxAmount: import("@prisma/client/runtime/library").Decimal;
        } | null;
        goodsReceipt: {
            shopId: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            status: import(".prisma/client").$Enums.DocumentStatus;
            remarks: string | null;
            supplierName: string;
            brandingMode: import(".prisma/client").$Enums.BrandingMode;
            brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
            templateVersion: number;
            postedAt: Date | null;
            totalValue: import("@prisma/client/runtime/library").Decimal | null;
            grNumber: string;
            grDate: Date;
            purchaseOrderId: string | null;
            receiptType: import(".prisma/client").$Enums.ReceiptType;
            receiptSource: import(".prisma/client").$Enums.ReceiptSource;
            inwardShift: import(".prisma/client").$Enums.InwardShift | null;
            supplierRef: string | null;
        } | null;
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.SupplierBillStatus;
        supplierId: string;
        remarks: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
        templateVersion: number;
        totalValue: import("@prisma/client/runtime/library").Decimal;
        purchaseOrderId: string | null;
        paidValue: import("@prisma/client/runtime/library").Decimal;
        dueDate: Date | null;
        goodsReceiptId: string | null;
        billNumber: string;
        billDate: Date;
    }>;
    voidBill(user: RequestUser, id: string, dto: VoidSupplierBillDto): Promise<{
        supplier: {
            deletedAt: Date | null;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string | null;
            phone: string | null;
            companyId: string | null;
            taxId: string | null;
            contactPerson: string | null;
            supplierCode: string;
            supplierName: string;
            vatNumber: string | null;
            rating: number;
            categories: string[];
            street: string | null;
            city: string | null;
            state: string | null;
            postalCode: string | null;
            country: string | null;
            paymentTerms: string | null;
            bankName: string | null;
            accountNumber: string | null;
            routingNumber: string | null;
            iban: string | null;
        };
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: import("@prisma/client/runtime/library").Decimal;
                purchasePrice: import("@prisma/client/runtime/library").Decimal;
                sellingPrice: import("@prisma/client/runtime/library").Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            };
        } & {
            id: string;
            uom: string;
            productId: string;
            quantity: import("@prisma/client/runtime/library").Decimal;
            lineValue: import("@prisma/client/runtime/library").Decimal;
            unitCost: import("@prisma/client/runtime/library").Decimal;
            billHeaderId: string;
        })[];
        purchaseOrder: {
            shopId: string;
            supplier: string;
            currency: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            status: import(".prisma/client").$Enums.PurchaseOrderStatus;
            remarks: string | null;
            brandingMode: import(".prisma/client").$Enums.BrandingMode;
            brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
            templateVersion: number;
            rfqId: string | null;
            contractId: string | null;
            totalValue: import("@prisma/client/runtime/library").Decimal | null;
            poNumber: string;
            poDate: Date;
            fxRateUsed: import("@prisma/client/runtime/library").Decimal | null;
            discountAmount: import("@prisma/client/runtime/library").Decimal;
            taxAmount: import("@prisma/client/runtime/library").Decimal;
        } | null;
        goodsReceipt: {
            shopId: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            status: import(".prisma/client").$Enums.DocumentStatus;
            remarks: string | null;
            supplierName: string;
            brandingMode: import(".prisma/client").$Enums.BrandingMode;
            brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
            templateVersion: number;
            postedAt: Date | null;
            totalValue: import("@prisma/client/runtime/library").Decimal | null;
            grNumber: string;
            grDate: Date;
            purchaseOrderId: string | null;
            receiptType: import(".prisma/client").$Enums.ReceiptType;
            receiptSource: import(".prisma/client").$Enums.ReceiptSource;
            inwardShift: import(".prisma/client").$Enums.InwardShift | null;
            supplierRef: string | null;
        } | null;
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.SupplierBillStatus;
        supplierId: string;
        remarks: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
        templateVersion: number;
        totalValue: import("@prisma/client/runtime/library").Decimal;
        purchaseOrderId: string | null;
        paidValue: import("@prisma/client/runtime/library").Decimal;
        dueDate: Date | null;
        goodsReceiptId: string | null;
        billNumber: string;
        billDate: Date;
    }>;
    send(user: RequestUser, id: string, resend?: string): Promise<import("../document-email/document-email.types").DocumentEmailSendResult>;
}
