import { Prisma, SupplierBillStatus } from '@prisma/client';
import { PrismaService } from '../../prisma/prisma.service';
import type { RequestUser } from '../../common/types/request-user';
import { AuditService } from '../audit/audit.service';
import { DocumentNumberService } from '../stock/document-number.service';
import { CreateSupplierBillDto } from './dto/create-supplier-bill.dto';
import { EmailNotificationsService } from '../email-notifications/email-notifications.service';
import { DocumentEmailService } from '../document-email/document-email.service';
import { VoidSupplierBillDto } from './dto/void-supplier-bill.dto';
export type SupplierBillListQuery = {
    shop_id?: string;
    status?: SupplierBillStatus;
    supplier_id?: string;
    date_from?: string;
    date_to?: string;
    cursor?: string;
    take?: number;
};
export declare class SupplierBillsService {
    private readonly prisma;
    private readonly audit;
    private readonly numbers;
    private readonly emailNotifications;
    private readonly documentEmail;
    constructor(prisma: PrismaService, audit: AuditService, numbers: DocumentNumberService, emailNotifications: EmailNotificationsService, documentEmail: DocumentEmailService);
    list(user: RequestUser, query?: SupplierBillListQuery): Promise<{
        data: {
            shopId: string;
            supplier: {
                id: string;
                supplierCode: string;
                supplierName: string;
            };
            id: string;
            status: import(".prisma/client").$Enums.SupplierBillStatus;
            supplierId: string;
            totalValue: Prisma.Decimal;
            purchaseOrderId: string | null;
            paidValue: Prisma.Decimal;
            dueDate: Date | null;
            goodsReceiptId: string | null;
            billNumber: string;
            billDate: Date;
            purchaseOrder: {
                poNumber: string;
            } | null;
        }[];
        meta: {
            nextCursor: string | null;
            limit: number;
            hasMore: boolean;
        };
    }>;
    get(user: RequestUser, id: string): Promise<{
        supplier: {
            deletedAt: Date | null;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string | null;
            phone: string | null;
            companyId: string | null;
            taxId: string | null;
            contactPerson: string | null;
            supplierCode: string;
            supplierName: string;
            vatNumber: string | null;
            rating: number;
            categories: string[];
            street: string | null;
            city: string | null;
            state: string | null;
            postalCode: string | null;
            country: string | null;
            paymentTerms: string | null;
            bankName: string | null;
            accountNumber: string | null;
            routingNumber: string | null;
            iban: string | null;
        };
        payments: {
            shopId: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            method: string | null;
            remarks: string | null;
            brandingMode: import(".prisma/client").$Enums.BrandingMode;
            brandingSnapshot: Prisma.JsonValue | null;
            templateVersion: number;
            amount: Prisma.Decimal;
            reference: string | null;
            paymentNumber: string;
            paymentDate: Date;
            supplierBillId: string;
        }[];
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: Prisma.Decimal;
                purchasePrice: Prisma.Decimal;
                sellingPrice: Prisma.Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            };
        } & {
            id: string;
            uom: string;
            productId: string;
            quantity: Prisma.Decimal;
            lineValue: Prisma.Decimal;
            unitCost: Prisma.Decimal;
            billHeaderId: string;
        })[];
        purchaseOrder: {
            shopId: string;
            supplier: string;
            currency: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            status: import(".prisma/client").$Enums.PurchaseOrderStatus;
            remarks: string | null;
            brandingMode: import(".prisma/client").$Enums.BrandingMode;
            brandingSnapshot: Prisma.JsonValue | null;
            templateVersion: number;
            rfqId: string | null;
            contractId: string | null;
            totalValue: Prisma.Decimal | null;
            poNumber: string;
            poDate: Date;
            fxRateUsed: Prisma.Decimal | null;
            discountAmount: Prisma.Decimal;
            taxAmount: Prisma.Decimal;
        } | null;
        goodsReceipt: {
            shopId: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            status: import(".prisma/client").$Enums.DocumentStatus;
            remarks: string | null;
            supplierName: string;
            brandingMode: import(".prisma/client").$Enums.BrandingMode;
            brandingSnapshot: Prisma.JsonValue | null;
            templateVersion: number;
            postedAt: Date | null;
            totalValue: Prisma.Decimal | null;
            grNumber: string;
            grDate: Date;
            purchaseOrderId: string | null;
            receiptType: import(".prisma/client").$Enums.ReceiptType;
            receiptSource: import(".prisma/client").$Enums.ReceiptSource;
            inwardShift: import(".prisma/client").$Enums.InwardShift | null;
            supplierRef: string | null;
        } | null;
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.SupplierBillStatus;
        supplierId: string;
        remarks: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: Prisma.JsonValue | null;
        templateVersion: number;
        totalValue: Prisma.Decimal;
        purchaseOrderId: string | null;
        paidValue: Prisma.Decimal;
        dueDate: Date | null;
        goodsReceiptId: string | null;
        billNumber: string;
        billDate: Date;
    }>;
    createFromGoodsReceipt(user: RequestUser, goodsReceiptId: string, dto?: CreateSupplierBillDto): Promise<{
        supplier: {
            deletedAt: Date | null;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string | null;
            phone: string | null;
            companyId: string | null;
            taxId: string | null;
            contactPerson: string | null;
            supplierCode: string;
            supplierName: string;
            vatNumber: string | null;
            rating: number;
            categories: string[];
            street: string | null;
            city: string | null;
            state: string | null;
            postalCode: string | null;
            country: string | null;
            paymentTerms: string | null;
            bankName: string | null;
            accountNumber: string | null;
            routingNumber: string | null;
            iban: string | null;
        };
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: Prisma.Decimal;
                purchasePrice: Prisma.Decimal;
                sellingPrice: Prisma.Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            };
        } & {
            id: string;
            uom: string;
            productId: string;
            quantity: Prisma.Decimal;
            lineValue: Prisma.Decimal;
            unitCost: Prisma.Decimal;
            billHeaderId: string;
        })[];
        purchaseOrder: {
            shopId: string;
            supplier: string;
            currency: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            status: import(".prisma/client").$Enums.PurchaseOrderStatus;
            remarks: string | null;
            brandingMode: import(".prisma/client").$Enums.BrandingMode;
            brandingSnapshot: Prisma.JsonValue | null;
            templateVersion: number;
            rfqId: string | null;
            contractId: string | null;
            totalValue: Prisma.Decimal | null;
            poNumber: string;
            poDate: Date;
            fxRateUsed: Prisma.Decimal | null;
            discountAmount: Prisma.Decimal;
            taxAmount: Prisma.Decimal;
        } | null;
        goodsReceipt: {
            shopId: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            status: import(".prisma/client").$Enums.DocumentStatus;
            remarks: string | null;
            supplierName: string;
            brandingMode: import(".prisma/client").$Enums.BrandingMode;
            brandingSnapshot: Prisma.JsonValue | null;
            templateVersion: number;
            postedAt: Date | null;
            totalValue: Prisma.Decimal | null;
            grNumber: string;
            grDate: Date;
            purchaseOrderId: string | null;
            receiptType: import(".prisma/client").$Enums.ReceiptType;
            receiptSource: import(".prisma/client").$Enums.ReceiptSource;
            inwardShift: import(".prisma/client").$Enums.InwardShift | null;
            supplierRef: string | null;
        } | null;
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.SupplierBillStatus;
        supplierId: string;
        remarks: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: Prisma.JsonValue | null;
        templateVersion: number;
        totalValue: Prisma.Decimal;
        purchaseOrderId: string | null;
        paidValue: Prisma.Decimal;
        dueDate: Date | null;
        goodsReceiptId: string | null;
        billNumber: string;
        billDate: Date;
    }>;
    sendToSupplier(user: RequestUser, id: string, options?: {
        resend?: boolean;
    }): Promise<import("../document-email/document-email.types").DocumentEmailSendResult>;
    voidBill(user: RequestUser, id: string, dto?: VoidSupplierBillDto): Promise<{
        supplier: {
            deletedAt: Date | null;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string | null;
            phone: string | null;
            companyId: string | null;
            taxId: string | null;
            contactPerson: string | null;
            supplierCode: string;
            supplierName: string;
            vatNumber: string | null;
            rating: number;
            categories: string[];
            street: string | null;
            city: string | null;
            state: string | null;
            postalCode: string | null;
            country: string | null;
            paymentTerms: string | null;
            bankName: string | null;
            accountNumber: string | null;
            routingNumber: string | null;
            iban: string | null;
        };
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: Prisma.Decimal;
                purchasePrice: Prisma.Decimal;
                sellingPrice: Prisma.Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            };
        } & {
            id: string;
            uom: string;
            productId: string;
            quantity: Prisma.Decimal;
            lineValue: Prisma.Decimal;
            unitCost: Prisma.Decimal;
            billHeaderId: string;
        })[];
        purchaseOrder: {
            shopId: string;
            supplier: string;
            currency: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            status: import(".prisma/client").$Enums.PurchaseOrderStatus;
            remarks: string | null;
            brandingMode: import(".prisma/client").$Enums.BrandingMode;
            brandingSnapshot: Prisma.JsonValue | null;
            templateVersion: number;
            rfqId: string | null;
            contractId: string | null;
            totalValue: Prisma.Decimal | null;
            poNumber: string;
            poDate: Date;
            fxRateUsed: Prisma.Decimal | null;
            discountAmount: Prisma.Decimal;
            taxAmount: Prisma.Decimal;
        } | null;
        goodsReceipt: {
            shopId: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            status: import(".prisma/client").$Enums.DocumentStatus;
            remarks: string | null;
            supplierName: string;
            brandingMode: import(".prisma/client").$Enums.BrandingMode;
            brandingSnapshot: Prisma.JsonValue | null;
            templateVersion: number;
            postedAt: Date | null;
            totalValue: Prisma.Decimal | null;
            grNumber: string;
            grDate: Date;
            purchaseOrderId: string | null;
            receiptType: import(".prisma/client").$Enums.ReceiptType;
            receiptSource: import(".prisma/client").$Enums.ReceiptSource;
            inwardShift: import(".prisma/client").$Enums.InwardShift | null;
            supplierRef: string | null;
        } | null;
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.SupplierBillStatus;
        supplierId: string;
        remarks: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: Prisma.JsonValue | null;
        templateVersion: number;
        totalValue: Prisma.Decimal;
        purchaseOrderId: string | null;
        paidValue: Prisma.Decimal;
        dueDate: Date | null;
        goodsReceiptId: string | null;
        billNumber: string;
        billDate: Date;
    }>;
    private buildSupplierBillEmailContent;
    private autoSendSupplierBillEmail;
}
