import type { RequestUser } from '../../common/types/request-user';
import { CreateDamagedStockDto } from './dto/create-damaged-stock.dto';
import { UpdateDamagedStockDto } from './dto/update-damaged-stock.dto';
import { DamagedStockService } from './damaged-stock.service';
export declare class DamagedStockController {
    private readonly service;
    constructor(service: DamagedStockService);
    list(user: RequestUser, shopId?: string, cursor?: string, take?: string): Promise<{
        data: ({
            shop: {
                id: string;
                address: string;
                brandingProfileId: string | null;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                email: string;
                companyId: string | null;
                shopNumber: string;
                shopName: string;
                taxId: string | null;
                contactPerson: string;
                mobile: string;
                costingMethod: import(".prisma/client").$Enums.CostingMethod;
                functionalCurrency: string;
            };
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: import("@prisma/client/runtime/library").Decimal;
                purchasePrice: import("@prisma/client/runtime/library").Decimal;
                sellingPrice: import("@prisma/client/runtime/library").Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            };
        } & {
            shopId: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            status: import(".prisma/client").$Enums.DocumentStatus;
            productId: string;
            remarks: string | null;
            postedAt: Date | null;
            damageNumber: string;
            damageDate: Date;
            damagedQuantity: import("@prisma/client/runtime/library").Decimal;
            reason: string;
        })[];
        meta: {
            nextCursor: string | null;
            limit: number;
            hasMore: boolean;
        };
    }>;
    create(user: RequestUser, dto: CreateDamagedStockDto): Promise<{
        shop: {
            id: string;
            address: string;
            brandingProfileId: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
            taxId: string | null;
            contactPerson: string;
            mobile: string;
            costingMethod: import(".prisma/client").$Enums.CostingMethod;
            functionalCurrency: string;
        };
        product: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            description: string;
            productCode: string;
            uom: string;
            category: string;
            hsnCode: string | null;
            materialGroup: string | null;
            drawingReference: string | null;
            brand: string | null;
            taxPreference: import(".prisma/client").$Enums.TaxPreference;
            gstRate: import("@prisma/client/runtime/library").Decimal;
            purchasePrice: import("@prisma/client/runtime/library").Decimal;
            sellingPrice: import("@prisma/client/runtime/library").Decimal;
            imageUrl: string | null;
            thumbnailUrl: string | null;
        };
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.DocumentStatus;
        productId: string;
        remarks: string | null;
        postedAt: Date | null;
        damageNumber: string;
        damageDate: Date;
        damagedQuantity: import("@prisma/client/runtime/library").Decimal;
        reason: string;
    }>;
    print(user: RequestUser, id: string): Promise<string>;
    get(user: RequestUser, id: string): Promise<{
        shop: {
            id: string;
            address: string;
            brandingProfileId: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
            taxId: string | null;
            contactPerson: string;
            mobile: string;
            costingMethod: import(".prisma/client").$Enums.CostingMethod;
            functionalCurrency: string;
        };
        product: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            description: string;
            productCode: string;
            uom: string;
            category: string;
            hsnCode: string | null;
            materialGroup: string | null;
            drawingReference: string | null;
            brand: string | null;
            taxPreference: import(".prisma/client").$Enums.TaxPreference;
            gstRate: import("@prisma/client/runtime/library").Decimal;
            purchasePrice: import("@prisma/client/runtime/library").Decimal;
            sellingPrice: import("@prisma/client/runtime/library").Decimal;
            imageUrl: string | null;
            thumbnailUrl: string | null;
        };
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.DocumentStatus;
        productId: string;
        remarks: string | null;
        postedAt: Date | null;
        damageNumber: string;
        damageDate: Date;
        damagedQuantity: import("@prisma/client/runtime/library").Decimal;
        reason: string;
    }>;
    update(user: RequestUser, id: string, dto: UpdateDamagedStockDto): Promise<{
        shop: {
            id: string;
            address: string;
            brandingProfileId: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
            taxId: string | null;
            contactPerson: string;
            mobile: string;
            costingMethod: import(".prisma/client").$Enums.CostingMethod;
            functionalCurrency: string;
        };
        product: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            description: string;
            productCode: string;
            uom: string;
            category: string;
            hsnCode: string | null;
            materialGroup: string | null;
            drawingReference: string | null;
            brand: string | null;
            taxPreference: import(".prisma/client").$Enums.TaxPreference;
            gstRate: import("@prisma/client/runtime/library").Decimal;
            purchasePrice: import("@prisma/client/runtime/library").Decimal;
            sellingPrice: import("@prisma/client/runtime/library").Decimal;
            imageUrl: string | null;
            thumbnailUrl: string | null;
        };
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.DocumentStatus;
        productId: string;
        remarks: string | null;
        postedAt: Date | null;
        damageNumber: string;
        damageDate: Date;
        damagedQuantity: import("@prisma/client/runtime/library").Decimal;
        reason: string;
    }>;
    post(user: RequestUser, id: string): Promise<{
        shop: {
            id: string;
            address: string;
            brandingProfileId: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
            taxId: string | null;
            contactPerson: string;
            mobile: string;
            costingMethod: import(".prisma/client").$Enums.CostingMethod;
            functionalCurrency: string;
        };
        product: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            description: string;
            productCode: string;
            uom: string;
            category: string;
            hsnCode: string | null;
            materialGroup: string | null;
            drawingReference: string | null;
            brand: string | null;
            taxPreference: import(".prisma/client").$Enums.TaxPreference;
            gstRate: import("@prisma/client/runtime/library").Decimal;
            purchasePrice: import("@prisma/client/runtime/library").Decimal;
            sellingPrice: import("@prisma/client/runtime/library").Decimal;
            imageUrl: string | null;
            thumbnailUrl: string | null;
        };
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.DocumentStatus;
        productId: string;
        remarks: string | null;
        postedAt: Date | null;
        damageNumber: string;
        damageDate: Date;
        damagedQuantity: import("@prisma/client/runtime/library").Decimal;
        reason: string;
    }>;
}
