import { Prisma } from '@prisma/client';
import { PrismaService } from '../../prisma/prisma.service';
import type { RequestUser } from '../../common/types/request-user';
import { DocumentNumberService } from '../stock/document-number.service';
import { StockService } from '../stock/stock.service';
import { AuditService } from '../audit/audit.service';
export declare class DamagedStockService {
    private readonly prisma;
    private readonly stock;
    private readonly numbers;
    private readonly audit;
    constructor(prisma: PrismaService, stock: StockService, numbers: DocumentNumberService, audit: AuditService);
    private available;
    list(user: RequestUser, query: {
        shop_id?: string;
        cursor?: string;
        take?: number;
    }): Promise<{
        data: ({
            shop: {
                id: string;
                address: string;
                brandingProfileId: string | null;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                email: string;
                companyId: string | null;
                shopNumber: string;
                shopName: string;
                taxId: string | null;
                contactPerson: string;
                mobile: string;
                costingMethod: import(".prisma/client").$Enums.CostingMethod;
                functionalCurrency: string;
            };
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: Prisma.Decimal;
                purchasePrice: Prisma.Decimal;
                sellingPrice: Prisma.Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            };
        } & {
            shopId: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            status: import(".prisma/client").$Enums.DocumentStatus;
            productId: string;
            remarks: string | null;
            postedAt: Date | null;
            damageNumber: string;
            damageDate: Date;
            damagedQuantity: Prisma.Decimal;
            reason: string;
        })[];
        meta: {
            nextCursor: string | null;
            limit: number;
            hasMore: boolean;
        };
    }>;
    create(user: RequestUser, dto: {
        damageDate: string;
        shopId: string;
        productId: string;
        damagedQuantity: number;
        reason: string;
        remarks?: string;
    }): Promise<{
        shop: {
            id: string;
            address: string;
            brandingProfileId: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
            taxId: string | null;
            contactPerson: string;
            mobile: string;
            costingMethod: import(".prisma/client").$Enums.CostingMethod;
            functionalCurrency: string;
        };
        product: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            description: string;
            productCode: string;
            uom: string;
            category: string;
            hsnCode: string | null;
            materialGroup: string | null;
            drawingReference: string | null;
            brand: string | null;
            taxPreference: import(".prisma/client").$Enums.TaxPreference;
            gstRate: Prisma.Decimal;
            purchasePrice: Prisma.Decimal;
            sellingPrice: Prisma.Decimal;
            imageUrl: string | null;
            thumbnailUrl: string | null;
        };
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.DocumentStatus;
        productId: string;
        remarks: string | null;
        postedAt: Date | null;
        damageNumber: string;
        damageDate: Date;
        damagedQuantity: Prisma.Decimal;
        reason: string;
    }>;
    get(user: RequestUser, id: string): Promise<{
        shop: {
            id: string;
            address: string;
            brandingProfileId: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
            taxId: string | null;
            contactPerson: string;
            mobile: string;
            costingMethod: import(".prisma/client").$Enums.CostingMethod;
            functionalCurrency: string;
        };
        product: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            description: string;
            productCode: string;
            uom: string;
            category: string;
            hsnCode: string | null;
            materialGroup: string | null;
            drawingReference: string | null;
            brand: string | null;
            taxPreference: import(".prisma/client").$Enums.TaxPreference;
            gstRate: Prisma.Decimal;
            purchasePrice: Prisma.Decimal;
            sellingPrice: Prisma.Decimal;
            imageUrl: string | null;
            thumbnailUrl: string | null;
        };
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.DocumentStatus;
        productId: string;
        remarks: string | null;
        postedAt: Date | null;
        damageNumber: string;
        damageDate: Date;
        damagedQuantity: Prisma.Decimal;
        reason: string;
    }>;
    update(user: RequestUser, id: string, dto: Partial<{
        damageDate: string;
        shopId: string;
        productId: string;
        damagedQuantity: number;
        reason: string;
        remarks?: string;
    }>): Promise<{
        shop: {
            id: string;
            address: string;
            brandingProfileId: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
            taxId: string | null;
            contactPerson: string;
            mobile: string;
            costingMethod: import(".prisma/client").$Enums.CostingMethod;
            functionalCurrency: string;
        };
        product: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            description: string;
            productCode: string;
            uom: string;
            category: string;
            hsnCode: string | null;
            materialGroup: string | null;
            drawingReference: string | null;
            brand: string | null;
            taxPreference: import(".prisma/client").$Enums.TaxPreference;
            gstRate: Prisma.Decimal;
            purchasePrice: Prisma.Decimal;
            sellingPrice: Prisma.Decimal;
            imageUrl: string | null;
            thumbnailUrl: string | null;
        };
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.DocumentStatus;
        productId: string;
        remarks: string | null;
        postedAt: Date | null;
        damageNumber: string;
        damageDate: Date;
        damagedQuantity: Prisma.Decimal;
        reason: string;
    }>;
    post(user: RequestUser, id: string): Promise<{
        shop: {
            id: string;
            address: string;
            brandingProfileId: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
            taxId: string | null;
            contactPerson: string;
            mobile: string;
            costingMethod: import(".prisma/client").$Enums.CostingMethod;
            functionalCurrency: string;
        };
        product: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            description: string;
            productCode: string;
            uom: string;
            category: string;
            hsnCode: string | null;
            materialGroup: string | null;
            drawingReference: string | null;
            brand: string | null;
            taxPreference: import(".prisma/client").$Enums.TaxPreference;
            gstRate: Prisma.Decimal;
            purchasePrice: Prisma.Decimal;
            sellingPrice: Prisma.Decimal;
            imageUrl: string | null;
            thumbnailUrl: string | null;
        };
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.DocumentStatus;
        productId: string;
        remarks: string | null;
        postedAt: Date | null;
        damageNumber: string;
        damageDate: Date;
        damagedQuantity: Prisma.Decimal;
        reason: string;
    }>;
    print(user: RequestUser, id: string): Promise<string>;
}
