ALTER TABLE ai_usage_logs
  ADD COLUMN IF NOT EXISTS tool_call_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tool_rounds      INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS duration_ms      INTEGER,
  ADD COLUMN IF NOT EXISTS timed_out        BOOLEAN NOT NULL DEFAULT FALSE;
