import type { RequestUser } from '../types/request-user';
import { PrismaService } from '../../prisma/prisma.service';
import { BrandingResolverService } from '../branding/branding-resolver.service';
import { type DocumentPdfKind, type DocumentPdfRenderResult } from './document-pdf.types';
export declare class DocumentPdfService {
    private readonly prisma;
    private readonly branding;
    constructor(prisma: PrismaService, branding: BrandingResolverService);
    private shopNameForId;
    private buildSnapshot;
    private persistSnapshot;
    private applyBranding;
    private assertCanRead;
    assertDocumentAccess(user: RequestUser, kind: DocumentPdfKind, id: string): Promise<void>;
    renderPdf(user: RequestUser, kind: DocumentPdfKind, id: string): Promise<DocumentPdfRenderResult>;
    renderPurchaseOrderPdf(user: RequestUser, id: string): Promise<DocumentPdfRenderResult>;
    renderInvoicePdf(user: RequestUser, id: string): Promise<DocumentPdfRenderResult>;
    renderSalesOrderPdf(user: RequestUser, id: string): Promise<DocumentPdfRenderResult>;
    renderSupplierBillPdf(user: RequestUser, id: string): Promise<DocumentPdfRenderResult>;
    renderSupplierPaymentPdf(user: RequestUser, id: string): Promise<DocumentPdfRenderResult>;
    renderPaymentReceiptPdf(user: RequestUser, id: string): Promise<DocumentPdfRenderResult>;
    renderPurchaseOrderPdfById(id: string): Promise<DocumentPdfRenderResult>;
    renderInvoicePdfById(id: string): Promise<DocumentPdfRenderResult>;
    renderSalesOrderPdfById(id: string): Promise<DocumentPdfRenderResult>;
    renderSupplierBillPdfById(id: string): Promise<DocumentPdfRenderResult>;
    renderSupplierPaymentPdfById(id: string): Promise<DocumentPdfRenderResult>;
    renderPaymentReceiptPdfById(id: string): Promise<DocumentPdfRenderResult>;
    renderGoodsReceiptPdf(user: RequestUser, id: string): Promise<DocumentPdfRenderResult>;
    renderGoodsIssuePdf(user: RequestUser, id: string): Promise<DocumentPdfRenderResult>;
    renderGoodsReturnPdf(user: RequestUser, id: string): Promise<DocumentPdfRenderResult>;
    renderSalesQuotationPdf(user: RequestUser, id: string): Promise<DocumentPdfRenderResult>;
    renderGoodsReceiptPdfById(id: string): Promise<DocumentPdfRenderResult>;
    renderGoodsIssuePdfById(id: string): Promise<DocumentPdfRenderResult>;
    renderGoodsReturnPdfById(id: string): Promise<DocumentPdfRenderResult>;
    renderSalesQuotationPdfById(id: string): Promise<DocumentPdfRenderResult>;
    buildPurchaseOrderPrintHtml(user: RequestUser, id: string): Promise<string>;
    private sleep;
    renderWithRetry(renderFn: () => Promise<DocumentPdfRenderResult>, maxAttempts?: number, delayMs?: number): Promise<DocumentPdfRenderResult>;
    renderPurchaseOrderPdfByIdWithRetry(id: string, maxAttempts?: number, delayMs?: number): Promise<DocumentPdfRenderResult>;
    renderInvoicePdfByIdWithRetry(id: string, maxAttempts?: number, delayMs?: number): Promise<DocumentPdfRenderResult>;
    renderSalesOrderPdfByIdWithRetry(id: string, maxAttempts?: number, delayMs?: number): Promise<DocumentPdfRenderResult>;
    renderSupplierBillPdfByIdWithRetry(id: string, maxAttempts?: number, delayMs?: number): Promise<DocumentPdfRenderResult>;
    renderSupplierPaymentPdfByIdWithRetry(id: string, maxAttempts?: number, delayMs?: number): Promise<DocumentPdfRenderResult>;
    renderPaymentReceiptPdfByIdWithRetry(id: string, maxAttempts?: number, delayMs?: number): Promise<DocumentPdfRenderResult>;
    renderGoodsReceiptPdfByIdWithRetry(id: string, maxAttempts?: number, delayMs?: number): Promise<DocumentPdfRenderResult>;
    renderGoodsReturnPdfByIdWithRetry(id: string, maxAttempts?: number, delayMs?: number): Promise<DocumentPdfRenderResult>;
    renderSalesQuotationPdfByIdWithRetry(id: string, maxAttempts?: number, delayMs?: number): Promise<DocumentPdfRenderResult>;
}
