import { Prisma } from '@prisma/client';
import { PrismaService } from '../../prisma/prisma.service';
import type { RequestUser } from '../../common/types/request-user';
import { AuditService } from '../audit/audit.service';
import { DocumentNumberService } from '../stock/document-number.service';
import { CreatePaymentDto } from './dto/create-payment.dto';
import { SubscriptionService } from '../billing/subscription.service';
import { EmailNotificationsService } from '../email-notifications/email-notifications.service';
import { DocumentEmailService } from '../document-email/document-email.service';
export declare class PaymentsService {
    private readonly prisma;
    private readonly audit;
    private readonly numbers;
    private readonly subscriptions;
    private readonly emailNotifications;
    private readonly documentEmail;
    constructor(prisma: PrismaService, audit: AuditService, numbers: DocumentNumberService, subscriptions: SubscriptionService, emailNotifications: EmailNotificationsService, documentEmail: DocumentEmailService);
    list(user: RequestUser, query?: {
        cursor?: string;
        take?: number;
        invoice_id?: string;
    }): Promise<{
        data: {
            shopId: string;
            id: string;
            invoiceId: string;
            method: string | null;
            receiptNumber: string;
            receiptDate: Date;
            amount: Prisma.Decimal;
            reference: string | null;
            invoice: {
                id: string;
                invoiceNumber: string;
                totalValue: Prisma.Decimal;
                paidValue: Prisma.Decimal;
            };
        }[];
        meta: {
            nextCursor: string | null;
            limit: number;
            hasMore: boolean;
        };
    }>;
    create(user: RequestUser, dto: CreatePaymentDto): Promise<{
        shop: {
            id: string;
            address: string;
            brandingProfileId: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
            taxId: string | null;
            contactPerson: string;
            mobile: string;
            costingMethod: import(".prisma/client").$Enums.CostingMethod;
            functionalCurrency: string;
        };
        invoice: {
            shopId: string;
            currency: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            status: import(".prisma/client").$Enums.InvoiceStatus;
            invoiceNumber: string;
            remarks: string | null;
            brandingMode: import(".prisma/client").$Enums.BrandingMode;
            brandingSnapshot: Prisma.JsonValue | null;
            templateVersion: number;
            totalValue: Prisma.Decimal;
            fxRateUsed: Prisma.Decimal | null;
            discountAmount: Prisma.Decimal;
            taxAmount: Prisma.Decimal;
            customerId: string;
            salesOrderId: string | null;
            invoiceDate: Date;
            paidValue: Prisma.Decimal;
            dueDate: Date | null;
        };
    } & {
        shopId: string;
        currency: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        invoiceId: string;
        method: string | null;
        remarks: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: Prisma.JsonValue | null;
        templateVersion: number;
        fxRateUsed: Prisma.Decimal | null;
        receiptNumber: string;
        receiptDate: Date;
        amount: Prisma.Decimal;
        reference: string | null;
    }>;
    get(user: RequestUser, id: string): Promise<{
        shop: {
            id: string;
            address: string;
            brandingProfileId: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
            taxId: string | null;
            contactPerson: string;
            mobile: string;
            costingMethod: import(".prisma/client").$Enums.CostingMethod;
            functionalCurrency: string;
        };
        invoice: {
            customer: {
                shopId: string;
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                email: string | null;
                phone: string | null;
                taxId: string | null;
                street: string | null;
                city: string | null;
                state: string | null;
                postalCode: string | null;
                country: string | null;
                customerCode: string;
                customerName: string;
                pan: string | null;
            };
        } & {
            shopId: string;
            currency: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            status: import(".prisma/client").$Enums.InvoiceStatus;
            invoiceNumber: string;
            remarks: string | null;
            brandingMode: import(".prisma/client").$Enums.BrandingMode;
            brandingSnapshot: Prisma.JsonValue | null;
            templateVersion: number;
            totalValue: Prisma.Decimal;
            fxRateUsed: Prisma.Decimal | null;
            discountAmount: Prisma.Decimal;
            taxAmount: Prisma.Decimal;
            customerId: string;
            salesOrderId: string | null;
            invoiceDate: Date;
            paidValue: Prisma.Decimal;
            dueDate: Date | null;
        };
    } & {
        shopId: string;
        currency: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        invoiceId: string;
        method: string | null;
        remarks: string | null;
        brandingMode: import(".prisma/client").$Enums.BrandingMode;
        brandingSnapshot: Prisma.JsonValue | null;
        templateVersion: number;
        fxRateUsed: Prisma.Decimal | null;
        receiptNumber: string;
        receiptDate: Date;
        amount: Prisma.Decimal;
        reference: string | null;
    }>;
    sendToCustomer(user: RequestUser, id: string, options?: {
        resend?: boolean;
    }): Promise<import("../document-email/document-email.types").DocumentEmailSendResult>;
    private buildPaymentEmailContent;
    private autoSendPaymentReceivedEmail;
}
