import Redis from 'ioredis';
import { ConfigService } from '@nestjs/config';
import type { RequestUser } from '../../common/types/request-user';
import { MailService } from '../../common/mail/mail.service';
import { PrismaService } from '../../prisma/prisma.service';
import { AuditService } from '../audit/audit.service';
import { SubscriptionService } from '../billing/subscription.service';
import { CreateUserDto } from './dto/create-user.dto';
import { InviteUserDto } from './dto/invite-user.dto';
import { UpdateUserDto } from './dto/update-user.dto';
import { EmailNotificationsService } from '../email-notifications/email-notifications.service';
export declare class UsersService {
    private readonly prisma;
    private readonly config;
    private readonly audit;
    private readonly mail;
    private readonly subscriptions;
    private readonly emailNotifications;
    private readonly redis;
    constructor(prisma: PrismaService, config: ConfigService, audit: AuditService, mail: MailService, subscriptions: SubscriptionService, emailNotifications: EmailNotificationsService, redis: Redis);
    private invalidateWhatsAppAuthCache;
    private bcryptRounds;
    private isOwner;
    private isOrgAdmin;
    private isAdmin;
    private assertCanManageShop;
    private normalizeRoleName;
    private inviteTtlMs;
    private resolveRoleId;
    private assertRoleAssignable;
    listRoles(): Promise<{
        permissions: import("@prisma/client/runtime/library").JsonValue;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        name: import(".prisma/client").$Enums.RoleName;
    }[]>;
    updateRolePermissions(actor: RequestUser, roleName: string, permissions: string[]): Promise<{
        permissions: import("@prisma/client/runtime/library").JsonValue;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        name: import(".prisma/client").$Enums.RoleName;
    }>;
    private resolveShopForActor;
    list(actor: RequestUser): Promise<({
        role: {
            permissions: import("@prisma/client/runtime/library").JsonValue;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            name: import(".prisma/client").$Enums.RoleName;
        };
        shop: {
            id: string;
            address: string;
            brandingProfileId: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
            taxId: string | null;
            contactPerson: string;
            mobile: string;
            costingMethod: import(".prisma/client").$Enums.CostingMethod;
            functionalCurrency: string;
        } | null;
    } & {
        shopId: string | null;
        deletedAt: Date | null;
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        email: string;
        name: string;
        lastLoginAt: Date | null;
        roleId: string;
        passwordHash: string;
        avatarUrl: string | null;
        mfaEnabled: boolean;
        mfaMethod: import(".prisma/client").$Enums.MfaMethod | null;
        mfaEnrolledAt: Date | null;
        mfaSecretEncrypted: string | null;
        passwordChangedAt: Date | null;
        refreshTokenHash: string | null;
        failedLoginCount: number;
        lockedUntil: Date | null;
    })[]>;
    create(actor: RequestUser, dto: CreateUserDto): Promise<{
        role: {
            permissions: import("@prisma/client/runtime/library").JsonValue;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            name: import(".prisma/client").$Enums.RoleName;
        };
        shop: {
            id: string;
            address: string;
            brandingProfileId: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
            taxId: string | null;
            contactPerson: string;
            mobile: string;
            costingMethod: import(".prisma/client").$Enums.CostingMethod;
            functionalCurrency: string;
        } | null;
    } & {
        shopId: string | null;
        deletedAt: Date | null;
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        email: string;
        name: string;
        lastLoginAt: Date | null;
        roleId: string;
        passwordHash: string;
        avatarUrl: string | null;
        mfaEnabled: boolean;
        mfaMethod: import(".prisma/client").$Enums.MfaMethod | null;
        mfaEnrolledAt: Date | null;
        mfaSecretEncrypted: string | null;
        passwordChangedAt: Date | null;
        refreshTokenHash: string | null;
        failedLoginCount: number;
        lockedUntil: Date | null;
    }>;
    invite(actor: RequestUser, dto: InviteUserDto): Promise<{
        ok: boolean;
        email: string;
        expiresAt: Date;
    }>;
    get(actor: RequestUser, id: string): Promise<{
        role: {
            permissions: import("@prisma/client/runtime/library").JsonValue;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            name: import(".prisma/client").$Enums.RoleName;
        };
        shop: {
            id: string;
            address: string;
            brandingProfileId: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
            taxId: string | null;
            contactPerson: string;
            mobile: string;
            costingMethod: import(".prisma/client").$Enums.CostingMethod;
            functionalCurrency: string;
        } | null;
    } & {
        shopId: string | null;
        deletedAt: Date | null;
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        email: string;
        name: string;
        lastLoginAt: Date | null;
        roleId: string;
        passwordHash: string;
        avatarUrl: string | null;
        mfaEnabled: boolean;
        mfaMethod: import(".prisma/client").$Enums.MfaMethod | null;
        mfaEnrolledAt: Date | null;
        mfaSecretEncrypted: string | null;
        passwordChangedAt: Date | null;
        refreshTokenHash: string | null;
        failedLoginCount: number;
        lockedUntil: Date | null;
    }>;
    update(actor: RequestUser, id: string, dto: UpdateUserDto): Promise<{
        role: {
            permissions: import("@prisma/client/runtime/library").JsonValue;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            name: import(".prisma/client").$Enums.RoleName;
        };
        shop: {
            id: string;
            address: string;
            brandingProfileId: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
            taxId: string | null;
            contactPerson: string;
            mobile: string;
            costingMethod: import(".prisma/client").$Enums.CostingMethod;
            functionalCurrency: string;
        } | null;
    } & {
        shopId: string | null;
        deletedAt: Date | null;
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        email: string;
        name: string;
        lastLoginAt: Date | null;
        roleId: string;
        passwordHash: string;
        avatarUrl: string | null;
        mfaEnabled: boolean;
        mfaMethod: import(".prisma/client").$Enums.MfaMethod | null;
        mfaEnrolledAt: Date | null;
        mfaSecretEncrypted: string | null;
        passwordChangedAt: Date | null;
        refreshTokenHash: string | null;
        failedLoginCount: number;
        lockedUntil: Date | null;
    }>;
    remove(actor: RequestUser, id: string): Promise<{
        ok: boolean;
    }>;
}
