import type { RequestUser } from '../../common/types/request-user';
import { CreateUserDto } from './dto/create-user.dto';
import { InviteUserDto } from './dto/invite-user.dto';
import { UpdateRolePermissionsDto } from './dto/update-role-permissions.dto';
import { UpdateUserDto } from './dto/update-user.dto';
import { UsersService } from './users.service';
export declare class UsersController {
    private readonly users;
    constructor(users: UsersService);
    list(user: RequestUser): Promise<({
        role: {
            permissions: import("@prisma/client/runtime/library").JsonValue;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            name: import(".prisma/client").$Enums.RoleName;
        };
        shop: {
            id: string;
            address: string;
            brandingProfileId: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
            taxId: string | null;
            contactPerson: string;
            mobile: string;
            costingMethod: import(".prisma/client").$Enums.CostingMethod;
            functionalCurrency: string;
        } | null;
    } & {
        shopId: string | null;
        deletedAt: Date | null;
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        email: string;
        name: string;
        lastLoginAt: Date | null;
        roleId: string;
        passwordHash: string;
        avatarUrl: string | null;
        mfaEnabled: boolean;
        mfaMethod: import(".prisma/client").$Enums.MfaMethod | null;
        mfaEnrolledAt: Date | null;
        mfaSecretEncrypted: string | null;
        passwordChangedAt: Date | null;
        refreshTokenHash: string | null;
        failedLoginCount: number;
        lockedUntil: Date | null;
    })[]>;
    listRoles(): Promise<{
        permissions: import("@prisma/client/runtime/library").JsonValue;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        name: import(".prisma/client").$Enums.RoleName;
    }[]>;
    updateRolePermissions(user: RequestUser, roleName: string, dto: UpdateRolePermissionsDto): Promise<{
        permissions: import("@prisma/client/runtime/library").JsonValue;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        name: import(".prisma/client").$Enums.RoleName;
    }>;
    invite(user: RequestUser, dto: InviteUserDto): Promise<{
        ok: boolean;
        email: string;
        expiresAt: Date;
    }>;
    create(user: RequestUser, dto: CreateUserDto): Promise<{
        role: {
            permissions: import("@prisma/client/runtime/library").JsonValue;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            name: import(".prisma/client").$Enums.RoleName;
        };
        shop: {
            id: string;
            address: string;
            brandingProfileId: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
            taxId: string | null;
            contactPerson: string;
            mobile: string;
            costingMethod: import(".prisma/client").$Enums.CostingMethod;
            functionalCurrency: string;
        } | null;
    } & {
        shopId: string | null;
        deletedAt: Date | null;
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        email: string;
        name: string;
        lastLoginAt: Date | null;
        roleId: string;
        passwordHash: string;
        avatarUrl: string | null;
        mfaEnabled: boolean;
        mfaMethod: import(".prisma/client").$Enums.MfaMethod | null;
        mfaEnrolledAt: Date | null;
        mfaSecretEncrypted: string | null;
        passwordChangedAt: Date | null;
        refreshTokenHash: string | null;
        failedLoginCount: number;
        lockedUntil: Date | null;
    }>;
    get(user: RequestUser, id: string): Promise<{
        role: {
            permissions: import("@prisma/client/runtime/library").JsonValue;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            name: import(".prisma/client").$Enums.RoleName;
        };
        shop: {
            id: string;
            address: string;
            brandingProfileId: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
            taxId: string | null;
            contactPerson: string;
            mobile: string;
            costingMethod: import(".prisma/client").$Enums.CostingMethod;
            functionalCurrency: string;
        } | null;
    } & {
        shopId: string | null;
        deletedAt: Date | null;
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        email: string;
        name: string;
        lastLoginAt: Date | null;
        roleId: string;
        passwordHash: string;
        avatarUrl: string | null;
        mfaEnabled: boolean;
        mfaMethod: import(".prisma/client").$Enums.MfaMethod | null;
        mfaEnrolledAt: Date | null;
        mfaSecretEncrypted: string | null;
        passwordChangedAt: Date | null;
        refreshTokenHash: string | null;
        failedLoginCount: number;
        lockedUntil: Date | null;
    }>;
    update(user: RequestUser, id: string, dto: UpdateUserDto): Promise<{
        role: {
            permissions: import("@prisma/client/runtime/library").JsonValue;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            name: import(".prisma/client").$Enums.RoleName;
        };
        shop: {
            id: string;
            address: string;
            brandingProfileId: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string;
            companyId: string | null;
            shopNumber: string;
            shopName: string;
            taxId: string | null;
            contactPerson: string;
            mobile: string;
            costingMethod: import(".prisma/client").$Enums.CostingMethod;
            functionalCurrency: string;
        } | null;
    } & {
        shopId: string | null;
        deletedAt: Date | null;
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        email: string;
        name: string;
        lastLoginAt: Date | null;
        roleId: string;
        passwordHash: string;
        avatarUrl: string | null;
        mfaEnabled: boolean;
        mfaMethod: import(".prisma/client").$Enums.MfaMethod | null;
        mfaEnrolledAt: Date | null;
        mfaSecretEncrypted: string | null;
        passwordChangedAt: Date | null;
        refreshTokenHash: string | null;
        failedLoginCount: number;
        lockedUntil: Date | null;
    }>;
    remove(user: RequestUser, id: string): Promise<{
        ok: boolean;
    }>;
}
