export type InvoiceCreatedEmailContent = {
    customerName: string;
    invoiceNumber: string;
    invoiceDate: string;
    dueDate: string;
    totalAmount: string;
    companyName: string;
};
export declare function invoiceCreatedSubject(content: InvoiceCreatedEmailContent): string;
export declare function invoiceCreatedText(content: InvoiceCreatedEmailContent): string;
export declare function invoiceCreatedHtml(content: InvoiceCreatedEmailContent): string;
export type PaymentReceivedEmailContent = {
    customerName: string;
    invoiceNumber: string;
    receiptNumber: string;
    amountPaid: string;
    balanceDue: string;
    paymentType: string;
    companyName: string;
};
export declare function paymentReceivedSubject(content: PaymentReceivedEmailContent): string;
export declare function paymentReceivedText(content: PaymentReceivedEmailContent): string;
export declare function paymentReceivedHtml(content: PaymentReceivedEmailContent): string;
export type SalesOrderCustomerEmailContent = {
    customerName: string;
    soNumber: string;
    orderDate: string;
    expectedDate: string;
    totalAmount: string;
    shopName: string;
    companyName: string;
};
export declare function salesOrderCustomerSubject(content: SalesOrderCustomerEmailContent): string;
export declare function salesOrderCustomerText(content: SalesOrderCustomerEmailContent): string;
export declare function salesOrderCustomerHtml(content: SalesOrderCustomerEmailContent): string;
export type SupplierBillIssuedEmailContent = {
    supplierName: string;
    billNumber: string;
    billDate: string;
    dueDate: string;
    totalAmount: string;
    poNumber: string;
    companyName: string;
};
export declare function supplierBillIssuedSubject(content: SupplierBillIssuedEmailContent): string;
export declare function supplierBillIssuedText(content: SupplierBillIssuedEmailContent): string;
export declare function supplierBillIssuedHtml(content: SupplierBillIssuedEmailContent): string;
export type SupplierPaymentRecordedEmailContent = {
    supplierName: string;
    billNumber: string;
    paymentNumber: string;
    amountPaid: string;
    balanceDue: string;
    paymentType: string;
    companyName: string;
};
export declare function supplierPaymentRecordedSubject(content: SupplierPaymentRecordedEmailContent): string;
export declare function supplierPaymentRecordedText(content: SupplierPaymentRecordedEmailContent): string;
export declare function supplierPaymentRecordedHtml(content: SupplierPaymentRecordedEmailContent): string;
export type PaymentReminderEmailContent = {
    customerName: string;
    invoiceNumber: string;
    dueDate: string;
    daysUntilDue: string;
    balanceDue: string;
    companyName: string;
};
export declare function paymentReminderSubject(content: PaymentReminderEmailContent): string;
export declare function paymentReminderText(content: PaymentReminderEmailContent): string;
export declare function paymentReminderHtml(content: PaymentReminderEmailContent): string;
export type InternalAlertEmailContent = {
    title: string;
    message: string;
    companyName: string;
};
export type GoodsReceiptSupplierEmailContent = {
    supplierName: string;
    grNumber: string;
    grDate: string;
    shopName: string;
    totalAmount: string;
    poNumber: string;
    companyName: string;
};
export declare function goodsReceiptSupplierSubject(content: GoodsReceiptSupplierEmailContent): string;
export declare function goodsReceiptSupplierText(content: GoodsReceiptSupplierEmailContent): string;
export declare function goodsReceiptSupplierHtml(content: GoodsReceiptSupplierEmailContent): string;
export declare function internalAlertSubject(content: InternalAlertEmailContent): string;
export declare function internalAlertText(content: InternalAlertEmailContent): string;
export declare function internalAlertHtml(content: InternalAlertEmailContent): string;
