ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'VIEW_DASHBOARD';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'DASHBOARD_CARD_CLICKED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'DASHBOARD_ACTION_TAKEN';
