import type { RequestUser } from '../../common/types/request-user';
import { AcceptAutoLinkQuotationDto } from './dto/accept-auto-link-quotation.dto';
import { CreateQuotationDto } from './dto/create-quotation.dto';
import { UpdateQuotationDto } from './dto/update-quotation.dto';
import { QuotationsService } from './quotations.service';
export declare class QuotationsController {
    private readonly quotations;
    constructor(quotations: QuotationsService);
    list(user: RequestUser, rfqId?: string): Promise<({
        supplier: {
            deletedAt: Date | null;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string | null;
            phone: string | null;
            companyId: string | null;
            taxId: string | null;
            contactPerson: string | null;
            supplierCode: string;
            supplierName: string;
            vatNumber: string | null;
            rating: number;
            categories: string[];
            street: string | null;
            city: string | null;
            state: string | null;
            postalCode: string | null;
            country: string | null;
            paymentTerms: string | null;
            bankName: string | null;
            accountNumber: string | null;
            routingNumber: string | null;
            iban: string | null;
        };
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: import("@prisma/client/runtime/library").Decimal;
                purchasePrice: import("@prisma/client/runtime/library").Decimal;
                sellingPrice: import("@prisma/client/runtime/library").Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            } | null;
            rfqItem: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string | null;
                uom: string;
                productId: string | null;
                rfqHeaderId: string;
                quantity: import("@prisma/client/runtime/library").Decimal;
                specifications: string | null;
            } | null;
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            description: string | null;
            uom: string;
            productId: string | null;
            quantity: import("@prisma/client/runtime/library").Decimal;
            specifications: string | null;
            unitPrice: import("@prisma/client/runtime/library").Decimal;
            lineValue: import("@prisma/client/runtime/library").Decimal;
            quoteHeaderId: string;
            rfqItemId: string | null;
        })[];
        rfq: {
            shopId: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            status: import(".prisma/client").$Enums.DocumentStatus;
            rfqNumber: string;
            rfqDate: Date;
            deadline: Date | null;
            title: string;
            notes: string | null;
            brandingMode: import(".prisma/client").$Enums.BrandingMode;
            brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
            templateVersion: number;
            postedAt: Date | null;
        };
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.DocumentStatus;
        supplierId: string;
        notes: string | null;
        postedAt: Date | null;
        rfqId: string;
        quoteNumber: string;
        quoteDate: Date;
        totalValue: import("@prisma/client/runtime/library").Decimal | null;
    })[]>;
    create(user: RequestUser, dto: CreateQuotationDto): Promise<{
        supplier: {
            deletedAt: Date | null;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string | null;
            phone: string | null;
            companyId: string | null;
            taxId: string | null;
            contactPerson: string | null;
            supplierCode: string;
            supplierName: string;
            vatNumber: string | null;
            rating: number;
            categories: string[];
            street: string | null;
            city: string | null;
            state: string | null;
            postalCode: string | null;
            country: string | null;
            paymentTerms: string | null;
            bankName: string | null;
            accountNumber: string | null;
            routingNumber: string | null;
            iban: string | null;
        };
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: import("@prisma/client/runtime/library").Decimal;
                purchasePrice: import("@prisma/client/runtime/library").Decimal;
                sellingPrice: import("@prisma/client/runtime/library").Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            } | null;
            rfqItem: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string | null;
                uom: string;
                productId: string | null;
                rfqHeaderId: string;
                quantity: import("@prisma/client/runtime/library").Decimal;
                specifications: string | null;
            } | null;
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            description: string | null;
            uom: string;
            productId: string | null;
            quantity: import("@prisma/client/runtime/library").Decimal;
            specifications: string | null;
            unitPrice: import("@prisma/client/runtime/library").Decimal;
            lineValue: import("@prisma/client/runtime/library").Decimal;
            quoteHeaderId: string;
            rfqItemId: string | null;
        })[];
        rfq: {
            shopId: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            status: import(".prisma/client").$Enums.DocumentStatus;
            rfqNumber: string;
            rfqDate: Date;
            deadline: Date | null;
            title: string;
            notes: string | null;
            brandingMode: import(".prisma/client").$Enums.BrandingMode;
            brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
            templateVersion: number;
            postedAt: Date | null;
        };
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.DocumentStatus;
        supplierId: string;
        notes: string | null;
        postedAt: Date | null;
        rfqId: string;
        quoteNumber: string;
        quoteDate: Date;
        totalValue: import("@prisma/client/runtime/library").Decimal | null;
    }>;
    get(user: RequestUser, id: string): Promise<{
        supplier: {
            deletedAt: Date | null;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string | null;
            phone: string | null;
            companyId: string | null;
            taxId: string | null;
            contactPerson: string | null;
            supplierCode: string;
            supplierName: string;
            vatNumber: string | null;
            rating: number;
            categories: string[];
            street: string | null;
            city: string | null;
            state: string | null;
            postalCode: string | null;
            country: string | null;
            paymentTerms: string | null;
            bankName: string | null;
            accountNumber: string | null;
            routingNumber: string | null;
            iban: string | null;
        };
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: import("@prisma/client/runtime/library").Decimal;
                purchasePrice: import("@prisma/client/runtime/library").Decimal;
                sellingPrice: import("@prisma/client/runtime/library").Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            } | null;
            rfqItem: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string | null;
                uom: string;
                productId: string | null;
                rfqHeaderId: string;
                quantity: import("@prisma/client/runtime/library").Decimal;
                specifications: string | null;
            } | null;
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            description: string | null;
            uom: string;
            productId: string | null;
            quantity: import("@prisma/client/runtime/library").Decimal;
            specifications: string | null;
            unitPrice: import("@prisma/client/runtime/library").Decimal;
            lineValue: import("@prisma/client/runtime/library").Decimal;
            quoteHeaderId: string;
            rfqItemId: string | null;
        })[];
        rfq: {
            shopId: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            status: import(".prisma/client").$Enums.DocumentStatus;
            rfqNumber: string;
            rfqDate: Date;
            deadline: Date | null;
            title: string;
            notes: string | null;
            brandingMode: import(".prisma/client").$Enums.BrandingMode;
            brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
            templateVersion: number;
            postedAt: Date | null;
        };
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.DocumentStatus;
        supplierId: string;
        notes: string | null;
        postedAt: Date | null;
        rfqId: string;
        quoteNumber: string;
        quoteDate: Date;
        totalValue: import("@prisma/client/runtime/library").Decimal | null;
    }>;
    update(user: RequestUser, id: string, dto: UpdateQuotationDto): Promise<{
        supplier: {
            deletedAt: Date | null;
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            email: string | null;
            phone: string | null;
            companyId: string | null;
            taxId: string | null;
            contactPerson: string | null;
            supplierCode: string;
            supplierName: string;
            vatNumber: string | null;
            rating: number;
            categories: string[];
            street: string | null;
            city: string | null;
            state: string | null;
            postalCode: string | null;
            country: string | null;
            paymentTerms: string | null;
            bankName: string | null;
            accountNumber: string | null;
            routingNumber: string | null;
            iban: string | null;
        };
        items: ({
            product: {
                id: string;
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string;
                productCode: string;
                uom: string;
                category: string;
                hsnCode: string | null;
                materialGroup: string | null;
                drawingReference: string | null;
                brand: string | null;
                taxPreference: import(".prisma/client").$Enums.TaxPreference;
                gstRate: import("@prisma/client/runtime/library").Decimal;
                purchasePrice: import("@prisma/client/runtime/library").Decimal;
                sellingPrice: import("@prisma/client/runtime/library").Decimal;
                imageUrl: string | null;
                thumbnailUrl: string | null;
            } | null;
            rfqItem: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                createdById: string | null;
                updatedById: string | null;
                description: string | null;
                uom: string;
                productId: string | null;
                rfqHeaderId: string;
                quantity: import("@prisma/client/runtime/library").Decimal;
                specifications: string | null;
            } | null;
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            description: string | null;
            uom: string;
            productId: string | null;
            quantity: import("@prisma/client/runtime/library").Decimal;
            specifications: string | null;
            unitPrice: import("@prisma/client/runtime/library").Decimal;
            lineValue: import("@prisma/client/runtime/library").Decimal;
            quoteHeaderId: string;
            rfqItemId: string | null;
        })[];
        rfq: {
            shopId: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            status: import(".prisma/client").$Enums.DocumentStatus;
            rfqNumber: string;
            rfqDate: Date;
            deadline: Date | null;
            title: string;
            notes: string | null;
            brandingMode: import(".prisma/client").$Enums.BrandingMode;
            brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
            templateVersion: number;
            postedAt: Date | null;
        };
    } & {
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.DocumentStatus;
        supplierId: string;
        notes: string | null;
        postedAt: Date | null;
        rfqId: string;
        quoteNumber: string;
        quoteDate: Date;
        totalValue: import("@prisma/client/runtime/library").Decimal | null;
    }>;
    submit(user: RequestUser, id: string): Promise<{
        shopId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        status: import(".prisma/client").$Enums.DocumentStatus;
        supplierId: string;
        notes: string | null;
        postedAt: Date | null;
        rfqId: string;
        quoteNumber: string;
        quoteDate: Date;
        totalValue: import("@prisma/client/runtime/library").Decimal | null;
    }>;
    acceptAndAutoLink(user: RequestUser, id: string, dto: AcceptAutoLinkQuotationDto): Promise<{
        quote: {
            shopId: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            status: import(".prisma/client").$Enums.DocumentStatus;
            supplierId: string;
            notes: string | null;
            postedAt: Date | null;
            rfqId: string;
            quoteNumber: string;
            quoteDate: Date;
            totalValue: import("@prisma/client/runtime/library").Decimal | null;
        };
        contract: {
            shopId: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            status: import(".prisma/client").$Enums.DocumentStatus;
            supplierId: string;
            paymentTerms: string | null;
            title: string;
            notes: string | null;
            postedAt: Date | null;
            rfqId: string | null;
            contractNumber: string;
            quotationId: string | null;
            startDate: Date;
            endDate: Date | null;
        };
        purchaseOrder: {
            shopId: string;
            supplier: string;
            currency: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            status: import(".prisma/client").$Enums.PurchaseOrderStatus;
            remarks: string | null;
            brandingMode: import(".prisma/client").$Enums.BrandingMode;
            brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
            templateVersion: number;
            rfqId: string | null;
            contractId: string | null;
            totalValue: import("@prisma/client/runtime/library").Decimal | null;
            poNumber: string;
            poDate: Date;
            fxRateUsed: import("@prisma/client/runtime/library").Decimal | null;
            discountAmount: import("@prisma/client/runtime/library").Decimal;
            taxAmount: import("@prisma/client/runtime/library").Decimal;
        };
        goodsReceiptDraft: {
            shopId: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            status: import(".prisma/client").$Enums.DocumentStatus;
            remarks: string | null;
            supplierName: string;
            brandingMode: import(".prisma/client").$Enums.BrandingMode;
            brandingSnapshot: import("@prisma/client/runtime/library").JsonValue | null;
            templateVersion: number;
            postedAt: Date | null;
            totalValue: import("@prisma/client/runtime/library").Decimal | null;
            grNumber: string;
            grDate: Date;
            purchaseOrderId: string | null;
            receiptType: import(".prisma/client").$Enums.ReceiptType;
            receiptSource: import(".prisma/client").$Enums.ReceiptSource;
            inwardShift: import(".prisma/client").$Enums.InwardShift | null;
            supplierRef: string | null;
        };
        idempotent: boolean;
    }>;
}
